Add Org.qgis.qgis-ltr
flathub/flathub pull request #1826
Opened 2020-09-13 15:12 UTC by hristo-mavrodiev

The Org.qgis.qgis contains the latest version of QGIS. This version is not a "production" environment for GIS projects. Purpose of this repo is to add the latest stable LTR version of QGIS. For example in Arch linux there are qgis and qgis-ltr packages - https://www.archlinux.org/packages/community/x86_64/qgis/  and https://aur.archlinux.org/packages/qgis-ltr/?O=20&PP=10

2020-09-13 15:48 UTC, barthalion requested changes

2020-09-13 15:48 UTC, barthalion commented on README.md
> +## The LTR version of QGIS copied from https://github.com/flathub/org.qgis.qgis
There's no point in having it here. No user is going to ever read it.

2020-09-13 15:48 UTC, barthalion commented on flathub.json
> +    "skip-appstream-check": true
Appdata should be fixed instead of disabling the check, and if it doesn't already, it should mention it's an LTR version.

2020-09-13 15:49 UTC, barthalion commented
How common is it to prefer LTR version over the latest one? Also for the record, Arch ships only latest QGIS. AUR is free-for-all thing.

cc @aleixpol

2020-09-13 15:49 UTC, barthalion commented
bot, build org.qgis.qgis-ltr

2020-09-13 18:00 UTC, hristo-mavrodiev commented
bot, build org.qgis.qgis-ltr

2020-09-13 19:53 UTC, hristo-mavrodiev commented
bot, build org.qgis.qgis-ltr

2020-09-13 21:03 UTC, aleixpol commented
> How common is it to prefer LTR version over the latest one? Also for the record, Arch ships only latest QGIS. AUR is free-for-all thing.
> 
> cc @aleixpol

I was planning to look into it as well. My plan was to have it in a branch for org.qgis.qgis rather than a separate repo. If someone else to maintain it, that works too.

I asked QGIS maintainers and they recommended to prefer this version to the latest. I'm guessing it's because of the extended use of the python scripting this system does.

I can commit to keep this LTR (or a branch, I actually asked in flatpak@ mailing list about this already) up to date if you want together with the stable version if someone wants.

It feels a bit odd that as is here, they will be listed as separate applications.

2020-09-13 21:46 UTC, LeandroStanger commented on org.qgis.qgis-ltr.json
> +    "runtime-version" : "5.12",
Update runtime to 5.15
```suggestion
    "base-version": "5.15",
    "runtime" : "org.kde.Platform",
    "runtime-version" : "5.15",
```

2020-09-15 08:27 UTC, barthalion commented
> I was planning to look into it as well. My plan was to have it in a branch for org.qgis.qgis rather than a separate repo. If someone else to maintain it, that works too.

It depends what you want to achieve. If LTR is pushed as a separate branch of existing QGIS, only one will be visible in the system application list. The other can be still launched from CLI with `flatpak run --branch=foobar` or made default via `flatpak make-current`.

This also means that LTR and the latest releases will share configuration directories. Unless they're already versioned by the app, it may (or not! I don't use it) cause some issues if they are not compatible.

In such situations separate app id is IMHO preferred but I leave the decision to you.

2020-09-16 07:09 UTC, hristo-mavrodiev commented
Sometimes the QGIS config is messed up (even when not switching versions) - QGIS fails to start, some bugs appear also.By default QGIS configs are stored in "/home/USER/.local/share/QGIS/QGIS3/"
The configuration files when using flatpak are store in   "$HOME/.var/app/org.qgis.qgis/data/QGIS/QGIS3"
Just deleting "org.qgis.qgis" folder will solve the issue and QGIS creates new configuration files. It's like a fresh new install.
The proposed build for LTR version fails, because it's now searching for qgis-ltr executable(desktop icon) instead of qgis. I have no idea how to solve this.
As a GIS user what I think that other people will love to see is to have the ability to choose a specific version for QGIS, like they have this choice on WinOS or MacOS. Also to have the same version of the important GIS dependencies (Qt, GDAL/OGR, GEOS, SQLite, PostgreSQL Client Version, QWT Version, PROJ, SpatiaLite Version, QScintilla2 Version, GRASS, SAGA,OracleDB driver, MSSQL DB driver) between the existing windows built and flatpak. So no matter you are using Linux or Windows you will have same result for this QGIS version.  It will be great if we could provide same experience as choosing an org.kde.sdk for example:
![kde sdk](https://user-images.githubusercontent.com/61916767/93302631-fad35b80-f802-11ea-854e-49bba2a69d8c.png)
I will try to help you, but I don't have the knowledge to fully maintain the LTR version. Probably to stay with org.qgis.qgis will be better...

2020-11-16 02:04 UTC, eszlari commented
I would try to avoid dashes in the App ID, since only the last part of the domain can contain one. If you would add extensions later, you would have using some like `org.qgis.qgis_ltr.Extension`.

I would use `org.qgis.qgis.LTR` as an ID.

2020-11-16 02:05 UTC, aleixpol commented
I created an lts branch of it, I'd say we should go with that and close this PR

2020-11-16 02:08 UTC, eszlari commented
> The proposed build for LTR version fails, because it's now searching for qgis-ltr executable(desktop icon) instead of qgis. I have no idea how to solve this.

You need to add `rename-desktop-file` (and `rename-appdata-file`) to the manifest to adjust the ID.

2020-11-16 02:15 UTC, eszlari commented
> I created an lts branch of it, I'd say we should go with that and close this PR

Depends on if @hristo-mavrodiev wants to use both version in parallel easily.

Also: AFAIK this branch is not exposed in gnome-software, plasma-discover or flathub.org at the moment.

2020-11-16 02:38 UTC, aleixpol commented
Discover should, and I don't see why other clients wouldn't.

2020-11-16 07:26 UTC, barthalion commented
Aleix decided to use a branch so we're going to stick with it.

2020-11-16 07:26 UTC, closed without merging