WIP: Add org.openchemistry.avogadro2
flathub/flathub pull request #2234
Opened 2021-03-31 16:25 UTC by kevinsmia1939

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://discuss.avogadro.cc/t/im-creating-flatpak-for-avogadro2-need-help-on-spglib/3456/17
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-03-31 16:33 UTC, kevinsmia1939 commented
why flathubbot think it is a json file?

2021-03-31 20:59 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-01 07:38 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-01 09:12 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-01 13:34 UTC, nedrichards commented
bot, build org.openchemistry.Avogadro2

2021-04-08 18:53 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-08 19:00 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-09 09:00 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-09 14:15 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-09 18:42 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-11 04:08 UTC, hfiguiere commented
bot, build org.openchemistry.Avogadro2

2021-04-11 07:44 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-11 14:28 UTC, hfiguiere requested changes

2021-04-11 15:59 UTC, kevinsmia1939 commented on org.openchemistry.Avogadro2.yaml
> +  - name: libarchive
Thanks, I will remove it. How do I check if it already in runtime?

2021-04-11 16:13 UTC, kevinsmia1939 commented
bot, build org.openchemistry.Avogadro2

2021-04-11 20:45 UTC, hfiguiere commented on org.openchemistry.Avogadro2.yaml
> +  - name: libarchive
usually I try to build and add dependencies as needed. Or I look into the runtime itself. It's a lot of trial and effort.

2021-04-13 02:16 UTC, hfiguiere commented
bot, build org.openchemistry.Avogadro2

2021-04-14 07:14 UTC, barthalion commented
```
ScriptLoader::queryProgramName: Unable to retrieve program name for "/app/lib/avogadro2/scripts/formatScripts/cclibScript.py" ; "Error running script '/usr/bin/python3 /app/lib/avogadro2/scripts/formatScripts/cclibScript.py --display-name --lang en_DK': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\nTraceback (most recent call last):\n  File \"/app/lib/avogadro2/scripts/formatScripts/cclibScript.py\", line 22, in <module>\n    from cclib.io.ccio import ccopen\nModuleNotFoundError: No module named 'cclib'\n"
```

Not sure if it's a blocker for anything.

2021-04-14 07:15 UTC, barthalion commented
Hey @ghutchis, would you or someone else working on Avogadro be interested in co-maintaning it on Flathub? There's no obligation to do so, but we have a rule about upstream involvement and we'd like you to have write access even when @kevinsmia1939 will be handling the maintenance.

2021-04-14 13:30 UTC, ghutchis commented
> Not sure if it's a blocker for anything.

No, that's not a blocker. We need to clean up our warnings - we try to load Python scripts at that stage. (That particular script will be made an optional post-install one soon.)

2021-04-14 13:32 UTC, ghutchis commented
> Hey @ghutchis, would you or someone else working on Avogadro be interested in co-maintaning it on Flathub? 

Sure, that's fine.

As a side question, is there a good way to make the Flatpak available as part of our GH actions builds? We've had some people frustrated with the official packages, and we'd like to add it to continuous release packaging.

2021-04-15 08:05 UTC, barthalion commented
> As a side question, is there a good way to make the Flatpak available as part of our GH actions builds? We've had some people frustrated with the official packages, and we'd like to add it to continuous release packaging.

There are multiple ways to do that. You can either use https://github.com/flathub/flatpak-external-data-checker/ or "abuse" GitHub Actions as event bus like here:

https://github.com/flathub/io.openrct2.OpenRCT2/blob/master/.github/workflows/beta.yml
https://github.com/OpenRCT2/OpenRCT2/pull/12836/files

This is for pushing every commit to Flathub Beta which is generally discouraged but can be tuned to update Flathub when you push a new tag.

2021-04-15 08:06 UTC, barthalion commented
/merge @ghutchis

2021-04-15 08:06 UTC, closed without merging