WIP: Add org.pymol.PyMOL
flathub/flathub pull request #2317
Opened 2021-05-07 20:24 UTC by kevinsmia1939

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** No respond yet https://github.com/schrodinger/pymol-open-source/issues/172
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-05-07 20:26 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-07 21:13 UTC, kevinsmia1939 commented
I don't understand the error.

2021-05-08 15:10 UTC, tinywrkb commented
This is strange, it looks like the CI doesn't find appstream-util. Try running the bot again.

2021-05-08 15:10 UTC, tinywrkb commented
bot, build org.pymol.PyMOL

2021-05-10 11:57 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-15 10:58 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-16 19:17 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-16 21:56 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-16 22:10 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-16 22:29 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-17 07:18 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-17 08:07 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-17 10:27 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-17 11:43 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-17 15:18 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-17 15:58 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-18 01:58 UTC, kevinsmia1939 commented
It is ready now. Upstream dev are not interest to maintain 3rd party package.

2021-05-18 02:04 UTC, hfiguiere requested changes

2021-05-18 02:04 UTC, hfiguiere commented on org.pymol.PyMOL.metainfo.xml
> + <id>org.pymol.PyMOL.desktop</id>
```suggestion
 <id>org.pymol.PyMOL</id>
```

2021-05-18 02:13 UTC, hfiguiere commented
> It is ready now. Upstream dev are not interest to maintain 3rd party package.

Did you submit the appdata and desktop file upstream? They are not specific to Flatpak.

2021-05-18 07:01 UTC, kevinsmia1939 commented on org.pymol.PyMOL.metainfo.xml
> + <id>org.pymol.PyMOL.desktop</id>
thanks

2021-05-18 07:01 UTC, kevinsmia1939 commented
> > It is ready now. Upstream dev are not interest to maintain 3rd party package.
> 
> Did you submit the appdata and desktop file upstream? They are not specific to Flatpak.

Not yet, but I will sent pr to them.

2021-05-18 07:01 UTC, kevinsmia1939 commented
bot, build org.pymol.PyMOL

2021-05-19 05:51 UTC, kevinsmia1939 commented
It should be good now.

2021-05-20 07:54 UTC, barthalion commented
/merge

2021-05-20 07:55 UTC, closed without merging