Add index flatpak
flathub/flathub pull request #2328
Opened 2021-05-13 20:35 UTC by ognarb

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. (I contribute a bit to Maui apps but I'm not the maintainer. The maintainer knows that I'm submitting this MR)
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). (sort of but it's part of KDE and I'm a KDE dev)
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-05-13 20:36 UTC, ognarb commented
bot, build org.kde.index

2021-05-13 20:52 UTC, ognarb commented
bot, build org.kde.index

2021-05-13 20:57 UTC, ognarb commented
bot, build org.kde.index

2021-05-13 21:35 UTC, ognarb commented
bot, build org.kde.index

2021-05-13 22:50 UTC, hfiguiere requested changes

2021-05-13 22:50 UTC, hfiguiere commented on org.kde.index.json
> +        "--socket=x11",
```suggestion
        "--socket=fallback-x11",
```

2021-05-14 00:56 UTC, hfiguiere requested changes

2021-05-14 00:56 UTC, hfiguiere commented on org.kde.index.json
> +        "--env=XDG_DATA_DIRS=/usr/share:/app/share/"
```suggestion
```

2021-05-14 07:12 UTC, barthalion commented on org.kde.index.json
> +    "separate-locales": false,
```suggestion
```

2021-05-14 15:42 UTC, ognarb commented
bot, build org.kde.index

2021-05-16 06:27 UTC, nedrichards commented
@flathub/kde FYI

2021-05-16 20:34 UTC, travier commented
Not tested but LGTM. Have you submitted the metadat patches upstream? Thanks

2021-05-17 07:17 UTC, barthalion commented
/merge

2021-05-17 07:19 UTC, closed without merging