Init
flathub/flathub pull request #2369
Opened 2021-06-07 18:16 UTC by necessarily-equal

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/Unvanquished/
- [x] Upstream owns the domain used in the application ID.
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

The patch isn't submitted upstream. We are discussing what the proper semantics we should prefer (probably removing the -connect?) to have a *single* desktop file. We don't have the requirement outside of flatpaks, because we do simply distribute two of them.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

CC @illwieckz

2021-06-07 19:43 UTC, hfiguiere requested changes

2021-06-07 19:48 UTC, hfiguiere commented on net.unvanquished.Unvanquished.yml
> +        path: 0001-Suppress-a-warning.patch
nevermind. I also missed it.

2021-06-07 19:48 UTC, hfiguiere commented
bot, build net.unvanquished.Unvanquished

2021-06-07 20:36 UTC, necessarily-equal commented on net.unvanquished.Unvanquished.desktop
> +Exec=/app/bin/unvanquished -connect %u
Is this safe from any conflict with the outside? For example if people would download a distro package too?

2021-06-07 20:43 UTC, necessarily-equal commented
Should build fine now

2021-06-07 21:57 UTC, hfiguiere commented
bot, build net.unvanquished.Unvanquished

2021-06-07 22:04 UTC, hfiguiere requested changes

2021-06-07 22:04 UTC, hfiguiere commented on net.unvanquished.Unvanquished.yml
> +      - cp -a unvanquished /app/bin/
There is no `/app/bin` so you need to create it. Usually we use `install` instead of `cp`

2021-06-07 22:05 UTC, hfiguiere commented
Have the appdata and destkop files submitted upstream?

2021-06-07 22:09 UTC, hfiguiere commented
bot, build net.unvanquished.Unvanquished

2021-06-07 22:10 UTC, necessarily-equal commented
The desktop file is a tweaked upstream one. It was initially sed'ed but at the 4th sed command I thought it was simpler to copy it. The appstream is in-PR, https://github.com/Unvanquished/Unvanquished/pull/1422, but the chicken-and-egg problem on release time is annoying. Not sure what the usual way to handle it is.

2021-06-07 22:16 UTC, hfiguiere commented
> The desktop file is a tweaked upstream one. It was initially sed'ed but at the 4th sed command I thought it was simpler to copy it. The appstream is in-PR, [Unvanquished/Unvanquished#1422](https://github.com/Unvanquished/Unvanquished/pull/1422), but the chicken-and-egg problem on release time is annoying. Not sure what the usual way to handle it is.

It's better to patch then.

2021-06-07 22:46 UTC, necessarily-equal commented
I must say I have no idea why the build fails

2021-06-07 22:47 UTC, hfiguiere commented
bot, build net.unvanquished.Unvanquished

2021-06-07 22:55 UTC, hfiguiere commented
tbf not sure what's happening here either.

2021-06-07 22:58 UTC, necessarily-equal commented
looks like it tries to fetch Unvanquished.git/src/utils/cbse ; but this repo shouldn't be recursed

```yaml
      - type: git # used for the icons
        disable-submodules: true
        dest: unv 
        url: https://github.com/Unvanquished/Unvanquished
        tag: unvanquished/0.52.0
```

2021-06-08 00:03 UTC, necessarily-equal commented
about the desktop file, I've opened https://github.com/Unvanquished/Unvanquished/issues/1424 and https://github.com/Unvanquished/Unvanquished/issues/1423. I don't really want to clone yet another repo to get one half of a desktop file and add the other half manually. So I'd keep it like that for now hoping to get it right on the next release.

2021-06-08 00:04 UTC, necessarily-equal commented
About the build error, well, locally it works :shrug:

2021-06-08 00:20 UTC, hfiguiere commented
> about the desktop file, I've opened [Unvanquished/Unvanquished#1424](https://github.com/Unvanquished/Unvanquished/issues/1424) and [Unvanquished/Unvanquished#1423](https://github.com/Unvanquished/Unvanquished/issues/1423). I don't really want to clone yet another repo to get one half of a desktop file and add the other half manually. So I'd keep it like that for now hoping to get it right on the next release.

You don't need to clone repo.  All you need is to add a patch. Github allow getting individual patches for commit.

2021-06-08 00:22 UTC, necessarily-equal commented
> You don't need to clone repo. All you need is to add a patch. Github 
> allow getting individual patches for commit.
> 

Well, the desktop files are stored in the updater repo, 
https://github.com/Unvanquished/updater/

2021-06-10 12:02 UTC, barthalion commented
bot, build net.unvanquished.Unvanquished

2021-06-10 14:05 UTC, barthalion commented
bot, build net.unvanquished.Unvanquished

2021-06-10 15:31 UTC, barthalion commented
bot, build net.unvanquished.Unvanquished

2021-06-10 15:32 UTC, necessarily-equal commented
Any reason for dropping the thumbnails, may I ask?

On Thu, Jun 10 2021 at 15:31:46 +0000, Flathub Bot 
***@***.***> wrote:
> Queued test build for net.unvanquished.Unvanquished.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

2021-06-10 20:13 UTC, hfiguiere commented on net.unvanquished.Unvanquished.yml
> +        path: net.unvanquished.Unvanquished.metadata.xml
```suggestion
        path: net.unvanquished.Unvanquished.metainfo.xml
```

2021-06-10 21:41 UTC, barthalion commented on net.unvanquished.Unvanquished.yml
> +        path: net.unvanquished.Unvanquished.metadata.xml
Bah.

2021-06-10 21:41 UTC, barthalion commented
bot, build net.unvanquished.Unvanquished

2021-06-11 06:13 UTC, barthalion commented
OK, it's something:

```
builddir/files/share/appdata/net.unvanquished.Unvanquished.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
```

@necessarily-equal Mind adding OARS section?

Re: thumbnails, appstream-util generates thumbnails from the source images and then we serve these from CDN, so it would be overwritten anyway.

2021-06-11 13:53 UTC, necessarily-equal commented
> @necessarily-equal Mind adding OARS section?

I did write one.

I have some doubts about some sections though. For example the discrimination thingy: all members of a team are equal and it's fine, but the objective of the game is to eliminate the other team. You can call it pest-control, but you could also consider it to be a genocide? Likewise, human-to-alien is fantasy violence (non-existing target) with realistic weapons (guns), but alien-to-human is against real-looking persons (cloned humans), but with unrealistic weapons. Since none of this is possible in real life, I did put mild — but moderate could be appropriate too

2021-06-11 13:55 UTC, necessarily-equal commented
Also in-game chat can be moderated, but we can't make sure every server is. Should I put *intense* here?

2021-06-11 21:55 UTC, barthalion commented
Eh, in reality it's just the best effort rating. What you picked looks sane to me.

bot, build net.unvanquished.Unvanquished

2021-06-11 22:09 UTC, barthalion commented
It displays following messages for me (in the terminal, but the last one also in UI):

```
Warn: Could not open an OpenAL device. 
Warn: Couldn't initialize the audio subsystem
```

2021-06-12 00:27 UTC, hfiguiere commented
Maybe it needs `--device=all` for audio (not using pulse). Just an idea.

2021-06-12 04:04 UTC, necessarily-equal commented
I've force-disabled the openAL backend, does that work for you?

2021-06-12 04:57 UTC, illwieckz commented
When installing this flatpak on a computer running Nvidia's 340 driver, flatpak installs `org.freedesktop.Platform.GL.nvidia-340-108` and then the `Warn: GLW_StartOpenGL() - could not load OpenGL subsystem: Missing GL version` is error is faced. see https://github.com/DaemonEngine/Daemon/issues/474

One known fix is to add `-DOpenGL_GL_PREFERENCE=LEGACY` to cmake call. This means the game will probably not be `GLVND` compatible, but the game would be expected to run everywhere there is a working GL driver.

Note: the prebuilt binary from `unvanquished_0.52.0.zip` is expected to not be affected.

2021-06-12 05:37 UTC, necessarily-equal commented
I've added the cmake flags. I'll add it to the nixpkg too, just in case.

2021-06-12 17:22 UTC, AsciiWolf commented
Sound works fine now. Tested on my Fedora 33 system. Also, I did not notice any issues, game seems to be fully playable. :-)

2021-06-12 17:30 UTC, AsciiWolf commented
I have tried enabling OpenAL with `-set s_useOpenAL=1` and sound still works fine. @barthalion What distro you are trying it on? Fedora 34? Maybe it is a PipeWire related bug.

2021-06-12 19:00 UTC, closed without merging

2021-06-12 19:04 UTC, AsciiWolf commented
@necessarily-equal Why did you close the PR?

2021-06-12 19:07 UTC, necessarily-equal commented
I've got no idea why github closed the PR — I wasn't even connected. Can someone reopen it?

2021-06-12 19:10 UTC, necessarily-equal commented
About the openAL error, forget about `s_useOpenAL`, it doesn't do anything

I have seen this warning form time to time. Maybe it is related?
```
--- Common Initialization Complete --- 
Calling GetRefAPI… 
SDL_Init( SDL_INIT_VIDEO )...  
Using SDL Version 2.0.12 
]
** (process:181058): WARNING **: 13:54:45.130: Error writing credentials to socket: Error sending message: Broken pipe
SDL using driver "x11" 
Initializing OpenGL display 
```

It seems to be a race condition. Not sure why it happens.

2021-06-12 22:07 UTC, barthalion commented
I think only you can re-open it but I don't think it really matters.

@AsciiWolf yeah, F34.

2021-06-12 22:07 UTC, barthalion commented
bot, build net.unvanquished.Unvanquished

2021-06-13 09:59 UTC, barthalion commented
It works for me now. Thanks @necessarily-equal for sorting it out.

/merge @illwieckz

2021-06-13 13:00 UTC, AsciiWolf commented
@necessarily-equal @barthalion Any chance that I could help co-maintain this Flatpak? :-) I already maintain the Tremulous Flatpak on Flathub and Unvanquished is based on Tremulous.

2021-06-22 18:47 UTC, illwieckz commented
@AsciiWolf the proposal is appreciated, though for the moment I'm not sure the amount of work required to update the flatpak is high enough to need third-party help. We definitely needed help to set it up at first, but now that it's done, it looks like updating on new release is basically a matter of a new git revision and some url to paste. Don't hesitate to submit pull requests if you seen any enhancement to do, that would be welcome !