Add org.kde.ktrip
flathub/flathub pull request #2370
Opened 2021-06-07 19:42 UTC by nicolasfella

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
I am the upstream maintainer
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ x Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-06-07 19:43 UTC, nicolasfella commented
bot, build org.kde.ktrip

2021-06-07 19:46 UTC, hfiguiere requested changes

2021-06-07 19:46 UTC, hfiguiere commented on org.kde.ktrip.json
> +        "--socket=x11",
```suggestion
        "--socket=fallback-x11",
```

2021-06-07 19:46 UTC, hfiguiere commented on org.kde.ktrip.json
> +            "sources": [ { "type": "archive", "url": "https://download.kde.org/unstable/kirigami-addons/0.2/kirigami-addons-0.2.tar.xz", "sha1": "a9c5c913fd7cbb1ebe17bffef32a1c1d744a9a33"} ]
sha256 are preferred.

2021-06-07 19:46 UTC, hfiguiere commented on org.kde.ktrip.json
> +                { "type": "archive", "url": "https://download.kde.org/stable/plasma-mobile/21.05/ktrip-21.05.tar.xz", "sha1": "25a1d6ad85b3454ea42b2aa43fe0c8b8bb9810e9" }
sha256 preferred

2021-06-07 19:50 UTC, nicolasfella commented
The appstream issues will be fixed with the 21.06 release in a few days

2021-06-10 11:11 UTC, nicolasfella commented
bot, build org.kde.ktrip

2021-06-10 11:53 UTC, nicolasfella commented
bot, build org.kde.ktrip

2021-06-10 12:56 UTC, barthalion commented
cc @flathub/kde

2021-06-10 21:27 UTC, tsdgeos commented on org.kde.ktrip.json
> +                    "url": "https://download.kde.org/stable/release-service/21.04.1/src/kpublictransport-21.04.1.tar.xz",
.2 was relased today ^_^

2021-06-10 21:43 UTC, nicolasfella commented
bot, build org.kde.ktrip

2021-06-11 08:30 UTC, barthalion commented
/merge

2021-06-11 08:31 UTC, closed without merging