Add com.github.weclaw1.ImageRoll
flathub/flathub pull request #2374
Opened 2021-06-10 18:40 UTC by weclaw1

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-06-10 18:51 UTC, hfiguiere requested changes

2021-06-10 18:51 UTC, hfiguiere commented on com.github.weclaw1.ImageRoll.yaml
> +runtime-version: '3.38'
```suggestion
runtime-version: '40'
```

2021-06-10 18:51 UTC, hfiguiere commented on com.github.weclaw1.ImageRoll.metainfo.xml
> +<?xml version="1.0" encoding="UTF-8"?>
why adding this file since it's installed from the sources

2021-06-10 18:52 UTC, hfiguiere commented
bot, buld com.github.weclaw1.ImageRoll

2021-06-10 18:54 UTC, hfiguiere commented
bot, build com.github.weclaw1.ImageRoll

2021-06-10 19:03 UTC, weclaw1 commented on com.github.weclaw1.ImageRoll.yaml
> +runtime-version: '3.38'
Fixed

2021-06-10 21:55 UTC, LeandroStanger commented
bot, build com.github.weclaw1.ImageRoll

2021-06-11 08:30 UTC, barthalion commented
/merge

2021-06-11 08:30 UTC, closed without merging