Com.GitHub.kalibari.audok
flathub/flathub pull request #2420
Opened 2021-07-12 22:17 UTC by kalibari

### Please confirm your submission meets all the criteria

- [ x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x ] My pull request follows the instructions at [App Submission][submission].
- [x ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-07-13 01:18 UTC, hfiguiere commented
Since this is a duplicate of #2416, can close it?

(it wasn't necessary to open a new one)

2021-07-13 01:53 UTC, hfiguiere requested changes

2021-07-13 01:53 UTC, hfiguiere commented on com.github.kalibari.audok.json
> +            "no-make-install": true,
This won't install the binaries, or did I miss something?

2021-07-13 01:53 UTC, hfiguiere commented
bot, build com.github.kalibari.audok

2021-07-13 02:07 UTC, hfiguiere commented
x86_64 fail to build because: `• file-invalid          : <screenshot> failed to load [https://github.com/kalibari/audok/blob/master/audok/screenshot.png]`

aarch64: streamripper needs to have the configure files updated.

2021-07-13 19:21 UTC, kalibari commented
> Since this is a duplicate of #2416, can close it?
> 
> (it wasn't necessary to open a new one)

Hello  hfiguiere, yes please close it, thank you!

2021-07-13 19:23 UTC, hfiguiere requested changes

2021-07-13 19:23 UTC, hfiguiere commented on flatpak.json
> +    "only-arches": ["x86_64"]
why????

2021-07-13 19:23 UTC, hfiguiere commented on com.github.kalibari.audok.json
> +            "no-make-install": false,
```suggestion
```

2021-07-13 19:23 UTC, hfiguiere commented on com.github.kalibari.audok.json
> +            "no-make-install": false,
```suggestion
```

2021-07-13 19:23 UTC, hfiguiere commented on com.github.kalibari.audok.json
> +            "make-install-args": ["PREFIX=/app"],
```suggestion
```

You shouldn't need this.

2021-07-13 19:23 UTC, hfiguiere commented on com.github.kalibari.audok.json
> +            "no-make-install": false,
```suggestion
```

2021-07-13 19:24 UTC, hfiguiere commented
> > Since this is a duplicate of #2416, can close it?
> > (it wasn't necessary to open a new one)
> 
> Hello hfiguiere, yes please close it, thank you!

I can't but you can and should.

2021-07-14 00:15 UTC, hfiguiere commented
bot, build com.github.kalibari.audok

2021-07-14 08:03 UTC, barthalion commented
Building streamripper fails on aarch64. You can fix it like this: https://github.com/flathub/org.gimp.GIMP/blob/f819d5614ca19d3ffff99f2040881a873daa175f/org.gimp.GIMP.json#L249

2021-07-14 13:36 UTC, hfiguiere requested changes
Also none of the suggestion I made were applied albeit they were resolved.

2021-07-14 13:36 UTC, hfiguiere commented on flatpak.json
> +{
This file does nothing anyway as it has the wrong filename.

See https://github.com/flathub/flathub/pull/2420#issuecomment-879684329 on how to resolve the aarch64 build issue.

2021-08-01 22:58 UTC, nedrichards commented
bot, build com.github.kalibari.audok

2021-08-02 03:00 UTC, hfiguiere commented on com.github.kalibari.audok.json
> +                    "commands": [ "cp -p /usr/share/automake-*/config.{sub,guess} ." ]
```suggestion
                    "commands": [ 
                        "cp -p /usr/share/automake-*/config.{sub,guess} .",
                        "cp -p /usr/share/automake-*/config.{sub,guess} libmad-0.15.1b/"
                    ]
```

This should fix the build. There is a subproject in the tarball that needed the same treatment.

2021-08-02 03:01 UTC, hfiguiere commented on com.github.kalibari.audok.json
> +            "no-make-install": false,
```suggestion
```

You don't need that line.

2021-08-02 14:07 UTC, kalibari commented
update com.github.kalibari.audok.json

2021-08-02 14:07 UTC, kalibari commented
audo

2021-08-02 16:54 UTC, hfiguiere commented
bot, build com.github.kalibari.audok

2021-08-07 04:04 UTC, hfiguiere commented
bot, build com.github.kalibari.audok

2021-08-10 19:24 UTC, nedrichards commented
/merge

2021-08-10 19:25 UTC, closed without merging