Create VCMI manifest
flathub/flathub pull request #2446
Opened 2021-08-02 16:53 UTC by Alexander-Wilms

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. @ArseniyShestakov I couln't register a forum account.  Would someone on the VCMI team be interested in (co-)maintaining this package?
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

This manifest doesn't use a specific VCMI tag or commit, since

_As of January 2021, we dont make big official releases anymore, but instead we provide a new version every several days: everytime when there is a new feature finished or new bug fixed.
Although there are no official "big releases", we reccomend updating the game at least twice a year, to make sure you have an updated, best version.
We try not to break savegame files compatibility, so you shouldnt have problem returning to your old games after update.
Please see corresponding "installation on" articles for details for your platform._

- https://wiki.vcmi.eu/Main_Page

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-08-02 16:57 UTC, Alexander-Wilms commented
bot, build eu.vcmi.VCMI

2021-08-02 16:58 UTC, hfiguiere requested changes

2021-08-02 16:58 UTC, hfiguiere commented on eu.vcmi.VCMI.yaml
> +        branch: develop
you need a commit and no branch here.

2021-08-02 17:10 UTC, hfiguiere commented on eu.vcmi.VCMI.yaml
> +        branch: develop
yes. otherwise the build isn't reproducible.

2021-08-02 17:41 UTC, Alexander-Wilms commented
bot, build eu.vcmi.VCMI

2021-08-02 17:47 UTC, hfiguiere commented
Why disabling aarch64? There is a version of luajit that builds on aarch64.
https://github.com/flathub/io.github.GnomeMpv/blob/ac259f54667bd82df9b13c67da1fb15544f41137/org.luajit.Luajit.json

2021-08-02 17:50 UTC, Alexander-Wilms commented
Ah, okay. I didn't use 2.1.0 since it's still a beta.

2021-08-02 17:51 UTC, hfiguiere commented
you could choose to use the beta ony for aarch64.

2021-08-02 17:53 UTC, Alexander-Wilms commented
Just using one version is easier, if that's alright.

2021-08-06 17:48 UTC, Alexander-Wilms commented
@hfiguiere Could you merge this?

2021-08-06 18:07 UTC, hfiguiere commented
I can't, I don't have permissions.

2021-09-07 22:12 UTC, closed without merging