Add org.denemo.Denemo
flathub/flathub pull request #2460
Opened 2021-08-13 13:59 UTC by fedelibre

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. *I contributed only translations in the past. I sent a private email to Richard Shannon, who gave me his Ok.*
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge). *Not me, but the project owners do own the domain.*
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-08-13 14:03 UTC, fedelibre commented
I'm CCing @nbenitez who helped me a lot

2021-08-13 14:04 UTC, fedelibre commented
bot, run org.denemo.Denemo

2021-08-13 14:04 UTC, fedelibre commented
bot, build org.denemo.Denemo

2021-08-13 21:14 UTC, hfiguiere requested changes

2021-08-15 16:00 UTC, hfiguiere commented
bot, build org.denemo.Denemo

2021-08-15 20:31 UTC, fedelibre commented
> Build [56279 failed](https://flathub.org/builds/#/builders/32/builds/56279)

It's checking for a 128x128 icon. It cannot find it because Denemo source has only a 60px PNG icon and no SVG.
I'll ask Richard.

By the way, I've discussed with him about changing the icon installation path and the application id. He's open to accept these changes, but he's concerned about the Windows builds. I'll tackle this after getting a successful build here and replying to PR reviews.

2021-08-16 01:09 UTC, hfiguiere commented
if you put `"skip-appstream-check": true` in a `flathub.json` it will let you have it until icon is fixed.

2021-08-17 07:57 UTC, barthalion commented
There's also `skip-icons-check` to disable this specific test.

2021-08-17 13:01 UTC, hfiguiere commented
I meant `skip-icon-check`, indeed.

2021-08-17 15:02 UTC, fedelibre commented
Richard told me that the SVG was lost during the migration from cvs to git.
He pushed a 128px icon file, but there's no added value since it's simply the 60px image enlarged.
So I'll use the `skip-icons-check`.

I'm on a slow Internet connection for 10 days. When I'm back home I'll see if I can find the SVG somewhere...

2021-08-17 15:04 UTC, fedelibre commented
bot, build org.denemo.Denemo

2021-08-17 21:46 UTC, fedelibre commented on org.denemo.Denemo.yaml
> +  - name: pango
No reason,  I just missed it was already in the SDK.

2021-08-17 21:46 UTC, fedelibre commented on org.denemo.Denemo.yaml
> +        url: http://files.portaudio.com/archives/pa_stable_v190600_20161030.tgz
Ok, thanks. Updated, I'm testing the build on my laptop

2021-08-17 22:08 UTC, fedelibre commented
bot, build org.denemo.Denemo

2021-08-20 08:29 UTC, barthalion commented
Does Richard Shann or someone else from the team has GitHub account so we can invite them?

2021-08-20 14:13 UTC, fedelibre commented
No, Richard doesn't have a Github account and he already told me he's not interested in maintaining the flatpak repository.

I think Jeremiah may be interested, so I think you can add him.
@jjbenham do you want to be invited to have write access to the Denemo flatpak repository?

2021-08-21 17:13 UTC, jjbenham commented
I will take care of that soon. I think I have to user accounts jjbenham and
jbenham. I am going to try to switch to jbenham if I can recover my
credentials.

Best,
Jeremiah

On Fri, Aug 20, 2021, 9:18 AM Federico Bruni ***@***.***>
wrote:

> No, Richard doesn't have a Github account and he already told me he's not
> interested in maintaining the flatpak repository.
>
> I think Jeremiah may be interested, so I think you can add him.
> @jjbenham <https://github.com/jjbenham> do you want to be invited to have
> write access to the Denemo flatpak repository?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/flathub/flathub/pull/2460#issuecomment-902722274>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAP6F72TGMD2MTTZCYZUOA3T5ZPIHANCNFSM5CDUVSMQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-22 20:13 UTC, nedrichards commented
I can see various bits of icon chat but fwiw the icon in the about view is missing. It's not a blocker and I'll merge shortly but just to let you know.

2021-08-22 20:13 UTC, nedrichards commented
/merge @jbenham @jjbenham

2021-08-22 20:14 UTC, closed without merging

2021-08-24 21:46 UTC, fedelibre commented
> I can see various bits of icon chat but fwiw the icon in the about view is missing. It's not a blocker and I'll merge shortly but just to let you know.

This should be fixed when upgrading to the next release of Denemo, as in the master branch the application id is now following the reverse-DNS schema.