Add io.github.achetagames.epic_asset_manager
flathub/flathub pull request #2469
Opened 2021-08-19 19:39 UTC by aknarts

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

There are two non standard permissions:
--talk-name=org.freedesktop.secrets - needed to access secrets used by the application
--filesystem=host - Sadly needed as this is a downloader tool that drops assets to a user specified location and eventually to user projects that can be placed anywhere on the machine

2021-08-19 19:40 UTC, aknarts commented
bot, build com.belmoussaoui.Authenticator

2021-08-19 19:41 UTC, aknarts commented
bot, build io.github.achetagames.epic_asset_manager

2021-08-19 19:41 UTC, aknarts commented
> Queued test build for com.belmoussaoui.Authenticator.

Used wrong name...:/

2021-08-19 19:56 UTC, aknarts commented
bot, build io.github.achetagames.epic_asset_manager

2021-08-19 20:12 UTC, aknarts commented
bot, build io.github.achetagames.epic_asset_manager

2021-08-19 20:22 UTC, aknarts commented
bot, build io.github.achetagames.epic_asset_manager

2021-08-19 21:06 UTC, aknarts commented
bot, build io.github.achetagames.epic_asset_manager

2021-08-19 21:13 UTC, aknarts commented
bot, build io.github.achetagames.epic_asset_manager

2021-08-19 21:15 UTC, hfiguiere requested changes

2021-08-19 21:15 UTC, hfiguiere commented on io.github.achetagames.epic_asset_manager.json
> +          "branch" : "main",
```suggestion
```

A branch move which mean next commit, the build break. Build should be reproducible.

2021-08-19 21:15 UTC, hfiguiere commented on io.github.achetagames.epic_asset_manager.json
> +              "branch" : "meson",
```suggestion
```

2021-08-19 21:15 UTC, hfiguiere commented on io.github.achetagames.epic_asset_manager.json
> +              "branch" : "meson",
```suggestion
```

2021-08-19 21:16 UTC, hfiguiere commented on io.github.achetagames.epic_asset_manager.json
> +    ],
For the record, the last build failure says:
`flatpak-builder: Cleanup libsassError: Can't specify build-args in sandboxed build`

2021-08-19 21:18 UTC, aknarts commented on io.github.achetagames.epic_asset_manager.json
> +    ],
That might be the reason why I am failing the build... thanks for pointing those out.

2021-08-19 21:19 UTC, aknarts commented on io.github.achetagames.epic_asset_manager.json
> +    "--filesystem=host",
Explained in the PR, it is a downloader where user specifies where they want to download and eventually place the assets into their projects. From what research I did from people who do use the tool already it is in very random locations. That is why, sadly...

2021-08-19 21:21 UTC, aknarts commented
bot, build io.github.achetagames.epic_asset_manager

2021-08-19 22:04 UTC, aknarts commented
Sorry for the mess I made trying to figure this one out, it is my first one, it was a learning experience.

2021-08-22 20:15 UTC, nedrichards commented
/merge

2021-08-22 20:15 UTC, closed without merging