Add com.sindresorhus.Caprine
flathub/flathub pull request #2471
Opened 2021-08-20 23:37 UTC by dusansimic

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. https://github.com/sindresorhus/caprine/issues/1689
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).

I don't, project maintainer does.

- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-08-21 00:07 UTC, hfiguiere requested changes

2021-08-21 00:07 UTC, hfiguiere commented on flathub.json
> +	"only-arches": ["x86_64"]
why?

2021-08-21 00:07 UTC, hfiguiere commented
bot, build com.sindresorhus.Caprine

2021-08-21 00:43 UTC, dusansimic commented
bot, build com.sindresorhus.Caprine

2021-08-21 01:04 UTC, dusansimic commented on com.sindresorhus.Caprine.yaml
> +  - --filesystem=home:ro
Well it can send files so it needs access to fs. I could set it to only have access to xdg dirs (documents, pictures, videos...).

2021-08-21 02:03 UTC, dusansimic commented
bot, build com.sindresorhus.Caprine

2021-08-21 08:21 UTC, dusansimic commented
bot, build com.sindresorhus.Caprine

2021-08-21 08:36 UTC, dusansimic commented
bot, build com.sindresorhus.Caprine

2021-08-21 22:02 UTC, dusansimic commented on com.sindresorhus.Caprine.yaml
> +  - --filesystem=home:ro
Fixed this by adding Documents, Pictures and Videos directory. All dirs are read only.

2021-08-22 20:02 UTC, nedrichards commented
/merge @sindresorhus

2021-08-22 20:02 UTC, closed without merging