Badabib
flathub/flathub pull request #2532
Opened 2021-09-24 21:29 UTC by RogerCrocker

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
 
  I think "--filesystem=home" might not be necessary, but I don't know how to avoid it.

- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-09-25 00:04 UTC, hfiguiere commented
bot, build com.github.rogercrocker.badabib

2021-09-25 00:04 UTC, hfiguiere requested changes

2021-09-25 00:04 UTC, hfiguiere commented on com.github.rogercrocker.badabib.json
> +    "runtime-version" : "40",
```suggestion
    "runtime-version" : "41",
```

41 is out now

2021-09-25 17:42 UTC, RogerCrocker commented on com.github.rogercrocker.badabib.json
> +    "runtime-version" : "40",
Thanks, I missed that.

2021-09-25 17:47 UTC, RogerCrocker commented
Sorry, I don't know how to fix the build failure. What does it mean that the "validation" of the screenshots failed?

2021-09-26 03:22 UTC, hfiguiere commented
the screenshots listed in the appdata file can't be downloaded since the URL do NOT point to the actual image but to the github page.

2021-09-27 07:39 UTC, barthalion commented
Yup, should be replaced with `https://raw.githubusercontent.com/RogerCrocker/BadaBib/master/data/screenshots/editor.png` (and so on for all the others).

2021-09-27 08:45 UTC, nedrichards commented
If you want to drop filesystem permissions for a GTK app you need to use GTKFileChooserNative rather than GTKFileChooser to open files https://docs.gtk.org/gtk3/class.FileChooserNative.html in the basic case it should be a 'add native to the end of your call' but there are some cases that it doesn't support which may be important to your app so take a look and experiment.

2021-09-27 13:55 UTC, RogerCrocker commented
OK, thanks a lot, that's very helpful. I'll look into these issues later today.

2021-09-27 21:34 UTC, RogerCrocker commented
OK, I corrected the links and replaced GTKFileChooser with GTKFileChooserNative. Can you try again?

2021-09-28 00:24 UTC, hfiguiere commented
bot, build com.github.rogercrocker.badabib

2021-09-28 08:39 UTC, nedrichards commented
/merge

2021-09-28 08:39 UTC, closed without merging

2021-09-28 18:29 UTC, RogerCrocker commented
Great, thanks everyone!