add org.freedesktop.LinuxAudio.Plugins.Calf
flathub/flathub pull request #2541
Opened 2021-09-30 16:05 UTC by Bleuzen

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-09-30 16:46 UTC, hfiguiere commented
there is a problem: the shared-modules are not as a git submodule but directly checked in.

2021-09-30 16:48 UTC, hfiguiere requested changes

2021-09-30 16:48 UTC, hfiguiere commented on org.freedesktop.LinuxAudio.Plugins.Calf.json
> +                "--enable-sse",
this will break when building on `aarch64`

2021-09-30 16:48 UTC, hfiguiere commented on org.freedesktop.LinuxAudio.Plugins.Calf.json
> +        "shared-modules/linux-audio/fluidsynth2.json",
```suggestion
        "shared-modules/linux-audio/fluidsynth2-static.json",
```

The static linking version should be used for plugins.

2021-09-30 16:51 UTC, hfiguiere commented
bot, build org.freedesktop.LinuxAudio.Plugins.Calf

2021-09-30 17:04 UTC, hfiguiere requested changes
Not sure why the build is unable to find (ignoring) glib at link time...

2021-09-30 17:04 UTC, hfiguiere commented on org.freedesktop.LinuxAudio.Plugins.Calf.json
> +            ],
```suggestion
            ],
            "build-options": {
                "arch": {
                    "x86_64": {
                        "config-opts": [
                            "--enable-sse"
                        ]
                    }
                }
            },
```

This how it should be done to enable-sse on x86_64 (the fact they don't do it automatically boggle my mind, there is no x86_64 CPU that don't have SSE)

2021-09-30 17:04 UTC, hfiguiere commented on org.freedesktop.LinuxAudio.Plugins.Calf.json
> +        "/share/man"
```suggestion
        "/share/man",
        "/lib/lv2",
        "/include"
```

2021-09-30 17:06 UTC, Bleuzen commented
It doesn't build anymore since switching to fluidsynth2-static. The non-static version works for me locally.

2021-10-01 04:05 UTC, hfiguiere commented on org.freedesktop.LinuxAudio.Plugins.Calf.json
> +            "build-options": {
```suggestion
            "build-options": {
                "ldflags": "-lpulse-simple -lpulse -lasound -ldbus-1 -lSDL2 -lreadline -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0  -lgomp",
```

This should do the trick.

2021-10-01 15:26 UTC, hfiguiere commented
bot, build org.freedesktop.LinuxAudio.Plugins.Calf

2021-11-13 21:44 UTC, Bleuzen commented
Seems to work now (in Ardour).
@hfiguiere  anything left?

2021-11-13 23:41 UTC, hfiguiere commented
bot, build org.freedesktop.LinuxAudio.Plugins.Calf

2021-11-21 04:51 UTC, hfiguiere commented
LGTM

2021-11-22 09:13 UTC, barthalion commented
/merge:2108 @hfiguiere

2021-11-22 09:14 UTC, barthalion commented
/merge:21.08 @hfiguiere

2021-11-22 09:14 UTC, closed without merging