Com.GitHub.flxzt.rnote
flathub/flathub pull request #2544
Opened 2021-09-30 22:20 UTC by flxzt

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. My app won't run without session-bus permissions
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-09-30 22:21 UTC, flxzt commented
bot, build com.github.flxzt.rnote

2021-09-30 23:42 UTC, hfiguiere requested changes

2021-09-30 23:42 UTC, hfiguiere commented on com.github.flxzt.rnote.json
> +        "--socket=session-bus",
why do you need session bus access? You should just declare which interface you need to access.

2021-10-01 09:37 UTC, barthalion commented
bot, build com.github.flxzt.rnote

2021-10-01 10:54 UTC, barthalion commented
It launches fine, but I can't find a way to actually draw anything. Is there some catch or is it a bug?

2021-10-01 11:00 UTC, flxzt commented
Have you enabled "mouse drawing" from the secondary menu?

2021-10-01 12:16 UTC, barthalion commented
Ah, that makes sense, I missed that option somehow. Can confirm it works, thanks.

/merge

2021-10-01 12:17 UTC, closed without merging