Co.luoja.telyn
flathub/flathub pull request #2546
Opened 2021-10-01 02:56 UTC by Kiwijane3

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-10-01 03:02 UTC, hfiguiere requested changes
From what I can gather, this is x86_64 so you need to disable the `aarch64` build.

Or better, build from source.

2021-10-01 03:02 UTC, hfiguiere commented
do you submit the .desktop, .appdata and icon files upstream?

2021-10-01 03:06 UTC, hfiguiere commented
Also I'm not even sure you need the GNOME runtime. The freedesktop runtime should be enough at that point.

2021-10-01 03:08 UTC, hfiguiere commented
bot, build co.luoja.Telyn

2021-10-01 03:17 UTC, Kiwijane3 commented
The resources are now merged upstream.

2021-10-01 03:31 UTC, hfiguiere requested changes

2021-10-01 03:31 UTC, hfiguiere commented on co.luoja.Telyn.appdata.xml
> +	<update_contact>janef0421@icloud.com</update_contact>
missing: `<releases>`, `<screenshots>`

2021-10-01 03:31 UTC, hfiguiere commented on co.luoja.Telyn.yml
> +      - ls
```suggestion
```

2021-10-01 03:41 UTC, Kiwijane3 commented
I have updated the appdata to include images and releases, and added a flathub.json specifying x86_64 builds.

2021-10-01 03:42 UTC, hfiguiere commented
bot, build co.luoja.Telyn

2021-10-01 03:52 UTC, hfiguiere commented on co.luoja.Telyn.appdata.xml
> +		<release version="1.0.1" date="2021-10-01"
```suggestion
		<release version="1.0.1" date="2021-10-01" />
```

2021-10-01 03:53 UTC, Kiwijane3 commented
I have updated the appdata file, it should now validate.

2021-10-01 04:06 UTC, hfiguiere commented
bot, build co.luoja.Telyn

2021-10-01 04:42 UTC, Kiwijane3 commented
There seems to be some bugs. I'll iron those out.

2021-10-04 01:37 UTC, Kiwijane3 commented
I've resolved the bugs I detected and pushed a modified manifest that fixes them. The application should now be ready to publish.

2021-10-04 10:00 UTC, barthalion commented on co.luoja.Telyn.yml
> +      - install -D co.luoja.Telyn.appdata.xml /app/share/metainfo/co.luoja.Telyn.appdata.xml
It would probably make sense to include these files in the tar.gz you are using above.

2021-10-04 10:01 UTC, barthalion commented
bot, build co.luoja.Telyn

2021-10-04 11:31 UTC, barthalion commented
/merge

2021-10-04 11:32 UTC, closed without merging