Add App manifest
flathub/flathub pull request #2552
Opened 2021-10-02 14:13 UTC by Suzie97

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-10-02 15:31 UTC, hfiguiere requested changes

2021-10-02 15:31 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +pe# This is the same ID that you've used in meson.build and other files
```suggestion
# This is the same ID that you've used in meson.build and other files
```

2021-10-02 15:31 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +runtime-version: '6'
there is no such runtime on flathub

2021-10-02 15:31 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +      branch: master
you'd need a specific tag or commit. not a branch.

2021-10-02 15:31 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +        path: .
this won't work. there is no source here. This should be either a git repository or an archive.

2021-10-02 15:49 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +runtime-version: '40'
```suggestion
runtime-version: '41'
```

2021-10-02 15:57 UTC, hfiguiere requested changes

2021-10-02 15:57 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +  - '--metadata=X-DConf=migrate-path=/com/github/suzie97/communique/'
```suggestion
```
This is only needed if the application did exist on an older runtime

2021-10-02 15:57 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +  - '--own-name=com.github.suzie97.communique.ArticleView'
```suggestion
```

The app already own the name by default.

2021-10-02 16:05 UTC, hfiguiere commented
bot, build com.github.suzie97.communique

2021-10-02 16:33 UTC, hfiguiere commented
graphite is missing.

2021-10-02 16:59 UTC, Suzie97 commented
bot, build com.github.suzie97.communique

2021-10-02 17:13 UTC, Suzie97 commented
@hfiguiere Thank you so much for the help!! 😄 😄

2021-10-02 17:19 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +
```suggestion
```

This is in the runtime.

2021-10-02 17:27 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +        sha256: 524c1bf390f9cdda4fbd9a47b269980dc64ab5280f0801b53bc69d782c72de0e
this is also in the runtime

2021-10-02 17:27 UTC, hfiguiere commented on com.github.suzie97.communique.yml
> +        sha256: 524c1bf390f9cdda4fbd9a47b269980dc64ab5280f0801b53bc69d782c72de0e
```suggestion
```

2021-10-02 18:59 UTC, Suzie97 commented
bot, build com.github.suzie97.communique

2021-10-04 11:46 UTC, barthalion commented
/merge

2021-10-04 11:47 UTC, closed without merging