Add com.github.vikdevelop.googlemaps
flathub/flathub pull request #2632
Opened 2021-11-10 13:13 UTC by vikdevelop

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-11-10 13:22 UTC, hfiguiere commented
I know it will fail

bot, build com.github.vikdevelop.googlemaps

2021-11-10 13:38 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 14:43 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 16:24 UTC, hfiguiere commented
At the top of the build log:

`(flatpak-builder:3595796): flatpak-builder-WARNING **: 16:18:58.868: Unknown property sources for type BuilderManifest`

This is the source of your problems.

(Usually I make sure it buid locally before submitting)

2021-11-10 16:24 UTC, hfiguiere commented
And in plain english `sources` is inside the module, not at the top level.

2021-11-10 16:35 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 16:52 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 17:00 UTC, hfiguiere commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 17:34 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 17:38 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 18:10 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 18:15 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 18:24 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 18:27 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 18:47 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 19:28 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-10 19:32 UTC, vikdevelop commented
bot. build com.github.vikdevelop.googlemaps

2021-11-11 09:39 UTC, nedrichards commented on com.github.vikdevelop.googlemaps.yml
> +       append-path: /usr/lib/sdk/node14/bin
seems like a mismatch between the node16 extension and node14 here? (I haven't looked at this in detail, it may not be)

2021-11-11 09:50 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 11:04 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 15:05 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 15:08 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 15:17 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 15:33 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 15:47 UTC, vikdevelop commented
bot, build com.github,vikdevelop.googlemaps

2021-11-11 15:53 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 15:57 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 16:00 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 16:46 UTC, hfiguiere requested changes

2021-11-11 16:46 UTC, hfiguiere commented on com.github.vikdevelop.googlemaps.yml
> +  append-path: /usr/lib/sdk/node14/bin
```suggestion
  append-path: /usr/lib/sdk/node16/bin
```

Since you use the node16 SDK extension.

2021-11-11 16:46 UTC, hfiguiere commented on com.github.vikdevelop.googlemaps.yml
> +          npm_config_cache: /run/build/googlemaps/flatpak-node/npm-cache
`/run/build/googlemaps` is gone at that point since the module is build.

2021-11-11 16:46 UTC, hfiguiere commented on com.github.vikdevelop.googlemaps.yml
> +        url: https://github.com/vikdevelop/googlemaps/releases/download/1.0.1/node-modules_googlemaps.zip
instead you should use the flatpak-builder-tools to generate a manifest for the dependencies.

2021-11-11 16:47 UTC, hfiguiere commented
BTW you'd save a lot of time trying to build it locally first.

2021-11-11 17:30 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-11 17:33 UTC, vikdevelop commented
bot, build com.github.vikdevelop.googlemaps

2021-11-12 20:18 UTC, closed without merging