Add net.sf.metronomek
flathub/flathub pull request #2634
Opened 2021-11-12 22:11 UTC by SeeLook

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-11-12 22:15 UTC, hfiguiere commented
bot, build net.sf.metronomek

2021-11-12 22:15 UTC, hfiguiere requested changes

2021-11-12 22:15 UTC, hfiguiere commented on net.sf.metronomek.json
> +  "runtime-version": "5.15",
```suggestion
  "runtime-version": "5.15-21.08",
```

2021-11-12 22:15 UTC, hfiguiere commented on net.sf.metronomek.json
> +      "--socket=x11",
```suggestion
      "--socket=fallback-x11",
```
since it seem to support wayland. this disable x11 if wayland is available.

2021-11-12 22:19 UTC, hfiguiere requested changes

2021-11-12 22:19 UTC, hfiguiere commented on net.sf.metronomek.json
> +  "rename-desktop-file": "net.sf.metronomek.desktop",
```suggestion
```
they are already named properly. you don't need this,

2021-11-12 23:36 UTC, hfiguiere commented
bot, build net.sf.metronomek

2021-11-12 23:46 UTC, hfiguiere commented
appdata file needs patching:
```
• attribute-invalid     : <release> timestamp is in the future
• tag-missing           : <url> is not present
```

2021-11-13 23:33 UTC, hfiguiere commented
bot, build net.sf.metronomek

2021-11-14 09:06 UTC, SeeLook commented
Tested.
Works fine.

2021-11-14 21:49 UTC, nedrichards commented
/merge

2021-11-14 21:49 UTC, closed without merging