Create org.emilien.SpaceLaunch
flathub/flathub pull request #2639
Opened 2021-11-14 21:54 UTC by elescoute

Initial version

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-11-14 22:04 UTC, nedrichards commented on org.emilien.SpaceLaunch
> +        "env" : {        }
should be removed if this is really empty

2021-11-14 22:04 UTC, nedrichards commented
bot, build org.emilien.SpaceLaunch

2021-11-14 22:05 UTC, nedrichards commented
your file doesn't have an extension. it needs to be .json if it's a JSON file for the buildbot to pick it up correctly.

2021-11-14 23:23 UTC, hfiguiere requested changes

2021-11-14 23:23 UTC, hfiguiere commented on org.emilien.SpaceLaunch
> +                    "url" : "https://gitlab.com/elescoute/spacelaunch",
when I try to view that project on gitlab, after being asked to login, it's 404. So either it's not the right URL or it is private and in either case, the build will fail. Also usually the checkout url end in `.git`

2021-11-14 23:24 UTC, hfiguiere commented
also do you own that domain? It resolve but the root in `404 not found`

2021-11-15 20:01 UTC, nedrichards commented
bot, build org.emilien.SpaceLaunch

2021-11-15 20:01 UTC, nedrichards commented
bot, build org.emilien.SpaceLaunch

2021-11-16 04:44 UTC, hfiguiere commented
bot, build org.emilien.SpaceLaunch

2021-11-16 04:52 UTC, hfiguiere commented
appstream has both an appdata and metainfo. There should be one, metainfo being the new name.

The app-id in either is wrong and doesn't match the id.

This would explain the build failure.

2021-11-16 21:15 UTC, nedrichards commented
bot, build org.emilien.SpaceLaunch

2021-11-17 08:22 UTC, elescoute commented
It's ready for review.

2021-11-17 09:58 UTC, barthalion commented
/merge

2021-11-17 09:58 UTC, closed without merging