Add com.github.gabutakut.gabutdm
flathub/flathub pull request #2667
Opened 2021-12-05 16:18 UTC by torikulhabib

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/gabutakut/gabutdm
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-12-05 16:51 UTC, hfiguiere requested changes

2021-12-05 16:51 UTC, hfiguiere commented on com.github.gabutakut.gabutdm.yml
> +        tag: master
`master` isn't a tag. It's a branch. You should have a specific commit. Or better use `shared-modules` as it has all that is needed to run it.

2021-12-05 16:51 UTC, hfiguiere commented on com.github.gabutakut.gabutdm.yml
> +  - '*.o'
```suggestion
```

2021-12-05 16:51 UTC, hfiguiere commented on com.github.gabutakut.gabutdm.yml
> +  - '--socket=x11'
```suggestion
```

2021-12-05 16:52 UTC, hfiguiere commented
bot, build com.github.gabutakut.gabutdm

2021-12-05 17:08 UTC, hfiguiere commented on com.github.gabutakut.gabutdm.yml
> +        tag: master
this wasn't resolved.

2021-12-05 22:35 UTC, nedrichards commented
bot, build com.github.gabutakut.gabutdm

2021-12-05 22:48 UTC, hfiguiere commented
There is still an unadressed comment, albeit marked as resolved

2021-12-05 23:49 UTC, hfiguiere commented on com.github.gabutakut.gabutdm.yml
> +        tag: shared-modules
this is not what I said at all.

2021-12-05 23:50 UTC, hfiguiere commented on com.github.gabutakut.gabutdm.yml
> +        tag: shared-modules
See https://github.com/flathub/flathub/wiki/App-Maintenance#required-files for some info

2021-12-06 08:25 UTC, barthalion commented
bot, build com.github.gabutakut.gabutdm

2021-12-06 12:24 UTC, torikulhabib commented
Libcanberra just working use tag: master🥲

2021-12-06 17:19 UTC, hfiguiere commented
> Libcanberra just working use tag: master🥲

I said previously to use the existing shared-module that has all that is needed to build.
`master` is NOT  a tag.

2021-12-07 01:46 UTC, torikulhabib commented
bot, build com.github.gabutakut.gabutdm

2021-12-07 07:54 UTC, barthalion commented
/merge

2021-12-07 07:55 UTC, closed without merging