Depreciate com.kitware.F3D and rename com.kitware.F3D to com.f3d-app.F3D
flathub/flathub pull request #2680
Opened 2021-12-13 15:26 UTC by kevinsmia1939

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. [**Link:**](https://github.com/f3d-app/f3d/issues/124#issuecomment-990358228)
- [] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-12-13 15:52 UTC, hfiguiere commented
what is the rationale for renaming?

2021-12-13 15:53 UTC, hfiguiere requested changes

2021-12-13 15:53 UTC, hfiguiere commented on com.f3d-app.F3D.yaml
> +runtime-version: '20.08'
```suggestion
runtime-version: '21.08'
```

2021-12-13 15:53 UTC, hfiguiere commented on com.f3d-app.F3D.yaml
> +app-id: com.f3d-app.F3D
```suggestion
app-id: com.f3d_app.F3D
```

It has to be with an underscore and not a `-`.

2021-12-13 17:08 UTC, kevinsmia1939 commented
> what is the rationale for renaming?
Dev suggest that ideally it should be rename.
https://github.com/f3d-app/f3d/issues/124#issuecomment-990358228

2021-12-13 17:20 UTC, hfiguiere commented
as I mentionned there, `f3d-app.com` doesn't resolve. So it break requirement of being a "domain" under upstream control.

2021-12-14 18:56 UTC, hfiguiere commented
The id should be `io.github.f3d_app.f3d`.

See https://github.com/f3d-app/f3d/issues/156

2021-12-17 09:19 UTC, kevinsmia1939 commented
i will close this one and

2021-12-17 09:19 UTC, closed without merging

2021-12-17 14:39 UTC, hfiguiere commented
you didn't need to close this.