Add Move Transition OBS plugin
flathub/flathub pull request #2697
Opened 2021-12-22 18:32 UTC by exeldro

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-12-22 18:35 UTC, hfiguiere requested changes

2021-12-22 18:35 UTC, hfiguiere commented on com.obsproject.Studio.Plugin.MoveTransition.yaml
> +sdk: org.kde.Sdk//5.15
```suggestion
sdk: org.kde.Sdk//5.15-21.08
```

OBS use 5.15-21.08

2021-12-22 18:35 UTC, hfiguiere commented on flathub.json
> +    "only-arches": ["x86_64", "i386"],
```suggestion
    "only-arches": ["x86_64"],
```

2021-12-22 18:37 UTC, hfiguiere commented
@GeorgesStavracas this up your alley.

2021-12-27 13:06 UTC, GeorgesStavracas commented
Sorry, this fell through the cracks. I'll have a look tonight!

2021-12-27 20:11 UTC, GeorgesStavracas requested changes
Two small comments, LGTM other than that. I think it can land after these comments are addressed.

2021-12-27 20:11 UTC, GeorgesStavracas commented on com.obsproject.Studio.Plugin.MoveTransition.metainfo.xml
> +
Tiny nitpick: please remove this empty newline

2021-12-27 20:11 UTC, GeorgesStavracas commented on com.obsproject.Studio.Plugin.MoveTransition.yaml
> +        ${FLATPAK_ID}
I think this should be a single line command

2021-12-27 20:21 UTC, exeldro commented
Applied suggested changes

2021-12-27 20:22 UTC, GeorgesStavracas approved these changes
LGTM. Please squash all commits with the first one, then let's land this \o/

2021-12-28 08:21 UTC, barthalion commented
/merge @GeorgesStavracas

2021-12-28 08:22 UTC, closed without merging