Initial commit - submit application
flathub/flathub pull request #2701
Opened 2021-12-25 05:47 UTC by sigulete

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2021-12-25 05:54 UTC, hfiguiere requested changes
These change are required to even build.

2021-12-25 05:54 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +runtime-version: '5.15'
```suggestion
runtime-version: '5.15-21.08'
```

2021-12-25 05:54 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        path: rsync_3.2.3.orig.tar.gz #https://packages.ubuntu.com/source/impish/rsync
you need a URL here.

2021-12-25 05:54 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        path: ksshaskpass_5.22.5.orig.tar.xz #https://packages.ubuntu.com/source/impish/ksshaskpass
you need an actual URL here.

2021-12-25 05:54 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +      - -DCMAKE_BUILD_TYPE=Release
```suggestion
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

2021-12-25 05:54 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        path: syncbackup_2.0.tar.xz
you need an URL here.

2021-12-25 05:54 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +
```suggestion
```

2021-12-25 05:54 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +    strip: true
```suggestion
```

You don't need this.

2021-12-25 07:43 UTC, sigulete commented
Thanks. This is my first time packaging for flathub.
I have completed the changes. The only question is what is going to be the
final repository for my application, hence the url for the module
*syncbackup* may need to be modified.
I committed the changes, should I open a pull request again?


On Sat, 25 Dec 2021 at 16:55, Hubert Figuière ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> These change are required to even build.
> ------------------------------
>
> In com.darhon.syncbackup.yml
> <https://github.com/flathub/flathub/pull/2701#discussion_r775110723>:
>
> > @@ -0,0 +1,53 @@
>
> +app-id: com.darhon.syncbackup
>
> +runtime: org.kde.Platform
>
> +runtime-version: '5.15'
>
>
> ⬇️ Suggested change
>
> -runtime-version: '5.15'
>
> +runtime-version: '5.15-21.08'
>
>
> ------------------------------
>
> In com.darhon.syncbackup.yml
> <https://github.com/flathub/flathub/pull/2701#discussion_r775110763>:
>
> > +finish-args:
>
> +  - --socket=x11
>
> +  - --socket=wayland
>
> +  - --share=ipc
>
> +  - --device=dri
>
> +  - --share=network
>
> +  - --filesystem=host
>
> +modules:
>
> +  - name: rsync
>
> +    buildsystem: autotools
>
> +    config-opts:
>
> +      - --disable-zstd
>
> +      - --disable-xxhash
>
> +    sources:
>
> +      - type: archive
>
> +        path: rsync_3.2.3.orig.tar.gz #https://packages.ubuntu.com/source/impish/rsync
>
> you need a URL here.
> ------------------------------
>
> In com.darhon.syncbackup.yml
> <https://github.com/flathub/flathub/pull/2701#discussion_r775110770>:
>
> > +  - name: rsync
>
> +    buildsystem: autotools
>
> +    config-opts:
>
> +      - --disable-zstd
>
> +      - --disable-xxhash
>
> +    sources:
>
> +      - type: archive
>
> +        path: rsync_3.2.3.orig.tar.gz #https://packages.ubuntu.com/source/impish/rsync
>
> +    cleanup:
>
> +      - /share/man
>
> +
>
> +  - name: ksshaskpass
>
> +    buildsystem: cmake
>
> +    sources:
>
> +      - type: archive
>
> +        path: ksshaskpass_5.22.5.orig.tar.xz #https://packages.ubuntu.com/source/impish/ksshaskpass
>
> you need an actual URL here.
> ------------------------------
>
> In com.darhon.syncbackup.yml
> <https://github.com/flathub/flathub/pull/2701#discussion_r775110774>:
>
> > +        path: rsync_3.2.3.orig.tar.gz #https://packages.ubuntu.com/source/impish/rsync
>
> +    cleanup:
>
> +      - /share/man
>
> +
>
> +  - name: ksshaskpass
>
> +    buildsystem: cmake
>
> +    sources:
>
> +      - type: archive
>
> +        path: ksshaskpass_5.22.5.orig.tar.xz #https://packages.ubuntu.com/source/impish/ksshaskpass
>
> +    cleanup:
>
> +      - /share/man
>
> +
>
> +  - name: syncbackup
>
> +    buildsystem: cmake
>
> +    config-opts:
>
> +      - -DCMAKE_BUILD_TYPE=Release
>
>
> ⬇️ Suggested change
>
> -      - -DCMAKE_BUILD_TYPE=Release
>
> +      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
>
>
> ------------------------------
>
> In com.darhon.syncbackup.yml
> <https://github.com/flathub/flathub/pull/2701#discussion_r775110785>:
>
> > +
>
> +  - name: ksshaskpass
>
> +    buildsystem: cmake
>
> +    sources:
>
> +      - type: archive
>
> +        path: ksshaskpass_5.22.5.orig.tar.xz #https://packages.ubuntu.com/source/impish/ksshaskpass
>
> +    cleanup:
>
> +      - /share/man
>
> +
>
> +  - name: syncbackup
>
> +    buildsystem: cmake
>
> +    config-opts:
>
> +      - -DCMAKE_BUILD_TYPE=Release
>
> +    sources:
>
> +      - type: archive
>
> +        path: syncbackup_2.0.tar.xz
>
>
> you need an URL here.
> ------------------------------
>
> In com.darhon.syncbackup.yml
> <https://github.com/flathub/flathub/pull/2701#discussion_r775110811>:
>
> > +#  - name: syncbackup_sh
>
> +#    buildsystem: simple
>
> +#    build-commands:
>
> +#      - install -D syncbackup.sh $FLATPAK_DEST/bin/syncbackup.sh
>
> +#    sources:
>
> +#      - type: script
>
> +#        dest-filename: syncbackup.sh
>
> +#        commands:
>
> +#          - export SSH_ASKPASS=$FLATPAK_DEST/bin/ksshaskpass
>
> +#          - $FLATPAK_DEST/bin/syncbackup
>
> +
>
>
> ⬇️ Suggested change
>
> -#  - name: syncbackup_sh
>
> -#    buildsystem: simple
>
> -#    build-commands:
>
> -#      - install -D syncbackup.sh $FLATPAK_DEST/bin/syncbackup.sh
>
> -#    sources:
>
> -#      - type: script
>
> -#        dest-filename: syncbackup.sh
>
> -#        commands:
>
> -#          - export SSH_ASKPASS=$FLATPAK_DEST/bin/ksshaskpass
>
> -#          - $FLATPAK_DEST/bin/syncbackup
>
> -
>
>
> ------------------------------
>
> In com.darhon.syncbackup.yml
> <https://github.com/flathub/flathub/pull/2701#discussion_r775110834>:
>
> > +build-options:
>
> +    strip: true
>
>
> ⬇️ Suggested change
>
> -build-options:
>
> -    strip: true
>
>
> You don't need this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/flathub/flathub/pull/2701#pullrequestreview-840006724>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIL5E656XWUSLH4ROXMK7GDUSVMDRANCNFSM5KXPDVGA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2021-12-25 14:23 UTC, hfiguiere requested changes

2021-12-25 14:23 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        url: https://github.com/sigulete/flathub.git
This repository doesn't contain the source code.

Also this REQUIRE a specific commit.

2021-12-25 14:23 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        md5: 2d17696a462d4b1abc3f8b50811ba78c
md5 is deprecated. Please use sha256.

2021-12-25 14:23 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        md5: 209f8326f5137d8817a6276d9577a2f1
md5 is deprecated. Please use sha256.

2021-12-25 14:23 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        url: http://archive.ubuntu.com/ubuntu/pool/main/r/rsync/rsync_3.2.3.orig.tar.gz
why no using the official upstream?

2021-12-25 14:23 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        url: http://archive.ubuntu.com/ubuntu/pool/universe/k/ksshaskpass/ksshaskpass_5.22.5.orig.tar.xz
why not using the official upstream?

2021-12-25 14:25 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +        url: https://github.com/sigulete/flathub.git
Just to clarify. This shoud point to the code of the software you are packaging. Not the flathub package repository.

2022-01-01 16:39 UTC, hfiguiere commented
bot, build com.darhon.syncbackup

2022-01-01 16:47 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +          - syncbackup --ssh-askpass /app/bin/ksshaskpass
```suggestion
  - name: syncbackup
    buildsystem: cmake-ninja
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    post-install:
      - install -D syncbackup.sh /app/bin/syncbackup.sh
    sources:
      - type: git
        url: https://github.com/DarhonSoftware/syncBackup.git
        tag: v2.0.0
        commit: 0703b02ffb57a960d190bab89da647d94feccb83
      - type: script
        dest-filename: syncbackup.sh
        commands: 
          - syncbackup --ssh-askpass /app/bin/ksshaskpass
```

2022-01-01 16:47 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +  - --socket=x11
```suggestion
  - --socket=fallback-x11
```

2022-01-03 10:13 UTC, barthalion commented
bot, build com.darhon.syncbackup

2022-01-03 10:17 UTC, barthalion commented on com.darhon.syncbackup.yml
> +      - install -D syncbackup.sh /app/bin/syncbackup.sh
This is nested too much.

2022-01-03 16:14 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +      post-install:
```suggestion
    post-install:
```

(this is the indentation problem mentionned below

2022-01-03 16:15 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +  - --socket=x11
```suggestion
```

My suggestion was removing this and it wasn't.

2022-01-03 16:15 UTC, hfiguiere commented on com.darhon.syncbackup.yml
> +    buildsystem: cmake
```suggestion
    buildsystem: cmake-ninja
```

2022-01-04 13:26 UTC, hfiguiere commented
bot, build com.darhon.syncbackup

2022-01-05 02:25 UTC, hfiguiere commented
BTW you can also trigger build like this:


bot, build com.darhon.syncbackup

2022-01-06 23:27 UTC, DarhonSoftware commented
bot, build com.darhon.syncbackup

2022-01-07 21:07 UTC, barthalion commented
/merge

2022-01-07 21:08 UTC, closed without merging