add org.kde.kompare
flathub/flathub pull request #2765
Opened 2022-01-13 08:15 UTC by Amit0617

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-01-13 08:16 UTC, Amit0617 commented
bot, build org.kde.kompare

2022-01-13 10:46 UTC, Amit0617 commented
bot, build org.kde.kompare

2022-01-13 10:53 UTC, Amit0617 commented
bot, build org.kde.kompare

2022-01-13 16:24 UTC, travier requested changes

2022-01-13 16:24 UTC, travier commented on org.kde.kompare.json
> +            	{
whitespace at the end of the line

2022-01-13 16:25 UTC, travier commented
Can you link to upstream patch submission?

2022-01-13 16:30 UTC, Amit0617 commented
https://invent.kde.org/sdk/kompare/-/merge_requests/5

2022-01-14 10:45 UTC, nedrichards commented
bot, build org.kde.kompare

2022-01-15 21:51 UTC, nedrichards commented
This isn't working ideally on its own. On a Fedora 35 test system I get:

> kf.service.services: KMimeTypeTrader: MIME type "text/x-patch" not found
kf.service.services: KMimeTypeTrader: couldn't find service type "Kompare/ViewPart" 
Please ensure that the .desktop file for it is installed; then run kbuildsycoca5.
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
kf.notifications: Audio notification requested, but sound file from notifyrc file was not found, aborting audio notification


and then it closes.

2022-01-16 17:39 UTC, Amit0617 commented
If there are any suggestions i will happily push those changes.

2022-01-19 20:39 UTC, nedrichards commented
bot, build org.kde.kompare

2022-01-24 17:16 UTC, Amit0617 commented
@nedrichards does this have any problem?

2022-01-25 19:52 UTC, nedrichards commented
Yes. I literally can't run it https://github.com/flathub/flathub/pull/2765#issuecomment-1013759627

2022-01-26 13:44 UTC, travier commented
There is still a mix of tabs and spaces here. Look for a configuration in your editor to highlight them and fix them (spaces only).

2022-02-02 10:07 UTC, Amit0617 commented
bot, build org.kde.kompare

2022-02-02 21:16 UTC, travier commented
This is now using tabs only but we usually use spaces only.

2022-02-02 21:18 UTC, travier commented
Apart form that, works as expected for me.

2022-02-03 05:28 UTC, Amit0617 commented
> This is now using tabs only but we usually use spaces only.

Oops!

2022-02-04 22:12 UTC, travier commented
LGTM. This one should be good to merge. We can merge as beta if it does not work for non-KDE setups

2022-02-05 08:27 UTC, nedrichards commented
bot, build org.kde.kompare

2022-02-05 08:33 UTC, nedrichards commented
bot, build org.kde.kompare

2022-02-05 08:42 UTC, nedrichards commented
/merge:beta

2022-02-05 08:43 UTC, closed without merging