Add org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins
flathub/flathub pull request #2812
Opened 2022-01-30 15:45 UTC by Bleuzen

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

2022-01-30 15:48 UTC, Bleuzen commented
DO NOT MERGE!

This is very wip, still in testing stage.
The plan is to package all plugins from Chowdhury-DSP in one flatpak.
This would supersede the current https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.ChowTapeModel flatpak.

2022-01-30 15:49 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2022-01-30 15:53 UTC, hfiguiere commented
you should use the same approach as for the WhiteElephantAudio plugins, ie not a third party git with submodules.

2022-01-30 15:58 UTC, Bleuzen commented
> you should use the same approach as for the WhiteElephantAudio plugins

While possible I try to make something easy to package, so that also other packagers besides on flathub have an easier time. This is simplified by having only one repo to build.

> ie not a third party git with submodules.

If this works well this could in some form land in the official ChowDSP releases repo. Third party is only for testing now, will be replaced later.

2022-01-30 16:01 UTC, hfiguiere commented
the thing is that your way of doing it limit who can update the versions of the plugins to you. And require extra steps.

2022-01-30 16:05 UTC, Bleuzen commented
> the thing is that your way of doing it limit who can update the versions of the plugins to you. And require extra steps.

This is only temporary for testing. Plan is to merge it upstream and the official plugin developer will make new tags and keep it updated.

2022-01-30 16:07 UTC, hfiguiere commented
but to be fair, "all in one" packages like that might be the wrong approach.

2022-01-30 16:08 UTC, hfiguiere commented
(unless this is upstream choice)

2022-01-30 16:18 UTC, Bleuzen commented
> but to be fair, "all in one" packages like that might be the wrong approach.

I would like to see those plugins packaged in more repos. Lowering the bar and having something simple seems a good start so more packagers can pick it up without too much of an effort. 
Of course this can be discussed if you still think there is something wrong with it.



> (unless this is upstream choice)

Will see, we are still testing how this could work:

https://github.com/Chowdhury-DSP/releases/issues/1

2022-01-30 16:56 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2022-01-30 16:57 UTC, Bleuzen commented
build should be fixed now, however the first one is still running for some reason despite that it ran into an error. Not sure why it doesn't end. Is there a way to stop frozen builds? @hfiguiere

2022-02-10 21:47 UTC, Bleuzen commented
@hfiguiere  any idea why the cloning fails now? A `git clone --recursive https://github.com/Chowdhury-DSP/releases.git` works here, but not in flatpak.

2022-02-16 18:18 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2022-02-16 18:46 UTC, Bleuzen commented
bot, stop

2022-02-16 18:47 UTC, Bleuzen commented
ehhw :/

2022-02-16 18:47 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2022-02-23 15:34 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2022-02-23 15:37 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2022-02-24 21:41 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2022-02-28 15:40 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2022-02-28 21:02 UTC, Bleuzen commented
@hfiguiere @barthalion hm it fails at cloning the RTNeural submodule, but only on flathub. Cloning and build works just fine here locally. Any idea?

2022-03-02 01:57 UTC, hfiguiere commented
no idea why this is failing. It looks like the git clone is too shallow.

2023-01-14 16:22 UTC, hfiguiere commented
I think I changed my mind on all-in-one packages. I submitted GuitarML that way. This will limit the number of plugin packages.

So anything I can help with to get this in?

I'll submit BYOD (not in here) separately though because I have a version with the standalone version. It make sense to have it.

2023-01-14 16:28 UTC, hfiguiere commented
Albeit it might make more sense to build the plugins one by one instead of using upstream meta project.

2023-01-14 19:04 UTC, hfiguiere commented
See https://github.com/Bleuzen/flathub/pull/1

2023-02-05 17:10 UTC, hfiguiere commented
Any chance you can merge the PR so we can move forward with this submission?

2023-02-05 21:27 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2023-02-05 21:54 UTC, hfiguiere commented
uh, it did build locally :-/ Need figure that part out.

2023-02-19 17:45 UTC, hfiguiere commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2023-02-19 17:51 UTC, hfiguiere commented
this repo that fail is also the same that's used for https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.ChowTapeModel/

2023-02-19 17:54 UTC, hfiguiere commented
@barthalion any idea of why it fails to fetch a submodule of a submodule. Build works locally and the same repo (and commit) works in a different package.

(also I'm not the OP so I can't really try things like disable-shallow)

2023-02-19 18:04 UTC, hfiguiere commented
BYOD is submitted separately for the standalone app https://github.com/flathub/flathub/pull/3918

2023-02-19 21:26 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2023-02-19 21:34 UTC, hfiguiere commented
looks like this is working better.

2023-03-07 20:40 UTC, hfiguiere commented
BYOD is available on flathub as both standalone and plugin built from https://github.com/flathub/com.chowdsp.BYOD

2023-04-11 13:14 UTC, hfiguiere commented
shall we move this out of draft?

2023-04-15 14:09 UTC, hfiguiere requested changes

2023-04-16 11:57 UTC, Bleuzen commented
bot, build org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins

2023-04-16 11:57 UTC, Bleuzen commented on org.freedesktop.LinuxAudio.Plugins.ChowDSP-Plugins.json
> +                "strip ${FLATPAK_DEST}/vst3/ChowKick.vst3/Contents/*-linux/*.so",
thanks :)

2023-05-08 00:33 UTC, hfiguiere commented
@barthalion  it's far in the backlog, but this should be ready now,

2023-05-08 11:04 UTC, barthalion commented
/merge:22.08

2023-05-08 11:05 UTC, closed without merging