Add com.obsproject.Studio.Plugin.TransitionTable
flathub/flathub pull request #2824
Opened 2022-02-03 17:45 UTC by exeldro

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-02-03 21:00 UTC, hfiguiere commented
bot, build com.obsproject.Studio.Plugin.TransitionTable

2022-02-10 13:47 UTC, GeorgesStavracas requested changes
Sorry it took me so long to review this. Had one comment, it's fairly minor, but I wish we can work out a better summary before including this plugin.

2022-02-10 13:47 UTC, GeorgesStavracas commented on com.obsproject.Studio.Plugin.TransitionTable.metainfo.xml
> +  <summary>Plugin for OBS Studio to add a Transition Table to the tools menu</summary>
Hm, how about something like `Fine-tune your transitions with a transition table`?

(I've been advocating for removing things like "Plugin for OBS Studio that ..." from summaries. Instead, I'm suggesting summaries that briefly explain what that plugin enables people to do.)

2022-02-16 07:54 UTC, barthalion commented
/merge @GeorgesStavracas

2022-02-16 07:55 UTC, closed without merging