Add it.mijorus.smile
flathub/flathub pull request #2827
Opened 2022-02-05 16:00 UTC by mijorus

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-02-05 16:11 UTC, hfiguiere requested changes

2022-02-05 16:11 UTC, hfiguiere commented on it.mijorus.smile.json
> +        "--socket=x11",
```suggestion
        "--socket=fallback-x11",
```

2022-02-05 16:11 UTC, hfiguiere commented on it.mijorus.smile.json
> +                    "path" : "./"
you need to get the source here from upstream.

2022-02-05 16:11 UTC, hfiguiere commented on it.mijorus.smile.json
> +    }
```suggestion
    ]
```

2022-02-05 16:11 UTC, hfiguiere commented on it.mijorus.smile.json
> +        "python3-requirements.json",
this is missing

2022-02-05 16:30 UTC, mijorus commented
Hi, sorry this is my first time uploading here. I have fixed the reported errros.

2022-02-05 16:39 UTC, barthalion commented
bot, build it.mijorus.smile

2022-02-05 16:43 UTC, hfiguiere commented
AppData fail to validate

```
builddir/files/share/appdata/it.mijorus.smile.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• style-invalid         : Not enough <screenshot> tags, minimum is 1
• tag-missing           : <release> required
• tag-missing           : <name> is not present
• tag-missing           : <summary> is not present
• tag-missing           : <url> is not present
Validation of files failed
```

2022-02-05 17:09 UTC, mijorus commented
bot, build it.mijorus.smile

2022-02-05 17:16 UTC, mijorus commented
> Started [test build 77313](https://flathub.org/builds/#/builders/32/builds/77313)

Did it crash?

2022-02-06 12:09 UTC, mijorus commented
bot, build it.mijorus.smile

2022-02-06 15:16 UTC, mijorus commented
bot, build it.mijorus.smile

2022-02-06 20:10 UTC, mijorus commented
I tested it in various VMs, everything seems to work fine

2022-02-06 21:29 UTC, barthalion commented
It doesn't seem to copy emojis for me on Fedora 35 Silverblue.

2022-02-06 22:31 UTC, mijorus commented
> It doesn't seem to copy emojis for me on Fedora 35 Silverblue.

It had more to do with my code than with Fedora apparently 🤣😂😅

2022-02-06 22:32 UTC, mijorus commented
bot, build it.mijorus.smile

2022-02-06 22:37 UTC, mijorus commented
> Build [77519 successful](https://flathub.org/builds/#/builders/32/builds/77519) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/75387/it.mijorus.smile.flatpakref
> ```

This new build seems to work just fine in my Fedora 35 VM

2022-02-08 06:24 UTC, barthalion commented
/merge

2022-02-08 06:25 UTC, closed without merging