Add PDF Stitcher application
flathub/flathub pull request #2837
Opened 2022-02-07 22:38 UTC by nbenitez

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/cfcurtis/pdfstitcher/issues/27#issuecomment-1032000524
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* Upstream is only providing binaries for Windows and Mac

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-02-07 23:00 UTC, hfiguiere commented
bot, build com.github.cfcurtis.pdfstitcher

2022-02-07 23:37 UTC, hfiguiere commented
appdata fail to validate 
```
builddir/files/share/appdata/com.github.cfcurtis.pdfstitcher.appdata.xml: FAILED:
• style-invalid         : Content before <ul> is too short [8], at least 20 characters required
Validation of files failed
```

2022-02-07 23:37 UTC, hfiguiere requested changes

2022-02-07 23:53 UTC, nbenitez commented on com.github.cfcurtis.pdfstitcher.json
> +                    "url": "https://files.pythonhosted.org/packages/b0/43/3e286c93b9fa20e233d53532cc419b5aad8a468d91065dbef4c846058834/Pillow-9.0.0.tar.gz",
Removed.

2022-02-07 23:53 UTC, nbenitez commented
bot, build com.github.cfcurtis.pdfstitcher

2022-02-08 07:20 UTC, barthalion commented
/merge @cfcurtis

2022-02-08 07:21 UTC, closed without merging