Autodesk Eagle
flathub/flathub pull request #2850
Opened 2022-02-16 05:42 UTC by benwaffle

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-02-16 05:45 UTC, benwaffle commented
bot, build com.autodesk.Eagle

2022-02-16 05:48 UTC, hfiguiere requested changes
you still need to add the flathub.json to limit architectures

2022-02-16 05:48 UTC, hfiguiere commented on com.autodesk.Eagle.yml
> +      - install -Dm644 mime.xml /app/share/mime/packages/eagle.xml
```suggestion
      - install -Dm644 mime.xml /app/share/mime/packages/${FLATPAK_ID}.xml
```

2022-02-16 05:48 UTC, hfiguiere commented on mime.xml
> +		<icon name="eagle"/>
this icon won't be found. At least use the same as for the application.

2022-02-16 05:48 UTC, hfiguiere commented on com.autodesk.Eagle.appdata.xml
> +</component>
it's missing the `project_license`

2022-02-16 05:49 UTC, hfiguiere commented
the appdata file is never installed.

2022-02-16 05:49 UTC, hfiguiere commented on com.autodesk.Eagle.yml
> +  - --filesystem=home
that's a lot of permissions.

2022-02-16 05:50 UTC, hfiguiere commented on com.autodesk.Eagle.yml
> +  - --socket=x11
you also need `--share=ipc`

2022-02-18 05:22 UTC, benwaffle commented
bot, build com.autodesk.Eagle

2022-02-18 05:44 UTC, hfiguiere commented on com.autodesk.Eagle.yml
> +          - install -Dm644 doc/eagle.1 export/share/man/man1/eagle.1
```suggestion
          - install -Dm644 doc/eagle.1 export/share/man/man1/eagle.1
```

Nobody will see the manpage.

2022-02-18 05:47 UTC, hfiguiere commented on com.autodesk.Eagle.desktop
> +TryExec=/app/eagle
```suggestion
```

2022-02-21 01:55 UTC, benwaffle commented
bot, build com.autodesk.Eagle

2022-02-21 02:00 UTC, benwaffle commented
bot, build com.autodesk.Eagle

2022-02-24 00:29 UTC, tinywrkb commented
The bundled ngspice is quite outdated. IIRC Eagle allows changing the location of the simulator in its settings.  
Please consider packaging an updated ngspice version, so the user will have the option to try a more recent simulator.  
I have a ngspice module packaged [here](https://github.com/tinywrkb/flatpaks/blob/master/shared-modules/ngspice/ngspice.json), though I'm not sure if only the simulator is enabled or also other tools.

2022-02-24 04:08 UTC, benwaffle commented
I think we should try to do that after this is merged.

2022-02-28 18:16 UTC, barthalion commented
bot, build com.autodesk.Eagle

2022-02-28 18:45 UTC, barthalion commented on com.autodesk.Eagle.appdata.xml
> +  <description>
The description should contain a disclaimer that it's not an officially maintained app (see commercial Jetbrains applications) and mention it requires an account to work.

2023-03-16 00:59 UTC, closed without merging