Add KBreakOut to Flathub
flathub/flathub pull request #2853
Opened 2022-02-17 01:59 UTC by cho2

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of [permissions](https://invent.kde.org/packaging/flatpak-kde-applications/-/blob/master/org.kde.kbreakout.json#L10). 
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. 
  - I am a member of [KDE Team on Flathub](https://github.com/orgs/flathub/teams/kde/members).
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
  - KDE project owns the domain
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. 
  - tbd

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-02-17 02:00 UTC, cho2 commented
bot, build org.kde.kbreakout

2022-02-17 02:03 UTC, hfiguiere requested changes

2022-02-17 02:03 UTC, hfiguiere commented on org.kde.kbreakout.json
> +        "--filesystem=host"
for a game?

also don't you need dri?

2022-02-17 02:03 UTC, hfiguiere commented on org.kde.kbreakout.json
> +        "--socket=x11",
```suggestion
        "--socket=fallback-x11",
```

if it supports wayland

2022-02-17 02:22 UTC, cho2 commented
bot, build org.kde.kbreakout

2022-02-17 02:25 UTC, hfiguiere requested changes

2022-02-17 02:25 UTC, hfiguiere commented on org.kde.kbreakout.json
> +        "--socket=-fallbackx11",
```suggestion
        "--socket=-fallback-x11",
```

2022-02-17 02:25 UTC, cho2 commented on org.kde.kbreakout.json
> +        "--socket=-fallbackx11",
oops, typo

2022-02-17 02:39 UTC, cho2 commented
```
flatpak run org.kde.kbreakout
Qt: Session management error: Could not open network socket
libGL error: MESA-LOADER: failed to retrieve device information
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing draw buffer.
QOpenGLFramebufferObject: Framebuffer incomplete, missing draw buffer.
QOpenGLFramebufferObject: Framebuffer incomplete, missing draw buffer.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
intel_do_flush_locked failed: error Input/Output
```

2022-02-17 02:41 UTC, cho2 commented
bot, build org.kde.kbreakout

2022-02-17 03:26 UTC, cho2 commented
cc @flathub/kde

2022-02-17 13:37 UTC, albert-astals-cid-kdab commented
Looks reasonable

2022-02-17 13:38 UTC, tsdgeos commented
Looks reasonable

2022-02-17 13:43 UTC, travier commented
Minor comment. LGTM

2022-02-18 00:51 UTC, cho2 commented
bot, build org.kde.kbreakout

2022-02-18 00:58 UTC, cho2 commented
cc @barthalion @nedrichards

2022-02-20 15:54 UTC, nedrichards commented
/merge

2022-02-20 15:55 UTC, closed without merging