Add com.github.torikulhabib.niki.yml
flathub/flathub pull request #2856
Opened 2022-02-18 09:40 UTC by torikulhabib

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. [**Link:**](https://github.com/torikulhabib/niki)
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-02-18 12:29 UTC, torikulhabib commented
bot, build com.github.torikulhabib.niki

2022-02-18 13:35 UTC, hfiguiere requested changes

2022-02-18 13:35 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +  - '--socket=session-bus'
You need to figure what dbus name are need. Addind the `session-bus` is usually not an option.

2022-02-18 13:35 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +  - '--socket=x11'
```suggestion
```

2022-02-18 13:35 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +  - name: libcanberra
please use the manifest `shared-modules` as it contain important patches.

2022-02-18 13:35 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +    buildsystem: cmake
```suggestion
    buildsystem: cmake-ninja
```

2022-02-19 03:00 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +  - name: libcanberra
I was talking about libcanberra.

2022-02-19 03:27 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +  - name: libcanberra
still not what I was saying.

2022-02-22 04:25 UTC, hfiguiere commented
bot, build com.github.torikulhabib.niki

2022-02-22 09:23 UTC, nedrichards commented on com.github.torikulhabib.niki.yml
> +  - name: libcanberra-0.30
this is in the shared-modules https://github.com/flathub/shared-modules/ you should pull it in from there please.

2022-02-22 09:26 UTC, nedrichards commented
While browsing I get a fair few

> Error: Your GStreamer installation is missing a plug-in.

issues - you may need to bundle a wider set of plugins.

2022-02-22 09:53 UTC, nedrichards commented
For more clarity on what I mean about codecs see the kind of setup that Totem has to be gstreamer based and support 'everything' https://github.com/flathub/org.gnome.Totem.Devel/blob/beta/org.gnome.Totem.json

2022-02-23 03:56 UTC, torikulhabib commented
bot, build com.github.torikulhabib.niki

2022-02-23 03:58 UTC, hfiguiere requested changes

2022-02-23 03:58 UTC, hfiguiere commented on .github/pull_request_template.md
> +### Please confirm your submission meets all the criteria
this shouldn't be in there.

2022-02-23 03:58 UTC, hfiguiere commented on .github/workflows/stale.yml
> +name: "Close stale PR"
nor the workflow.

2022-02-23 03:58 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +  - '--socket=x11'
```suggestion
  - '--socket=x11'
```

2022-02-23 03:58 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +    buildsystem: cmake
```suggestion
    buildsystem: cmake-ninja
```

2022-02-23 04:00 UTC, hfiguiere requested changes

2022-02-23 04:00 UTC, hfiguiere commented on com.github.torikulhabib.niki.yml
> +  - 'codecs/pipewire.json'
these manifests are missing from the repository too.

2022-02-24 22:10 UTC, nedrichards commented
bot, build com.github.torikulhabib.niki

2022-02-24 22:12 UTC, hfiguiere commented
build fail because of what I mentionned in my review comments.

2022-02-25 21:07 UTC, nedrichards commented
Yup, I know - sometimes a failure makes it clearer that those comments are there for a reason!

2023-03-23 00:53 UTC, closed without merging