Add manifest for org.kde.krdc
flathub/flathub pull request #2859
Opened 2022-02-19 06:20 UTC by flyingcakes85

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-02-19 06:21 UTC, flyingcakes85 commented
bot, build org.kde.krdc

2022-02-19 06:22 UTC, flyingcakes85 commented
@travier 

I have tested VNC to work :+1: Couldn't get RDP to work, which is _probably_ because of my inexperience with the Windows environment.

Also, should we need pulseaudio sandbox permission here? I don't get any error messages in terminal when using VNC, but I believe RDP also carries audio.

2022-02-19 15:32 UTC, flyingcakes85 commented
bot, build org.kde.krdc

2022-02-19 15:44 UTC, hfiguiere requested changes

2022-02-19 15:44 UTC, hfiguiere commented on org.kde.krdc.json
> +        "--socket=x11",
```suggestion
        "--socket=fallback-x11",
```

2022-02-19 15:44 UTC, hfiguiere commented on org.kde.krdc.json
> +            "name": "libusb",
you should get it from shared-modules.

2022-02-19 15:44 UTC, hfiguiere commented on org.kde.krdc.json
> +            "name": "icon",
this should be part of the main module (`post-install` section)

2022-02-19 15:56 UTC, flyingcakes85 commented on org.kde.krdc.json
> +            "name": "libusb",
Thanks, updated :+1:

2022-02-19 15:56 UTC, flyingcakes85 commented
bot, build org.kde.krdc

2022-02-19 17:19 UTC, travier commented
CC @flathub/kde

2022-02-19 17:19 UTC, travier commented
Pulseaudio should be fine

2022-02-19 17:20 UTC, travier commented
Not yet tested but LGTM

2022-02-20 10:37 UTC, flyingcakes85 commented
bot, build org.kde.krdc

2022-02-20 11:01 UTC, flyingcakes85 commented
Added pulseaudio permission.

2022-02-20 15:58 UTC, nedrichards commented
/merge

2022-02-20 15:59 UTC, closed without merging