Add manifest for KDE Kile
flathub/flathub pull request #2873
Opened 2022-02-24 20:48 UTC by Pointedstick

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions.
  - `--device=dri` is for direct rendering access on Wayland
  - `--filesystem=home` is to make the embedded terminal not be useless
  - `--env=PATH=/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/usr/bin/` is to make Tex stuff work
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. 
  - https://invent.kde.org/ngraham
  - https://invent.kde.org/office/kile/-/commits/master?author=Nate%20Graham
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned.

---

This app includes functionality from KDE's Konsole and Okular apps, so the packaging copies Okular's pre-existing FlatHub packaging to bundle dependencies not already in a runtime. cc @tsdgeos

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-02-24 21:30 UTC, tsdgeos commented
bot, build org.kde.kile

2022-02-24 21:35 UTC, hfiguiere requested changes

2022-02-24 22:41 UTC, Pointedstick commented
Thanks for the suggestions! I will look into those shortly.

2022-02-24 22:43 UTC, Pointedstick commented on org.kde.kile.json
> +        "--socket=session-bus",
This may not be needed after all; I will see if I can remove it.

2022-02-25 02:04 UTC, hfiguiere commented
AppStream file doesn't validate:

```
builddir/files/share/appdata/org.kde.kile.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• tag-missing           : <release> required
Validation of files failed
```

2022-02-25 15:24 UTC, Pointedstick commented
Fixed that upstream with https://invent.kde.org/office/kile/-/commit/8a06742bdf65c169c9a015cba21b78f2a1fbb508, and added a patch to the packaging for now until we can update to the next version.

2022-02-25 15:35 UTC, hfiguiere commented
bot, build org.kde.kile

2022-02-25 17:00 UTC, hfiguiere commented
```
builddir/files/share/appdata/org.kde.kile.appdata.xml: FAILED:
• tag-missing           : <release> required
Validation of files failed
```

2022-02-25 17:46 UTC, Pointedstick commented
bot, build org.kde.kile

2022-02-25 21:06 UTC, nedrichards commented
/merge

2022-02-25 21:07 UTC, closed without merging