Add Huely
flathub/flathub pull request #2882
Opened 2022-03-03 01:31 UTC by benpocalypse

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-03-03 01:36 UTC, benpocalypse commented
bot, build com.github.benpocalypse.Huely

2022-03-03 02:13 UTC, hfiguiere requested changes

2022-03-03 02:13 UTC, hfiguiere commented on com.github.benpocalypse.Huely.yml
> +sdk: io.elementary.Sdk
This runtime isn't available on Flathub. So it won't build.

2022-03-03 02:13 UTC, hfiguiere commented on com.github.benpocalypse.Huely.yml
> +      - type: dir
this will not work either since it can't find the sources. It should be a git repository commit or a tarball (prefered)

2022-03-03 11:51 UTC, benpocalypse commented
This is my first time publishing an app, so my apologies for the amateur mistakes. I'm looking at some previous pull requests that were in similar shape, so hopefully I can have this straightened out later today. 
Thanks for the quick review and comments.

2022-03-04 14:46 UTC, benpocalypse commented
bot, build com.github.benpocalypse.Huely

2022-03-04 14:57 UTC, hfiguiere requested changes

2022-03-04 14:57 UTC, hfiguiere commented on com.github.benpocalypse.Huely.yml
> +base-version: juno-20.08
```suggestion
base-version: juno-21.08
```

This is the right version for gnome 41

2022-03-04 15:50 UTC, nedrichards commented
bot, build com.github.benpocalypse.Huely

2022-03-04 15:52 UTC, nedrichards commented
> This is my first time publishing an app, so my apologies for the amateur mistakes. I'm looking at some previous pull requests that were in similar shape, so hopefully I can have this straightened out later today. Thanks for the quick review and comments.

Don't worry about it, we're here to serve you in helping get your app out to as many people as possible as well. Thanks for sharing the app and looking forward to using it soon.

2022-03-04 16:19 UTC, nedrichards commented
I don't have a compatible light so I can only do the most basic testing. @benpocalypse can you confirm that the build works with your environment?

2022-03-05 21:02 UTC, nedrichards commented
/merge

2022-03-05 21:03 UTC, closed without merging

2022-03-06 01:03 UTC, benpocalypse commented
Thanks for the quick review, and thanks for letting me put my app on Flathub!