added new app submission
flathub/flathub pull request #2962
Opened 2022-03-29 07:56 UTC by vega-d

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

The app has dedicated access to `~/Nextcloud/Notes` to allow for desktop nextcloud notes integration.

2022-03-29 08:57 UTC, JakobDev commented
You should use --filesystem=xdg-documents instead of --filesystem=~/Documents. The name of the Documents folder is translated, so this will not work on other languages than English.

You should also add the App ID to your PR title.

2022-03-29 09:06 UTC, vega-d commented
> You should use --filesystem=xdg-documents instead of --filesystem=~/Documents. The name of the Documents folder is translated, so this will not work on other languages than English.

Thank you for noticing that, I hardcoded it for testing and forgot to change back



> You should also add the App ID to your PR title.

I didn't even realize it just took my commit message as PR name, oops

2022-03-29 15:42 UTC, hfiguiere requested changes

2022-03-29 16:21 UTC, vega-d commented on io.github.vegad.vnotes.yml
> +        url: https://github.com/vega-d/vnotes
Do I need to include a specific commit there? My master branch gets new changes merged only when they are release-ready anyways

2022-03-29 16:22 UTC, hfiguiere commented on io.github.vegad.vnotes.yml
> +        url: https://github.com/vega-d/vnotes
> you need a commit here.

2022-03-29 16:23 UTC, hfiguiere commented on io.github.vegad.vnotes.yml
> +        url: https://github.com/vega-d/vnotes
the build must be reproducible, which mean that rebuilding from the same manifest should always lead to the same result.

2022-03-29 16:25 UTC, hfiguiere reviewed
Build will fail as the appdata file is lacking `releases` and `content_rating`

2022-03-29 16:25 UTC, hfiguiere commented on io.github.vegad.vnotes.yml
> +        url: https://github.com/vega-d/vnotes
this is exactly what I said.

2022-03-29 16:26 UTC, vega-d commented on io.github.vegad.vnotes.yml
> +        url: https://github.com/vega-d/vnotes
I apologize for the confusion, I sent my previous message before yours loaded in.

2022-03-29 18:23 UTC, hfiguiere commented
bot, build io.github.vegad.vnotes

2022-03-29 19:33 UTC, vega-d commented
oh uh looks like I missed a tag in appstream, hold on

2022-03-29 19:44 UTC, vega-d commented
wait where am I supposed to put that `<url>`

2022-03-29 19:56 UTC, vega-d commented
Found it, `flatpak run --env=G_DEBUG=fatal-criticals org.freedesktop.appstream-glib validate builddir/*/share/appdata/io.github.vegad.vnotes.appdata.xml` passes with OK output

2022-03-30 08:54 UTC, barthalion commented
bot, build io.github.vegad.vnotes

2022-03-30 21:14 UTC, vega-d commented
the test build is working fine, except the desktop file is borked or something. If has a `--branch=master` argument but the app is in `test` branch so launching the test build from the gui doesn't work. Is that normal? If I drop the `--branch` argument from the desktop file it's working just fine

2022-03-31 07:04 UTC, barthalion commented
It works fine for me. It's probably because you had a local build installed.

/merge

2022-03-31 07:05 UTC, closed without merging