Add Flatpak for wavbreaker
flathub/flathub pull request #2979
Opened 2022-04-04 17:39 UTC by thp

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions: Wayland + X11 for GUI, PulseAudio for libao output, filesystem home for file read/write access to audio files
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains http://wavbreaker.sourceforge.net
- [x] Any additional patches or files have been submitted to the upstream projects concerned: Yes, the packaging is based on [what we have in upstream](https://github.com/thp/wavbreaker/blob/master/scripts/flatpak/net.sourceforge.wavbreaker.json) 

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-04 18:27 UTC, hfiguiere requested changes
I also see that the meson build want mpg123 but it's not listed in the manifest.

2022-04-04 18:27 UTC, hfiguiere commented on net.sourceforge.wavbreaker.json
> +    "runtime-version": "20.08",
```suggestion
    "runtime-version": "21.08",
```

2022-04-04 18:27 UTC, hfiguiere commented on net.sourceforge.wavbreaker.json
> +                    "url": "https://github.com/xiph/libao.git"
you need a specific commit / tag

2022-04-04 18:27 UTC, hfiguiere commented on net.sourceforge.wavbreaker.json
> +    "finish-args": [
finish-args is usually located above `modules` by convention.

2022-04-04 18:27 UTC, hfiguiere commented
bot, build net.sourceforge.wavbreaker

2022-04-04 18:28 UTC, hfiguiere commented
also it's missing an appstream file. 

(this will cause the build to fail)

2022-04-04 20:15 UTC, thp commented
> I also see that the meson build want mpg123 but it's not listed in the manifest.

As far as I understand it, `mpg123` is part of the freedesktop SDK, and can be re-used:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/mpg123.bst

2022-04-04 20:49 UTC, thp commented
> also it's missing an appstream file.

New upstream version 0.15 now installs an appstream file (https://github.com/thp/wavbreaker/commit/d169e81de3c1c8b78461ac927b0e87ee5ee73d9a).

2022-04-07 00:13 UTC, hfiguiere commented
bot, build net.sourceforge.wavbreaker

2022-04-07 06:50 UTC, barthalion commented
(On unrelated note @thp, I have used urlwatch for many years as Arch developer to monitor new upstream releases. Thanks for developing it!)

/merge

2022-04-07 06:51 UTC, closed without merging