add com.pengaru.glimmer.json
flathub/flathub pull request #2982
Opened 2022-04-04 23:09 UTC by vcaputo

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-04 23:15 UTC, vcaputo commented
Am new to the flatpak/flathub way of things, using this fun little gtk3 eye-candy gadget I've been poking at in spare time as an excuse to explore all this new stuff.

@chergert provided this manifest after playing with very early glimmer awhile back but I only just now got things to where it seemed worth potentially subjecting to random people.  I must admit I haven't spent any further time scrutinizing the manifest's correctness or validity, lmk if it needs any changes as it might have bitrotted it's been so long since he first created the PR adding it on the glimmer repo.

2022-04-04 23:22 UTC, hfiguiere requested changes

2022-04-04 23:22 UTC, hfiguiere commented on com.pengaru.glimmer.json
> +    "runtime-version" : "3.38",
this runtime version has been EOL for quite some time.
```suggestion
    "runtime-version" : "42",
```

2022-04-04 23:22 UTC, hfiguiere commented on com.pengaru.glimmer.json
> +                    "url" : "https://git.pengaru.com/glimmer"
you need a tag or commit here.

2022-04-04 23:22 UTC, hfiguiere commented on com.pengaru.glimmer.json
> +            "builddir" : false,
```suggestion
```

2022-04-04 23:22 UTC, hfiguiere commented
bot, build com.pengaru.glimmer

2022-04-05 00:46 UTC, vcaputo commented
Looks like I need to enable "smart" http capabilities for my git repos served via https on pengaru.com, will comment and update the manifest to address the above suggestions when I get  around to this.

Thanks.

2022-04-05 08:51 UTC, hfiguiere commented
you can add `disable-shallow-clone: true` to the source entry

2022-04-05 09:41 UTC, vcaputo commented
No need, setup the git-http-backend and updated the redirect to point there instead of cgit.

I think this should succeed now (actually tested here with flatpak-builder, unlike before), thanks.

2022-04-07 06:26 UTC, barthalion commented
bot, build com.pengaru.glimmer

2022-04-07 07:08 UTC, barthalion commented
You need to install an appdata file. https://www.freedesktop.org/software/appstream/metainfocreator/ can be used to generate it, and `org.freedesktop.appstream-glib` from Flathub to validate it.

2022-04-08 09:29 UTC, nedrichards commented
And a desktop file if I read https://git.pengaru.com/cgit/glimmer/.git/tree/ correctly.

2022-04-09 05:30 UTC, vcaputo commented
Thanks guys, It'll probably take me a week+ to get around to addressing those items due to travel stuffs.

2023-04-24 00:54 UTC, closed without merging