Add manifest for Hypatia (com.github.HypatiaProject.hypatia)
flathub/flathub pull request #2983
Opened 2022-04-04 23:33 UTC by nathandyer

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-05 01:43 UTC, hfiguiere requested changes

2022-04-05 01:43 UTC, hfiguiere commented on com.github.HyptiaProject.hypatia.json
> +                    "url" : "https://github.com/HypatiaProject/hypatia.git"
you need a specific revision or tag.

2022-04-05 01:43 UTC, hfiguiere commented on com.github.HyptiaProject.hypatia.json
> +    }
```suggestion
    ]
```

2022-04-05 01:43 UTC, hfiguiere commented
bot, build com.github.HypatiaProject.hypatia

2022-04-05 01:49 UTC, hfiguiere commented
The manifest is not properly named. It has a typo. That's why the build is failing.

2022-04-05 08:44 UTC, hfiguiere commented
bot, build com.github.HypatiaProject.hypatia

2022-04-05 10:14 UTC, hfiguiere commented
appdata fail to validate

```
builddir/files/share/appdata/com.github.HypatiaProject.hypatia.appdata.xml: FAILED:
• tag-missing           : <url> is not present
Validation of files failed
```

2022-04-05 13:01 UTC, nathandyer commented
My apologies, I validated it with appstream-util before pushing the release, but apparently I was using the relaxed option. Ran again without the relaxed option, found the issue, and corrected it.

Should be good to try building again.

2022-04-05 17:19 UTC, hfiguiere commented
bot, build com.github.HypatiaProject.hypatia

2022-04-05 22:14 UTC, nathandyer commented
Tested the build, everything looks good to me!

2022-04-07 06:33 UTC, barthalion commented
/merge

2022-04-07 06:34 UTC, closed without merging