Add io.github.pwr_solaar.solaar
flathub/flathub pull request #2984
Opened 2022-04-05 10:11 UTC by hadess

Deps file generated with:
```
flatpak-pip-generator evdev\>=1.1.2 pyudev\>=0.13 PyYAML\>=3.12 python-xlib\>=0.27 psutil\>=5.4.3
flatpak-json2yaml.py python3-modules.json
```

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-05 10:16 UTC, hfiguiere requested changes

2022-04-05 10:16 UTC, hfiguiere commented on io.github.pwr_solaar.solaar.yaml
> +        url: https://github.com/pwr-Solaar/Solaar.git
you need an explicit revision here

2022-04-05 10:16 UTC, hfiguiere commented
bot, build io.github.pwr_solaar.solaar

2022-04-05 10:26 UTC, barthalion commented
Didn't it use to require udev rules on the host?

2022-04-05 12:24 UTC, hadess commented
> Didn't it use to require udev rules on the host?

https://github.com/systemd/systemd/pull/22971

2022-04-07 06:27 UTC, barthalion commented
bot, build io.github.pwr_solaar.solaar

2022-04-07 06:32 UTC, barthalion commented
```
builddir/files/share/appdata/io.github.pwr_solaar.solaar.appdata.xml: FAILED:
• tag-missing           : <release> required
```

2022-04-07 17:12 UTC, hadess commented
> builddir/files/share/appdata/io.github.pwr_solaar.solaar.appdata.xml: FAILED:
> • tag-missing           : <release> required

That was fixed in https://github.com/pwr-Solaar/Solaar/pull/1546 and picked up by a bump

2023-04-22 00:53 UTC, closed without merging