Add com.webalys.streamline
flathub/flathub pull request #2986
Opened 2022-04-05 14:07 UTC by andirsun

### Please confirm your submission meets all the criteria
Hi I am developer at https://github.com/webalys-hq and we want to publish our desktop app streamline icons. So our repo is private and we want to know how to publish the app. 
I follow the guide here https://github.com/flatpak/flatpak-builder-tools/tree/master/node and generate resources.json
We was able to generate a flatpak with eletron-builder. https://file.io/egiD0MHpbO2I
- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-05 14:35 UTC, hfiguiere requested changes
Also I don't see a desktop file or an appdata file and I'll assume they don't exist upstream because Electron.

2022-04-05 14:35 UTC, hfiguiere commented on com.webalys.streamline.yml
> +branch: stable
```suggestion
```

2022-04-05 14:35 UTC, hfiguiere commented on com.webalys.streamline.yml
> +runtime-version: '19.08'
```suggestion
runtime-version: '21.08'
```

19.08 has been EOL since last year (after 2 years)

2022-04-05 14:35 UTC, hfiguiere commented on com.webalys.streamline.yml
> +base-version: '19.08'
```suggestion
base-version: '21.08'
```

same

2022-04-05 14:52 UTC, andirsun commented on com.webalys.streamline.yml
> +        url: https://github.com/webalys-hq/streamline-web
Do you know any example or documentation in order to do that ?

2022-04-07 06:28 UTC, barthalion commented on com.webalys.streamline.yml
> +        url: https://github.com/webalys-hq/streamline-web
The usual approach for proprietary applications is to build a tarball locally or through some CI/CD, and then upload it to S3. Then the manifest simply repackages your binary distribution.

2023-04-22 00:53 UTC, closed without merging