Testing: Add fi.csc.Elmer
flathub/flathub pull request #2992
Opened 2022-04-06 21:18 UTC by kevinsmia1939

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:https://www.elmerfem.org/forum/viewtopic.php?t=7712**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
 **https://github.com/ElmerCSC/elmerfem/pull/323**
[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-06 21:20 UTC, kevinsmia1939 commented
bot, build

2022-04-06 21:25 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer.yaml

2022-04-06 21:26 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-04-06 21:39 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +runtime: org.kde.Sdk
```suggestion
runtime: org.kde.Platform
```

2022-04-06 21:39 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +base-version: 5.15-21.08
```suggestion
```

since you don't have a base app

2022-04-06 21:39 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - -DCMAKE_INSTALL_PREFIX=/app
```suggestion
```
It's implicit

2022-04-06 21:39 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - -DCMAKE_BUILD_TYPE:STRING=Release
```suggestion
      - -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
```

It's always nice to have the debug info

2022-04-06 21:39 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - -DCMAKE_INSTALL_PREFIX:PATH=/app
```suggestion
```

This is implicit

2022-04-06 21:39 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - install -Dm0644 ElmerGUI/Application/images/logo.png ${FLATPAK_DEST}/share/icons/hicolor/64x64/apps/${FLATPAK_ID}.png
this is too small of an icon

2022-04-07 17:27 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-04-08 13:14 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-04-08 18:02 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-04-14 13:39 UTC, kevinsmia1939 commented
I have not receive any feedback from anyone in the forum and github. From my test, it seems to work fine, so I think it is ready to publish. It might be worth to ping https://github.com/raback for their opinion and if they want to be the maintainer.

2022-11-15 12:00 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-15 21:26 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-15 21:40 UTC, hfiguiere requested changes

2022-11-16 18:42 UTC, hfiguiere requested changes

2022-11-16 18:42 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +    buildsystem: cmake
vtk works with cmake-ninja AFAIR

2022-11-16 18:42 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +        disable-submodules: true
is there a reason to disable submodules?

2022-11-16 18:42 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - install -Dm0644 ${FLATPAK_ID}.metainfo.xml ${FLATPAK_DEST}/share/metainfo/${FLATPAK_ID}.metainfo.xml
because `builddir: true` you probably need to prefix the source path with `../`

2022-11-16 18:42 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +    buildsystem: cmake
`cmake-ninja`?

2022-11-16 18:42 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +    buildsystem: cmake
`cmake-ninja` ?

2022-11-16 18:42 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - ln -s /app/lib/libMPI.so /app/lib/libMPI::MPI_C.so
you could just put this in the `post-install` of the module the build this dso.

2022-11-16 20:27 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-16 20:36 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-17 12:50 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-17 22:52 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-18 22:43 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-18 22:47 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-19 00:02 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-19 01:32 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2022-11-25 13:12 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2023-07-02 12:30 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +        branch: devel
never a branch

2024-02-26 17:08 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +runtime-version: 5.15-22.08
```suggestion
runtime-version: 5.15-23.08
```

2024-02-26 17:11 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +  - --socket=fallback-x11
I see tk is being build. If tk is actually used, then X11 needs to be available at all times.

2024-02-27 02:33 UTC, bbhtt commented on fi.csc.Elmer.metainfo.xml
> +            <image>https://raw.githubusercontent.com/ElmerCSC/elmerfem-manuals/main/latex-elmergui/images/elmergui.png</image>
Please make this from a tag or a commit

2024-02-27 02:33 UTC, bbhtt commented on flathub.json
Why x86_64 only?

2026-06-13 10:26 UTC, kevinsmia1939 commented
reopen

2026-06-13 13:42 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +          - sed 's/QWT_INSTALL_PREFIX\s*=\s*\/usr\/local\/qwt-$$QWT_VERSION/QWT_INSTALL_PREFIX=\/app/g'
these really should be a patch.

2026-06-13 13:42 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - /share/man
```suggestion
```

the are already in the global rule.

2026-06-13 13:44 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - ln -s /app/lib/libMPI.so /app/lib/libMPI::MPI_C.so
also I doubt this is the proper solution. It's probably CMake being CMake.

2026-06-13 13:45 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - -DCMAKE_INSTALL_LIBDIR=lib
```suggestion
```

2026-06-13 13:45 UTC, hfiguiere commented on fi.csc.Elmer.yaml
> +      - -DCMAKE_PREFIX_PATH=/app
```suggestion
```

2026-06-14 07:08 UTC, kevinsmia1939 commented on fi.csc.Elmer.yaml
> +  - --socket=fallback-x11
tk has been remove

2026-06-14 08:13 UTC, kevinsmia1939 commented on fi.csc.Elmer.yaml
> +      - -DCMAKE_PREFIX_PATH=/app
fixed

2026-06-14 08:13 UTC, kevinsmia1939 commented on fi.csc.Elmer.yaml
> +      - -DCMAKE_INSTALL_LIBDIR=lib
fixed

2026-06-14 08:13 UTC, kevinsmia1939 commented on fi.csc.Elmer.yaml
> +      - /share/man
fixed

2026-06-14 08:14 UTC, kevinsmia1939 commented on flathub.json
ARM has been enabled

2026-06-14 08:14 UTC, kevinsmia1939 commented on fi.csc.Elmer.yaml
> +runtime-version: 5.15-22.08
Update to 5.15-25.08

2026-06-14 08:15 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2026-06-14 08:32 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2026-06-14 13:40 UTC, hfiguiere commented
build fails because
```
2026-06-14T09:02:17.1325735Z -- ParMETIS 1.0.0 CMake 4.2.0 install prefix /app
2026-06-14T09:02:17.1359690Z '/usr/bin/git' '--version'
2026-06-14T09:02:17.1360198Z -- Found Git: /usr/bin/git (found version "2.52.0")
2026-06-14T09:02:17.1629153Z Submodule 'METIS' (https://github.com/scivision/METIS) registered for path 'METIS'
2026-06-14T09:02:17.1630215Z '/usr/bin/git' 'submodule' 'update' '--init' '--recursive' '--' '/run/build/parmetis/METIS'
2026-06-14T09:02:17.1650377Z Cloning into '/run/build/parmetis/METIS'...
2026-06-14T09:02:17.1743829Z fatal: unable to access 'https://github.com/scivision/METIS/': Could not resolve host: github.com
2026-06-14T09:02:17.1756014Z fatal: clone of 'https://github.com/scivision/METIS' into submodule path '/run/build/parmetis/METIS' failed
2026-06-14T09:02:17.1757026Z Failed to clone 'METIS'. Retry scheduled
2026-06-14T09:02:17.1781294Z Cloning into '/run/build/parmetis/METIS'...
2026-06-14T09:02:17.1871075Z fatal: unable to access 'https://github.com/scivision/METIS/': Could not resolve host: github.com
2026-06-14T09:02:17.1883584Z fatal: clone of 'https://github.com/scivision/METIS' into submodule path '/run/build/parmetis/METIS' failed
2026-06-14T09:02:17.1884558Z Failed to clone 'METIS' a second time, aborting
2026-06-14T09:02:17.1892497Z CMake Error at cmake/GitSubmodule.cmake:16 (execute_process):
2026-06-14T09:02:17.1893135Z   execute_process failed command indexes:
2026-06-14T09:02:17.1893477Z 
2026-06-14T09:02:17.1893838Z     1: "Child return code: 1"
2026-06-14T09:02:17.1894144Z 
2026-06-14T09:02:17.1894319Z Call Stack (most recent call first):
2026-06-14T09:02:17.1894794Z   CMakeLists.txt:19 (git_submodule)
2026-06-14T09:02:17.1895106Z 
2026-06-14T09:02:17.1895111Z 
2026-06-14T09:02:17.1895325Z -- Configuring incomplete, errors occurred!
2026-06-14T09:02:17.2008628Z Error: module parmetis: Child process exited with code 1
```

seems that it want to checkout stuff at build time

2026-06-14 21:00 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2026-06-14 23:17 UTC, kevinsmia1939 commented
Investigating
```
2026-06-14T22:01:42.7322133Z FAILED: [code=1] CMakeFiles/nglib.dir/libsrc/general/parthreads.cpp.o 
2026-06-14T22:01:42.7327684Z /run/ccache/bin/c++ -DHAVE_DLFCN_H -DOCCGEOMETRY -Dnglib_EXPORTS -I/run/build/netgen/_flatpak_build/netgen -I/run/build/netgen -I/run/build/netgen/include -I/run/build/netgen/libsrc -I/run/build/netgen/libsrc/include -isystem /app/include/opencascade -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -mbranch-protection=bti+pac-ret -O2 -g -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -march=native -MD -MT CMakeFiles/nglib.dir/libsrc/general/parthreads.cpp.o -MF CMakeFiles/nglib.dir/libsrc/general/parthreads.cpp.o.d -o CMakeFiles/nglib.dir/libsrc/general/parthreads.cpp.o -c /run/build/netgen/libsrc/general/parthreads.cpp
2026-06-14T22:01:42.7333262Z In file included from /run/build/netgen/libsrc/core/simd.hpp:34,
2026-06-14T22:01:42.7333966Z                  from /run/build/netgen/libsrc/core/ngcore.hpp:16,
2026-06-14T22:01:42.7334764Z                  from /run/build/netgen/libsrc/include/../general/../include/mydefs.hpp:14,
2026-06-14T22:01:42.7335636Z                  from /run/build/netgen/libsrc/include/../general/myadt.hpp:16,
2026-06-14T22:01:42.7336461Z                  from /run/build/netgen/libsrc/include/myadt.hpp:1,
2026-06-14T22:01:42.7337158Z                  from /run/build/netgen/libsrc/general/parthreads.cpp:9:
2026-06-14T22:01:42.7338538Z /run/build/netgen/libsrc/core/simd_arm64.hpp: In function ‘ngcore::SIMD<ngcore::mask64, 2> ngcore::operator==(SIMD<long int, 2>, SIMD<long int, 2>)’:
2026-06-14T22:01:42.7340707Z /run/build/netgen/libsrc/core/simd_arm64.hpp:161:21: note: use ‘-flax-vector-conversions’ to permit conversions between vectors with differing element types or numbers of subparts
2026-06-14T22:01:42.7342103Z   161 |     return vceqq_u64(a.Data(), b.Data());
2026-06-14T22:01:42.7342621Z       |            ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
2026-06-14T22:01:42.7343453Z /run/build/netgen/libsrc/core/simd_arm64.hpp:161:28: error: cannot convert ‘__Int64x2_t’ to ‘uint64x2_t’
2026-06-14T22:01:42.7344326Z   161 |     return vceqq_u64(a.Data(), b.Data());
2026-06-14T22:01:42.7344829Z       |                      ~~~~~~^~
2026-06-14T22:01:42.7345259Z       |                            |
2026-06-14T22:01:42.7345702Z       |                            __Int64x2_t
2026-06-14T22:01:42.7346334Z In file included from /run/build/netgen/libsrc/core/simd_arm64.hpp:1:
2026-06-14T22:01:42.7347787Z /usr/lib/gcc/aarch64-unknown-linux-gnu/15.2.0/include/arm_neon.h:7646:23: note: initializing argument 1 of ‘uint64x2_t vceqq_u64(uint64x2_t, uint64x2_t)’
2026-06-14T22:01:42.7349505Z  7646 | vceqq_u64 (uint64x2_t __a, uint64x2_t __b)
2026-06-14T22:01:42.7350020Z       |            ~~~~~~~~~~~^~~
2026-06-14T22:01:42.7351062Z /run/build/netgen/libsrc/core/simd_arm64.hpp: In function ‘ngcore::SIMD<ngcore::mask64, 2> ngcore::operator>(SIMD<long int, 2>, SIMD<long int, 2>)’:
2026-06-14T22:01:42.7353124Z /run/build/netgen/libsrc/core/simd_arm64.hpp:166:21: error: could not convert ‘vcgtq_s64(a.ngcore::SIMD<long int, 2>::Data(), b.ngcore::SIMD<long int, 2>::Data())’ from ‘uint64x2_t’ to ‘ngcore::SIMD<ngcore::mask64, 2>’
2026-06-14T22:01:42.7354611Z   166 |     return vcgtq_s64(a.Data(), b.Data());
2026-06-14T22:01:42.7355123Z       |            ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
2026-06-14T22:01:42.7355591Z       |                     |
2026-06-14T22:01:42.7355998Z       |                     uint64x2_t
2026-06-14T22:01:42.7356880Z [35/179] Building CXX object CMakeFiles/nglib.dir/libsrc/general/optmem.cpp.o
2026-06-14T22:01:42.7357731Z FAILED: [code=1] CMakeFiles/nglib.dir/libsrc/general/optmem.cpp.o 
2026-06-14T22:01:42.7363467Z /run/ccache/bin/c++ -DHAVE_DLFCN_H -DOCCGEOMETRY -Dnglib_EXPORTS -I/run/build/netgen/_flatpak_build/netgen -I/run/build/netgen -I/run/build/netgen/include -I/run/build/netgen/libsrc -I/run/build/netgen/libsrc/include -isystem /app/include/opencascade -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -mbranch-protection=bti+pac-ret -O2 -g -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -march=native -MD -MT CMakeFiles/nglib.dir/libsrc/general/optmem.cpp.o -MF CMakeFiles/nglib.dir/libsrc/general/optmem.cpp.o.d -o CMakeFiles/nglib.dir/libsrc/general/optmem.cpp.o -c /run/build/netgen/libsrc/general/optmem.cpp
```

2026-06-15 21:59 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2026-06-16 09:33 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2026-06-16 15:31 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2026-06-17 00:39 UTC, bbhtt commented on fi.csc.Elmer.desktop
have you submitted metainfo and desktop to upstream?

2026-06-17 00:41 UTC, bbhtt commented on fi.csc.Elmer.yaml
> +      - /share/man
in toplevel

2026-06-17 00:41 UTC, bbhtt commented on fi.csc.Elmer.yaml
> +      - /share/doc
in toplevel

2026-06-18 11:36 UTC, kevinsmia1939 commented on fi.csc.Elmer.desktop
yes, this one https://github.com/ElmerCSC/elmerfem/pull/323

2026-06-18 12:44 UTC, kevinsmia1939 commented on fi.csc.Elmer.yaml
> +      - /share/man
fixed

2026-06-18 12:44 UTC, kevinsmia1939 commented on fi.csc.Elmer.yaml
> +      - /share/doc
fixed

2026-06-18 14:12 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2026-06-18 23:00 UTC, kevinsmia1939 commented
bot, build fi.csc.Elmer

2026-06-19 04:48 UTC, bbhtt commented
/merge head=29c945f29bddd25be96497bf14c9ed8f84a55d46

2026-06-19 04:48 UTC, closed without merging