Add org.vertcoin.vertcoin-qt
flathub/flathub pull request #3004
Opened 2022-04-12 22:15 UTC by vertiond

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-12 22:16 UTC, vertiond commented
bot, build org.vertcoin.vertcoin-qt

2022-04-12 22:28 UTC, hfiguiere requested changes

2022-04-12 22:28 UTC, hfiguiere commented on flathub.json
> +  "only-arches": ["x86_64", "arm", "aarch64"]
you can remove this it's not needed.

2022-04-12 22:28 UTC, hfiguiere commented on org.vertcoin.vertcoin-qt.json
> +        },
```suggestion
```

this arch isn't supported anymore for at least 2 years

2022-04-12 22:28 UTC, hfiguiere commented on org.vertcoin.vertcoin-qt.json
> +          "url": "https://github.com/vertcoin-project/vertcoin-core/vertcoin-0.18.0-x86_64-linux-gnu.tar.gz",
this URL is 404

2022-04-12 22:28 UTC, hfiguiere commented on org.vertcoin.vertcoin-qt.json
> +          "url": "https://github.com/vertcoin-project/vertcoin-core/vertcoin-0.18.0-aarch64-linux-gnu.tar.gz",
this URL is 404

2022-04-12 22:31 UTC, hfiguiere commented
also both the .desktop file and appdata should be submitted upstream to be managed there.

2022-04-16 14:09 UTC, vertiond commented
Looks good to me.

2022-04-19 12:24 UTC, barthalion commented
bot, build org.vertcoin.vertcoin-qt

2022-04-19 13:16 UTC, barthalion commented
/merge

2022-04-19 13:17 UTC, closed without merging