Add QXmlEdit
flathub/flathub pull request #3071
Opened 2022-04-25 20:08 UTC by Mailaender

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions.
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/lbellonda/qxmledit/issues/77
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. (https://github.com/lbellonda/qxmledit/pull/84 https://github.com/lbellonda/qxmledit/pull/85)

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-25 21:16 UTC, hfiguiere commented on org.qxmledit.qxmledit.yml
> +        dest: qxmledit
you shouldn't need to do that (and line 16)

2022-04-25 21:18 UTC, hfiguiere commented on org.qxmledit.qxmledit.yml
> +      - mv ${FLATPAK_DEST}/share/applications/QXmlEdit.desktop ${FLATPAK_DEST}/share/applications/${FLATPAK_ID}.desktop
you should just use `rename-desktop-file: QXmlEdit.desktop`

2022-04-25 21:18 UTC, hfiguiere commented on org.qxmledit.qxmledit.yml
> +      - mv ${FLATPAK_DEST}/share/appdata/QXmlEdit.appdata.xml ${FLATPAK_DEST}/share/appdata/${FLATPAK_ID}.appdata.xml
yui should just ise `rename-appdata-file: QXmlEdit.appdata.xml`

2022-04-25 21:20 UTC, hfiguiere commented
bot, build org.qxmledit.QXmlEdit

2022-04-25 22:10 UTC, hfiguiere commented
The manifest file should be named after the app-id: `org.qxmledit.QXmlEdit.json`. Otherwise it won't be found by the flathub bot.

2022-04-26 07:52 UTC, Mailaender commented
Updated. Can I keep it in @yaml?

2022-04-26 10:23 UTC, JakobDev commented
The Appdata patches should not been needed. Everything is valid according to the [Specification](https://www.freedesktop.org/software/appstream/docs/). The thing, that should be changed, is that the Mimetypes tag is [depracted](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-mimetypes). But it is still valid and flatpak-builder should not complain about it. Maybe you have a old version of appstream-glib.

2022-04-26 11:02 UTC, Mailaender commented
Removed the appdata patch. I got this gibberish error message on https://neon.kde.org/ without them:
```
Error loading AppData file: failed to parse /app/share/appdata/org.qxmledit.QXmlEdit.appdata.xml: Error on line 25 char 9: <categories> already set '' and tried to replace with '
    '
```

2022-04-26 11:30 UTC, hfiguiere commented
> Updated. Can I keep it in @yaml?

sorry it's about it being case sensitive. I mistakenly wrote .json.

2022-04-26 11:32 UTC, hfiguiere commented
bot, build org.qxmledit.QXmlEdit

2022-04-26 11:37 UTC, hfiguiere commented on org.qxmledit.QXmlEdit.yml
> +        path: categories.patch
this patch was removed from the repo, so it is not found.

(hence the failure)

2022-04-26 11:39 UTC, hfiguiere commented
bot, build org.qxmledit.QXmlEdit

2022-04-26 11:56 UTC, Mailaender commented
> Error loading AppData file: failed to parse /srv/buildbot/worker/build-x86_64-6/build/.flatpak-builder/rofiles/rofiles-GLbTvX/files/share/appdata/org.qxmledit.QXmlEdit.appdata.xml: Error on line 24 char 9: <categories> already set '​' and tried to replace with '
    ​'
Error: ERROR: appstream-compose failed: Child process exited with code 1

Same problem I encountered, so I am adding the patch back in.

2022-04-26 16:34 UTC, hfiguiere commented
bot, build org.qxmledit.QXmlEdit

2022-04-26 16:49 UTC, hfiguiere commented
```
builddir/files/share/appdata/org.qxmledit.QXmlEdit.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• attribute-invalid     : <screenshot> width (800) did not match specified (808) [https://raw.githubusercontent.com/lbellonda/qxmledit/master/install_scripts/environment/desktop/screenshots/qxmledit800.png]
• attribute-invalid     : <screenshot> height (600) did not match specified (599) [https://raw.githubusercontent.com/lbellonda/qxmledit/master/install_scripts/environment/desktop/screenshots/qxmledit800.png]
• attribute-missing     : <release> has no timestamp
Validation of files failed
```

2022-04-26 18:45 UTC, Mailaender commented
Updated my patch https://github.com/lbellonda/qxmledit/pull/85.

2022-04-26 18:48 UTC, hfiguiere commented
btw you can also trigger the build


bot, build org.qxmledit.QXmlEdit

2022-04-26 20:07 UTC, hfiguiere requested changes

2022-05-05 08:32 UTC, barthalion commented
/merge @lbellonda

2022-05-05 08:33 UTC, closed without merging