Add Legacy Master PDF Editor
flathub/flathub pull request #3087
Opened 2022-04-30 20:40 UTC by jointri

Had to delete my old repo and make a fresh one in order to be able to make a new PR, this one should be fixed for new PR for new package for flathub. This package is important because it is the last version to be able to make edits to a PDF without watermark. Let me know if you want any changes to this PR.

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-30 21:02 UTC, hfiguiere requested changes

2022-04-30 21:02 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor-Legacy.yaml
> +app-id: net.codeindustry.MasterPDFEditor
also here the id should match too.

2022-04-30 21:02 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor-Legacy.yaml
> +runtime-version: '5.13'
```suggestion
runtime-version: '5.15-21.08'
```

5.13 is EOL

2022-04-30 21:30 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor4.metainfo.xml
> +  <launchable type="desktop-id">net.codeindustry.MasterPDFEditor.desktop</launchable>
```suggestion
  <launchable type="desktop-id">net.codeindustry.MasterPDFEditor4.desktop</launchable>
```

2022-04-30 21:31 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor4.metainfo.xml
> +  <launchable type="desktop-id">net.codeindustry.MasterPDFEditor.desktop</launchable>
nevermind, stream crossed.

2022-04-30 21:32 UTC, jointri commented
Made a few changes. Let me know what you think.

2022-04-30 21:35 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor4.desktop
> +Icon=net.codeindustry.MasterPDFEditor-Legacy
```suggestion
Icon=net.codeindustry.MasterPDFEditor4
```

2022-04-30 21:35 UTC, hfiguiere commented
bot, build net.codeindustry.MasterPDFEditor4

2022-04-30 21:58 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor4.yaml
> +          - 'tar --strip-components=1 -xf master-pdf-editor-4.3.89_qt5.amd64.tar.gzz'
you need to restrict the build to x86_64: https://github.com/flathub/flathub/wiki/App-Maintenance#flathubjson

(unless there is a version for aarch64)

2022-04-30 21:59 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor4.yaml
> +      - 'install -Dm 644 net.codeindustry.MasterPDFEditor-Legacy.png -t /app/share/icons/hicolor/128x128/apps'
```suggestion
      - 'install -Dm 644 net.codeindustry.MasterPDFEditor4.metainfo.xml -t /app/share/metainfo'
      - 'install -Dm 644 net.codeindustry.MasterPDFEditor4.desktop -t /app/share/applications'
      - 'install -Dm 644 net.codeindustry.MasterPDFEditor4.png -t /app/share/icons/hicolor/128x128/apps'
```

and you need to rename the PNG

2022-04-30 22:00 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor4.yaml
> +        path: net.codeindustry.MasterPDFEditor-Legacy.png
```suggestion
        path: net.codeindustry.MasterPDFEditor4.metainfo.xml
      - type: file
        path: net.codeindustry.MasterPDFEditor4.desktop
      - type: file
        path: net.codeindustry.MasterPDFEditor4.png
```

2022-04-30 22:03 UTC, jointri commented
bot, build net.codeindustry.MasterPDFEditor4

2022-04-30 22:05 UTC, jointri commented
What does this extra data error mean?

2022-04-30 22:11 UTC, jointri commented
bot, build net.codeindustry.MasterPDFEditor4

2022-04-30 22:12 UTC, jointri commented
bot, build net.codeindustry.MasterPDFEditor4

2022-04-30 22:18 UTC, jointri commented
Before anyone approves of this PR, I found the following in the build log:

INFO    src.manifest: Checking 2 external data items
INFO    src.manifest: Skipped check [1/2] archive sane-backends-1.0.28.tar.gz (from net.codeindustry.MasterPDFEditor4.yaml)
INFO    src.manifest: Started check [2/2] extra-data master-pdf-editor-4.3.89_qt5.amd64.tar.gz (from net.codeindustry.MasterPDFEditor4.yaml)
ERROR   src.manifest: Failed to check extra-data master-pdf-editor-4.3.89_qt5.amd64.tar.gz with URLChecker: Error downloading upstream source: 403, message='Forbidden', url=URL('https://www.code-industry.net:443/public/')
BROKEN: master-pdf-editor-4.3.89_qt5.amd64.tar.gz
 Couldn't get new version for http://www.code-industry.net/public/
WARNING src.main: Check finished with 1 error(s)

Should this be of any concern?

2022-04-30 22:29 UTC, jointri commented
@hfiguiere 
What do you think of the error that I got, the build still pressed on. Was the flatpak made incorrectly?

2022-04-30 22:33 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor4.yaml
> +        filename: master-pdf-editor-4.3.89_qt5.amd64.tar.gz
```suggestion
        url: http://www.code-industry.net/public/master-pdf-editor-4.3.89_qt5.amd64.tar.gz
```

I think that's the proper one. the URL is supposed to download the file.

2022-04-30 22:33 UTC, hfiguiere commented on flathub.json
> +  "only-arches": ["x86_64"]
```suggestion
  "only-arches": ["x86_64"]
```

2022-04-30 22:33 UTC, jointri commented
bot, build net.codeindustry.MasterPDFEditor4

2022-04-30 22:37 UTC, jointri commented
bot, build net.codeindustry.MasterPDFEditor4

2022-04-30 22:45 UTC, jointri commented
@hfiguiere 
I think it worked out without issue. Can it be merged now?

2022-04-30 23:01 UTC, hfiguiere commented
I can't merge. Just be patient.

2022-05-02 18:22 UTC, muelli commented
note that the legacy version is already on flathub:
https://github.com/flathub/net.codeindustry.MasterPDFEditor/tree/4.3.89

but it may well be worth it to have the same app twice...

2022-05-02 18:38 UTC, hfiguiere commented
1. this branch isn't published on flathub (but that can be fixed)
2. I believe that it's better to have a separate App in these circumstances (not sure everyone agree), as it is more user friendly than having app branches.

2022-05-05 09:11 UTC, barthalion commented
```
[bpiotrowski@risuku ~]$ flatpak run net.codeindustry.MasterPDFEditor4
bwrap: execvp masterpdfeditor4: No such file or directory

[bpiotrowski@risuku ~]$ cat .local/share/flatpak/exports/share/applications/net.codeindustry.MasterPDFEditor4.desktop 
[Desktop Entry]
Name=Master PDF Editor 4
Comment=Edit PDF files
Exec=/usr/bin/flatpak run --branch=test --arch=x86_64 --command=masterpdfeditor --file-forwarding net.codeindustry.MasterPDFEditor4 @@ %f @@
Terminal=false
Icon=net.codeindustry.MasterPDFEditor4
Type=Application
Categories=Office;Graphics;
MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;
X-Flatpak=net.codeindustry.MasterPDFEditor4

[bpiotrowski@risuku ~]$ /usr/bin/flatpak run --branch=test --arch=x86_64 --command=masterpdfeditor --file-forwarding net.codeindustry.MasterPDFEditor4
bwrap: execvp masterpdfeditor: No such file or directory
```

It can be launched neither via CLI or the desktop file.

2022-05-05 12:02 UTC, hfiguiere commented on net.codeindustry.MasterPDFEditor4.yaml
> +command: masterpdfeditor4
are you sure it's the right command?

2022-08-07 14:52 UTC, closed without merging