Org.gnome.crosswords
flathub/flathub pull request #3088
Opened 2022-04-30 21:31 UTC by blandford

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [s] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-04-30 21:33 UTC, hfiguiere requested changes

2022-04-30 21:33 UTC, hfiguiere commented on org.gnome.Crosswords.json
> +        "--env=PATH=/app/bin:/usr/bin",
You shouldn't need it.
```suggestion
```

2022-04-30 21:34 UTC, hfiguiere commented
bot, build org.gnome.Crosswords

2022-04-30 23:00 UTC, bilelmoussaoui commented on org.gnome.Crosswords.json
> +        "/share/icons/hicolor/scalable/apps/org.gnome.Adwaita1.Demo.svg",
```suggestion
```
Are those actually needed? You don't ship adwaita yourself as it is part of the sdk

2022-05-05 08:15 UTC, barthalion commented
bot, build org.gnome.Crosswords

2022-05-05 08:15 UTC, barthalion commented on org.gnome.Crosswords.json
> +        "org.gnome.Crosswords.PuzzleSets": {
Do you plan to submit additional puzzle sets eventually?

2022-05-05 08:25 UTC, barthalion commented
/merge

2022-05-05 08:26 UTC, closed without merging

2022-05-05 13:59 UTC, blandford commented
Yes! I have two puzzle sets ready to go now, and I'm working on a third.
I'm also working on documentation to let 3rd-party folks produce them,
though I don't expect that immediately.


On Thu, May 5, 2022 at 1:15 AM Bartłomiej Piotrowski <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In org.gnome.Crosswords.json
> <https://github.com/flathub/flathub/pull/3088#discussion_r865657057>:
>
> > +    ],
> +    "cleanup" : [
> +        "/include",
> +        "/lib/girepository-1.0",
> +        "/lib/pkgconfig",
> +        "/libexec/installed-tests",
> +        "/man",
> +        "/share/doc",
> +        "/share/gtk-doc",
> +        "/share/man",
> +        "/share/pkgconfig",
> +        "*.la",
> +        "*.a"
> +    ],
> +    "add-extensions": {
> +        "org.gnome.Crosswords.PuzzleSets": {
>
> Do you plan to submit additional puzzle sets eventually?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/flathub/flathub/pull/3088#pullrequestreview-962996315>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMYFPKRTC5GBQOUTORR2YDVIN7TDANCNFSM5UY4A4YQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>