Add io.github.diegoivan.GaticTacToe
flathub/flathub pull request #3089
Opened 2022-05-01 00:22 UTC by Diego-Ivan

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. 
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-05-01 00:23 UTC, Diego-Ivan commented
bot, build io.github.diegoivan.GaticTacToe

2022-05-01 00:31 UTC, Diego-Ivan commented
bot, build io.github.diegoivan.GaticTacToe

2022-05-01 00:33 UTC, hfiguiere requested changes

2022-05-01 00:33 UTC, hfiguiere commented on io.github.diegoivan.GaticTacToe.json
> +  },
you don't need this, valac is in the Sdk.

The vala sdk extension is for IDE.

2022-05-01 01:36 UTC, Diego-Ivan commented
bot, build io.github.diegoivan.GaticTacToe

2022-05-01 16:03 UTC, Diego-Ivan commented
bot, build io.github.diegoivan.GaticTacToe

2022-05-01 17:47 UTC, Diego-Ivan commented
bot, build io.github.diegoivan.GaticTacToe

2022-05-01 18:33 UTC, Diego-Ivan commented
I'm not very sure why the build is failing. I don't exactly what this error is about:
```
stat builddir/*/share/app-info/xmls/io.github.diegoivan.GaticTacToe.xml.gz
 in dir /srv/buildbot/worker/build-x86_64-6/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'stat builddir/*/share/app-info/xmls/io.github.diegoivan.GaticTacToe.xml.gz'
 using PTY: False
stat: cannot stat 'builddir/*/share/app-info/xmls/io.github.diegoivan.GaticTacToe.xml.gz': No such file or directory
program finished with exit code 1
elapsedTime=0.010660
```
Can I get a little help?

2022-05-01 21:17 UTC, Diego-Ivan commented
@hfiguiere Any ideas on what might not be going right? Thanks in advance

2022-05-01 23:08 UTC, hfiguiere commented
the appstream file is simply not found.

2022-05-01 23:20 UTC, hfiguiere commented
```
WARNING: Failed to validate desktop file /var/home/hub/source/flathub/io.github.diegoivan.GaticTacToe/repo/export/share/applications/io.github.diegoivan.GaticTacToe.desktop: /var/home/hub/source/flathub/io.github.diegoivan.GaticTacToe/repo/export/share/applications/io.github.diegoivan.GaticTacToe.desktop: error: value "Games;GNOME;GTK;" for key "Categories" in group "Desktop Entry" contains an unregistered value "Games"; values extending the format should start with "X-"
/var/home/hub/source/flathub/io.github.diegoivan.GaticTacToe/repo/export/share/applications/io.github.diegoivan.GaticTacToe.desktop: hint: value "Games;GNOME;GTK;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu
```

This is building locally.

2022-05-01 23:22 UTC, hfiguiere commented
Here is the list of main categories

https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry

2022-05-01 23:31 UTC, Diego-Ivan commented
Thank you so much for your help!

2022-05-01 23:31 UTC, Diego-Ivan commented
bot, build io.github.diegoivan.GaticTacToe

2022-05-01 23:32 UTC, hfiguiere commented
it will fail.

the app-id in the appdata file is incorrect.

2022-05-01 23:45 UTC, hfiguiere commented
build should have failed. But for sure the app-id in the appdata file doesn't match the app-id.

2022-05-02 00:08 UTC, Diego-Ivan commented
Thanks for you comments! I'll push the changes and rebuild

2022-05-02 00:09 UTC, Diego-Ivan commented
bot, build io.github.diegoivan.GaticTacToe

2022-05-05 08:13 UTC, barthalion commented
/merge

2022-05-05 08:15 UTC, closed without merging