Add com.wickeditor.WickEditor
flathub/flathub pull request #3126
Opened 2022-05-10 15:12 UTC by Aman9das

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** The project is largely not under development anymore.
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-05-10 15:52 UTC, Aman9das commented
bot, build com.wickeditor.WickEditor

2022-05-10 17:08 UTC, hfiguiere commented on com.wickeditor.WickEditor.yml
> +  cxxflags: -O2 -g
```suggestion
```

2022-05-11 07:23 UTC, barthalion requested changes
`shared-modules` were added directly instead of git submodule.

2022-05-11 07:24 UTC, barthalion commented
Have you reached out to upstream developers about your submission?

2022-05-11 14:50 UTC, hfiguiere requested changes
You should submit the .desktop and the metainfo.xml upstream.

The lack of .desktop upstream is a bug.

2022-05-11 14:50 UTC, hfiguiere commented on com.wickeditor.WickEditor.yml
> +        path: com.wickeditor.WickEditor.png
there is an icon file at https://github.com/Wicklets/wick-editor/blob/master/public/icon.png

why do you need this one?

2022-05-11 14:50 UTC, hfiguiere commented on com.wickeditor.WickEditor.yml
> +      - install -D com.wickeditor.WickEditor.png /app/share/icons/hicolor/128x128/apps/com.wickeditor.WickEditor.png
this icon is NOT 128x128 but rather 521x512

2022-05-11 15:05 UTC, Aman9das commented
bot, build com.wickeditor.WickEditor

2022-05-11 15:06 UTC, hfiguiere commented on com.wickeditor.WickEditor.yml
> +      - install -D com.wickeditor.WickEditor.png /app/share/icons/hicolor/128x128/apps/com.wickeditor.WickEditor.png
and the metainfo and a properly sized icons.

2022-05-12 02:02 UTC, Aman9das commented
Hello! May I ask what all are holding up the publishing of wick editor

2022-05-12 02:04 UTC, hfiguiere commented
patience?

2022-05-12 02:05 UTC, Aman9das commented
> patience?

Thanks! My bad.. i thought i something something was needed at my end

2022-05-12 07:00 UTC, barthalion commented
/merge

2022-05-12 07:02 UTC, closed without merging