Add Pentobi
flathub/flathub pull request #3149
Opened 2022-05-15 11:58 UTC by Mailaender

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-05-15 11:58 UTC, Mailaender commented
bot, build io.sourceforge.pentobi

2022-05-15 14:08 UTC, hfiguiere requested changes

2022-05-15 14:08 UTC, hfiguiere commented on io.sourceforge.pentobi.yml
> +    buildsystem: cmake
Cmake-ninja doesn't work?
```suggestion
    buildsystem: cmake-ninja
```

2022-05-15 16:51 UTC, Mailaender commented on io.sourceforge.pentobi.yml
> +    buildsystem: cmake
No it fails due to cyclic dependencies.

2022-05-15 18:15 UTC, enz commented
Great. If you are interested in maintaining the flatpack config, I could add a link from the Pentobi homepage.

Also note that  PENTOBI_OPEN_HELP_EXTERNALLY is no longer neede with Pentobi >= 19.0 because it always uses an external browser (and it won't be needed in the future because Pentobi >= 21.0 will include a custom help viewer impementation, which neither needs QtWebView nor an external browser).

2022-05-15 19:36 UTC, Mailaender commented
Removed the option. I think for the help to work you need a browser installed in the sandbox as well (untested) which is a bit unfortunate.

2022-05-16 08:49 UTC, barthalion commented
bot, build io.sourceforge.pentobi

2022-05-16 09:11 UTC, barthalion commented
Yeah, opening help definitely doesn't work. I know GNOME apps somehow handle this, but I don't remember how. Alternatively, help button could be changed to open an external URL.

2022-05-16 09:11 UTC, barthalion commented
/merge @enz

2022-05-16 09:12 UTC, closed without merging