Add vokoscreenNG
flathub/flathub pull request #3179
Opened 2022-05-21 13:38 UTC by Mailaender

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/vkohaupt/vokoscreenNG/issues/21 https://github.com/vkohaupt/vokoscreenNG/issues/58
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* https://github.com/vkohaupt/vokoscreenNG/pull/94 https://github.com/vkohaupt/vokoscreenNG/pull/126 https://github.com/vkohaupt/vokoscreenNG/pull/165 https://github.com/vkohaupt/vokoscreenNG/issues/93

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-05-21 14:05 UTC, hfiguiere commented
bot, build com.github.vkohaupt.vokoscreenNG

2022-05-21 14:06 UTC, hfiguiere requested changes

2022-05-21 14:06 UTC, hfiguiere commented on com.github.vkohaupt.vokoscreenNG.yml
> +  - --device=dri
```suggestion
  - --device=all
```

dri is include in all.

2022-05-21 14:06 UTC, hfiguiere commented on vokoscreenNG.appdata.xml
> +  <metadata_license>MIT</metadata_license>
`CC0-1.0` is prefered.

2022-05-23 06:49 UTC, barthalion commented
bot, build com.github.vkohaupt.vokoscreenNG

2022-05-24 06:49 UTC, barthalion commented
/merge @vkohaupt

2022-05-24 06:50 UTC, closed without merging