Add Frogatto & Friends
flathub/flathub pull request #3213
Opened 2022-05-27 13:30 UTC by Mailaender

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/frogatto/frogatto/issues/584
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* https://github.com/frogatto/frogatto/pull/580 https://github.com/frogatto/frogatto/pull/581 https://github.com/frogatto/frogatto/pull/582 https://github.com/frogatto/frogatto/pull/583 https://github.com/frogatto/frogatto/pull/585

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-05-27 16:04 UTC, Mailaender commented
bot, build com.frogatto.Frogatto

2022-05-27 16:14 UTC, hfiguiere requested changes

2022-05-27 16:14 UTC, hfiguiere commented on frogatto.appdata.xml
> +  <id>frogatto.desktop</id>
you should use the app-id here.

2022-05-27 16:14 UTC, hfiguiere commented on frogatto.desktop
> +Icon=frogatto
and use the proper icon name.

2022-05-27 16:14 UTC, hfiguiere commented on com.frogatto.Frogatto.yaml
> +      - cflags: -std=c++11
are you sure? `-std=c++11` belong to `cxxflags`

2022-05-27 16:14 UTC, hfiguiere commented on com.frogatto.Frogatto.yaml
> +rename-icon: frogatto
as stated in other PR. if you do provide these files, you should install them with the right name from the ground up. The "rename" stuff is really only for when upstream doesn't conform to XDG standards.

2022-05-27 16:15 UTC, hfiguiere commented
And please fix the upstream PR to use a proper app-id a filenames.

2022-05-27 17:04 UTC, Mailaender commented
bot, build com.frogatto.Frogatto

2022-05-27 17:12 UTC, hfiguiere commented on frogatto.appdata.xml
> +  <project_license>Zlib and proprietary</project_license>
these licenses identifiers are invalid.

2022-05-27 19:16 UTC, hfiguiere commented on frogatto.appdata.xml
> +  <project_license>LicenseRef-proprietary</project_license>
```suggestion
  <project_license>Zlib AND CC-BY-3.0 AND LicenseRef-proprietary</project_license>
```

2022-05-27 19:31 UTC, Mailaender commented
bot, build com.frogatto.Frogatto

2022-05-28 09:47 UTC, Mailaender commented
bot, build com.frogatto.Frogatto

2022-05-30 05:45 UTC, barthalion commented on com.frogatto.Frogatto.yaml
> +  - shared-modules/SDL/SDL-1.2.15.json
Have you tested sdl12-compat?

2022-05-30 05:45 UTC, barthalion commented on com.frogatto.Frogatto.yaml
> +      - cxxflags: -std=c++11
```suggestion
    build-options:
      cxxflags: -std=c++11
```

2022-05-30 05:54 UTC, barthalion commented on com.frogatto.Frogatto.yaml
> +  - shared-modules/SDL/SDL-1.2.15.json
I just did, and it doesn't work.

2022-05-30 06:01 UTC, barthalion commented
/merge

2022-05-30 06:03 UTC, closed without merging