Add AudioTube
flathub/flathub pull request #3219
Opened 2022-05-27 20:01 UTC by JBBgameich

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project.
- [x] I own the domain used in the application ID. (Not directly me, but KDE does)
- [x] Any additional patches or files have been submitted to the upstream projects concerned.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-05-27 20:02 UTC, JBBgameich commented
bot, build org.kde.audiotube

2022-05-27 20:02 UTC, hfiguiere commented
cc @flathub/kde

2022-05-27 20:05 UTC, hfiguiere requested changes

2022-05-27 20:05 UTC, hfiguiere commented on org.kde.audiotube.json
> +            "sources": [ { "type": "git", "url": "https://github.com/pybind/pybind11", "tag": "v2.9.1" } ]
```suggestion
            "sources": [
                {
                    "type": "git", 
                    "url": "https://github.com/pybind/pybind11", 
                    "tag": "v2.9.1" 
                }
            ]
```

2022-05-27 20:05 UTC, hfiguiere commented on org.kde.audiotube.json
> +            "config-opts": ["-DPYBIND11_FINDPYTHON=ON"],
```suggestion
            "config-opts": [
                "-DPYBIND11_FINDPYTHON=ON"
            ],
```

2022-05-27 20:05 UTC, hfiguiere commented on org.kde.audiotube.json
> +            "name": "org.kde.audiotube",
```suggestion
            "name": "audiotube",
```

2022-05-27 20:05 UTC, hfiguiere commented on org.kde.audiotube.json
> +            "config-opts": ["-DPYBIND11_FINDPYTHON=ON", "-DPYBIND11_TEST=OFF"],
```suggestion
            "config-opts": [
                "-DPYBIND11_FINDPYTHON=ON",
                "-DPYBIND11_TEST=OFF"
            ],
```

2022-05-27 21:12 UTC, CarlSchwan commented
Looks good to me

2022-05-27 22:36 UTC, JBBgameich commented
bot, build org.kde.audiotube

2022-05-28 14:56 UTC, JBBgameich commented
bot, build org.kde.audiotube

2022-05-28 17:51 UTC, JBBgameich commented
This should be ready now from my side as far as I can see.

2022-05-30 05:50 UTC, barthalion commented
/merge

2022-05-30 05:52 UTC, closed without merging