Add OpenLieroX
flathub/flathub pull request #3220
Opened 2022-05-27 20:34 UTC by Mailaender

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-05-27 20:34 UTC, Mailaender commented
bot, build net.sourceforge.OpenLieroX

2022-05-27 21:05 UTC, hfiguiere requested changes

2022-05-27 21:05 UTC, hfiguiere commented on net.sourceforge.OpenLieroX.appdata.xml
> +  <metadata_license>CC0-1.0</metadata_license>
it's missing a project license

2022-05-27 21:05 UTC, hfiguiere commented on net.sourceforge.OpenLieroX.appdata.xml
> +    <release version="0.58 rc5" date="2018-07-23"/>
I bet appstream validate will dislike the unordered releases.

2022-05-27 21:05 UTC, hfiguiere commented on net.sourceforge.OpenLieroX.yaml
> +  - --socket=wayland
are you sure it supports wayland since it uses SDL 1.2

2022-05-27 23:47 UTC, hfiguiere commented on net.sourceforge.OpenLieroX.yaml
> +      - install -Dm644 net.sourceforge.OpenLieroX.appdata.xml ${FLATPAK_DEST}/share/appdata/openlierox.appdata.xml
you install it with the wrong name. hence, it's not found.

2022-05-28 09:52 UTC, Mailaender commented
bot, build net.sourceforge.OpenLieroX

2022-05-28 10:19 UTC, Mailaender commented
bot, build net.sourceforge.OpenLieroX

2022-05-30 05:59 UTC, barthalion commented
bot, build net.sourceforge.OpenLieroX

2022-05-30 07:33 UTC, barthalion commented
/merge

2022-05-30 07:34 UTC, closed without merging