Add BlueBubbles
flathub/flathub pull request #3283
Opened 2022-06-23 16:46 UTC by jjoelj

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-06-23 21:06 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +  - --own-name=app.bluebubbles.BlueBubbles
this is automatically granted
```suggestion
```

2022-06-23 21:14 UTC, hfiguiere requested changes

2022-06-23 21:14 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +        url: https://ftp.lysator.liu.se/pub/opensuse/distribution/leap/15.3/repo/oss/x86_64/libappindicator3-1-12.10.1+bzr20170215-1.12.x86_64.rpm
this is not a SUSE distribution. libappindicator is commonly build on Flathub by various other packages. You should do the same.

And the other dependencies.

2022-06-23 21:14 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +        path: bluebubbles-linux-portable.tar.gz
this should NOT be in this repository. This should be downloaded from upstream. Even more  since this is a 56MB archive.

2022-06-23 21:14 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.metainfo.xml
> +</component>
`content_rating` and `releases` are missing.

2022-06-23 21:14 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +sdk: org.gnome.Sdk
do you really need the GNOME SDK?

2022-06-24 06:42 UTC, jjoelj commented on app.bluebubbles.BlueBubbles.yml
> +sdk: org.gnome.Sdk
It is used for libnotify.

2022-06-24 17:07 UTC, hfiguiere requested changes

2022-06-24 17:07 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +        url: https://github.com/BlueBubblesApp/bluebubbles-app/releases/download/v1.9.1%2B30/bluebubbles-linux-portable.tar.gz
I have doubt how "portable" that is.

`/lib` contains `ELF 64-bit LSB shared object, x86-64,`

So I have doubt of the validaty of aarch64 support here.

It's sad, but it's flutter.

2022-06-24 17:07 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +      - 'cp -r bluebubbles /app/'
This install a bunch of Windows DLL too. They should be skipped. See `data/flutter_assets/packages/record_windows`

2022-06-24 17:07 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +      - 'cp -r app.bluebubbles.BlueBubbles.metainfo.xml /app/share/metainfo/'
```suggestion
      - 'install -Dm644 app.bluebubbles.BlueBubbles.metainfo.xml -t /app/share/metainfo/'
```

2022-06-24 17:07 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +      - 'cp -r app.bluebubbles.BlueBubbles.metainfo.xml /app/share/appdata/'
```suggestion
```

You already installed it

2022-06-24 17:07 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +      - 'cp -r app.bluebubbles.BlueBubbles.desktop /app/share/applications/'
```suggestion
      - 'install -Dm644 app.bluebubbles.BlueBubbles.desktop -t /app/share/applications/'
```

2022-06-24 17:07 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +      - type: file
```suggestion
      - type: archive
        dest: bluebubbles
```

2022-06-24 17:07 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +      - 'tar -xf bluebubbles-linux-portable.tar.gz -C bluebubbles'
```suggestion
```

With the change to the source type below.

2022-06-24 17:07 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +      - /lib/*.la
```suggestion
      - '*.la'
      - '*.a'
```

2022-06-24 17:08 UTC, hfiguiere commented
bot, build app.bluebubbles.BlueBubbles

2022-06-24 18:09 UTC, hfiguiere commented
```
builddir/files/share/appdata/app.bluebubbles.BlueBubbles.appdata.xml: FAILED:
• tag-missing           : <url> is not present
Validation of files failed
```

2022-06-24 19:02 UTC, jjoelj commented on app.bluebubbles.BlueBubbles.yml
> +  - --socket=wayland
It apparently does not. Removed.

2022-06-24 19:03 UTC, jjoelj commented on app.bluebubbles.BlueBubbles.yml
> +      - 'cp -r libobjectbox.so /app/lib/'
When I make from source, it tries to access the internet to download the pre-built release binary.

2022-06-24 19:03 UTC, jjoelj commented
bot, build app.bluebubbles.BlueBubbles

2022-06-24 19:06 UTC, jjoelj commented
bot, build app.bluebubbles.BlueBubbles

2022-06-24 19:30 UTC, jjoelj commented
bot, build app.bluebubbles.BlueBubbles

2022-06-24 21:25 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +        url: https://github.com/BlueBubblesApp/bluebubbles-app/releases/download/v1.9.1%2B30/bluebubbles-linux-portable.tar
my comment about this being x86_64 binaries still stands.

2022-06-24 21:25 UTC, hfiguiere commented on app.bluebubbles.BlueBubbles.yml
> +        path: app.bluebubbles.BlueBubbles.metainfo.xml
```suggestion
```

this was listed twice.

2022-06-27 00:19 UTC, hfiguiere commented
bot, build app.bluebubbles.BlueBubbles

2022-06-27 09:01 UTC, barthalion commented
/merge

2022-06-27 09:02 UTC, closed without merging