Add Naikari
flathub/flathub pull request #3287
Opened 2022-06-26 09:36 UTC by Mailaender

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://github.com/naikari/naikari/pull/6
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* https://github.com/naikari/naikari/pull/6

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-06-26 09:38 UTC, Mailaender commented
bot, build io.github.naikari.Naikari

2022-06-26 09:44 UTC, Mailaender commented
bot, build io.github.naikari.Naikari

2022-06-26 14:02 UTC, hfiguiere requested changes
You probably need cleanup rules for all these `include`

2022-06-26 14:02 UTC, hfiguiere commented on io.github.naikari.Naikari.yaml
> +        commit: 4c2441c16ce3c4e312aaefecc6d40c4fe21de97c
you never put a branch.

```suggestion
        # branch: v2.1
        commit: 4c2441c16ce3c4e312aaefecc6d40c4fe21de97c
```

(I leave as a comment for information)

2022-06-26 14:04 UTC, hfiguiere commented
There is also a build warning:
```
WARNING: Icon not matching app id in /srv/buildbot/worker/build-x86_64-2/build/builddir/export/share/applications/io.github.naikari.Naikari.desktop: naikari
WARNING: Icon referenced in desktop file but not exported: naikari
```

2022-06-26 16:26 UTC, Mailaender commented
bot, build io.github.naikari.Naikari

2022-07-01 10:53 UTC, Mailaender commented
bot, build io.github.naikari.Naikari

2022-07-01 19:51 UTC, barthalion commented
/merge @onpon4

2022-07-01 19:52 UTC, closed without merging