com.giuspen.cherrytree -> net.giuspen.cherrytree
flathub/flathub pull request #3299
Opened 2022-06-29 21:27 UTC by giuspen

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-06-29 23:27 UTC, hfiguiere commented
bot, build net.giuspen.cherrytree

2022-06-29 23:28 UTC, hfiguiere requested changes

2022-06-29 23:28 UTC, hfiguiere commented on net.giuspen.cherrytree.json
> +            "buildsystem": "cmake",
```suggestion
            "buildsystem": "cmake-ninja",
```

2022-06-29 23:28 UTC, hfiguiere commented on net.giuspen.cherrytree.json
> +            "buildsystem": "cmake",
```suggestion
            "buildsystem": "cmake-ninja",
```

2022-06-29 23:28 UTC, hfiguiere commented on net.giuspen.cherrytree.json
> +            "buildsystem": "cmake",
```suggestion
            "buildsystem": "cmake-ninja",
```

2022-06-29 23:28 UTC, hfiguiere commented on net.giuspen.cherrytree.json
> +        "--filesystem=host",
that is a very broad filesystem permission

2022-06-29 23:28 UTC, hfiguiere commented on net.giuspen.cherrytree.json
> +        "--socket=x11",
does it support wayland?

2022-06-29 23:42 UTC, hfiguiere commented
what's the relation with https://flathub.org/apps/details/com.giuspen.cherrytree

2022-06-30 09:41 UTC, barthalion commented
bot, build net.giuspen.cherrytree

2022-06-30 10:01 UTC, hfiguiere commented
> what's the relation with https://flathub.org/apps/details/com.giuspen.cherrytree

Still that question is unanswered.

2022-06-30 10:14 UTC, barthalion commented
It's obviously a rename due to domain change.

2022-06-30 10:17 UTC, hfiguiere commented
it's not specified in the submission where there is the question acknowledged by the OP. Hence my question.

2022-06-30 12:01 UTC, barthalion commented
@giuspen Please remember to mark the old ID as EOL: https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

/merge

2022-06-30 12:02 UTC, closed without merging

2022-06-30 17:42 UTC, giuspen commented
Thanks @barthalion I will mark the old ID to EOL. @hfiguiere yes it is a rename due to domain change.