Add OpenRSC Launcher
flathub/flathub pull request #3304
Opened 2022-06-30 18:41 UTC by dginovker

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
Additional patches have been submitted upstream, but upstream is pretty stable and doesn't merge often. Will remove from here and fetch from upstream once they merge

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-06-30 18:58 UTC, nedrichards commented
bot, build vet.rsc.OpenRSC.Launcher

2022-06-30 19:00 UTC, nedrichards commented on vet.rsc.OpenRSC.Launcher.appdata.xml
> +    <id>vet.rsc.OpenRSC.Launcher.desktop</id>
it'd be best if you removed the .desktop here (per the recommendations https://github.com/flathub/flathub/wiki/AppData-Guidelines#id ) and instead included that path (with the .desktop) as a launchable https://github.com/flathub/flathub/wiki/AppData-Guidelines#Launchable

2022-06-30 19:10 UTC, dginovker commented on vet.rsc.OpenRSC.Launcher.appdata.xml
> +    <project_license>AGPLv3</project_license>
Buildbot is failing since AGPLv3 is not a license. Where can I see the valid licenses? (Upstream is AGPL v3)

2022-06-30 19:17 UTC, dginovker commented on vet.rsc.OpenRSC.Launcher.appdata.xml
> +    <project_license>AGPLv3</project_license>
https://spdx.org/licenses/

2022-06-30 19:22 UTC, dginovker commented
bot, build vet.rsc.OpenRSC.Launcher

2022-06-30 23:33 UTC, hfiguiere requested changes

2022-06-30 23:33 UTC, hfiguiere commented on vet.rsc.OpenRSC.Launcher.json
> +                "install -Dm644 vet.rsc.OpenRSC.Launcher.svg /app/share/icons/hicolor/48x48/apps/vet.rsc.OpenRSC.Launcher.svg",
```suggestion
                "install -Dm644 vet.rsc.OpenRSC.Launcher.svg /app/share/icons/hicolor/scalable/apps/vet.rsc.OpenRSC.Launcher.svg",
```

svg is definitely not fixed size.

2022-07-01 01:31 UTC, dginovker commented
bot, build vet.rsc.OpenRSC.Launcher

2022-07-01 01:43 UTC, dginovker commented
Works as expected :+1:

2022-07-01 08:35 UTC, nedrichards commented
/merge

2022-07-01 08:37 UTC, closed without merging