Add org.fcitx.Fcitx5.Addon.Chewing
flathub/flathub pull request #3311
Opened 2022-07-03 22:35 UTC by wengxt

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-07-03 22:36 UTC, wengxt commented
bot, build org.fcitx.Fcitx5.Addon.Chewing

2022-07-04 00:40 UTC, hfiguiere requested changes

2022-07-04 00:40 UTC, hfiguiere commented on org.fcitx.Fcitx5.Addon.Chewing.yaml
> +        branch: v0.5.1
you need a tag or commit. not a branch.

2022-07-05 19:40 UTC, nedrichards commented
bot, build org.fcitx.Fcitx5.Addon.Chewing

2022-07-05 19:42 UTC, nedrichards commented
Do you need the same collaborators on this PR (and https://github.com/flathub/flathub/pull/3310) as you have on the existing fctix extensions and system?

2022-07-06 06:59 UTC, barthalion commented
/merge

2022-07-06 07:00 UTC, closed without merging