Create com.adilhanney.timing.timing_flutter.json
flathub/flathub pull request #3317
Opened 2022-07-05 17:17 UTC by adil192

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  <s>If not, the unredistributable parts are using an extra-data source type.</s>
- [x] I am an upstream contributor to the project. <s>If not, I contacted upstream developers about submitting their software to Flathub. **Link:**</s>
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-07-05 17:24 UTC, hfiguiere requested changes

2022-07-05 17:24 UTC, hfiguiere commented on com.adilhanney.timing.timing_flutter.json
> +        "cp com.adilhanney.timing.timing_flutter.metainfo.xml /app/share/metainfo/",
```suggestion
        "install -Dm644 com.adilhanney.timing.timing_flutter.metainfo.xml -t /app/share/metainfo/",
```

2022-07-05 17:24 UTC, hfiguiere commented on com.adilhanney.timing.timing_flutter.json
> +        "cp icon.svg /app/share/icons/hicolor/scalable/apps/com.adilhanney.timing.timing_flutter.svg",
```suggestion
        "install -Dm644 icon.svg -t /app/share/icons/hicolor/scalable/apps/com.adilhanney.timing.timing_flutter.svg",
```

2022-07-05 17:24 UTC, hfiguiere commented on com.adilhanney.timing.timing_flutter.json
> +        "cp com.adilhanney.timing.timing_flutter.metainfo.xml /app/share/appdata/"
```suggestion
        "install -Dm644 com.adilhanney.timing.timing_flutter.desktop -t /app/share/applications/"
```

2022-07-05 17:26 UTC, hfiguiere commented
bot, build com.adilhanney.timing.timing_flutter

2022-07-05 17:28 UTC, hfiguiere commented on com.adilhanney.timing.timing_flutter.json
> +  "app-id": "com.adilhanney.timing.timing_flutter",
I would just use `com.adilhanney.timing` (granted that the domain is actually yours). But the website at the github repo point to https://adil.hanney.org/timing_flutter/

2022-07-05 19:43 UTC, nedrichards commented
bot, build com.adilhanney.timing

2022-07-05 20:19 UTC, adil192 commented
bot, build com.adilhanney.timing

2022-07-06 06:58 UTC, barthalion commented
/merge

2022-07-06 06:59 UTC, closed without merging