Add com.rocksandpaper.syndic
flathub/flathub pull request #3393
Opened 2022-08-06 02:30 UTC by cscarney

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

I am the upstream maintainer, everything is redistributable under GPL-3.  The only permissions beyond the basic ones are for status notifications while running in the background.

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-08-06 02:33 UTC, hfiguiere commented
bot, build com.rocksandpaper.syndic

2022-08-06 02:33 UTC, hfiguiere requested changes

2022-08-06 02:33 UTC, hfiguiere commented on com.rocksandpaper.syndic.yml
> +- --socket=x11
```suggestion
- --socket=fallback-x11
```

if it actually support wayland.

2022-08-08 10:45 UTC, barthalion commented
bot, build com.rocksandpaper.syndic

2022-08-08 12:26 UTC, closed without merging