Add files
flathub/flathub pull request #3491
Opened 2022-09-09 20:52 UTC by jonri

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
> `--filesystem=host # we need read/write access to the game engine directory, which may be in any location`
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. [**Link: forum request**](https://forums.thedarkmod.com/index.php?/topic/21478-darkradiant-install-with-flatpak-linux/)
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
> *Domain is owned by another team member.*
- [x] Any additional patches or files have been submitted to the upstream projects concerned. 
> *Will commit appstream file in next released version.*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-09-09 21:00 UTC, hfiguiere requested changes

2022-09-09 21:00 UTC, hfiguiere commented on net.darkradiant.DarkRadiant.yml
> +cleanup:
all these are usually above modules.

2022-09-09 21:00 UTC, hfiguiere commented on net.darkradiant.DarkRadiant.yml
> +  - --filesystem=host # we need read/write access to the game engine directory, which may be in any location
that remain extremely broad filesystem permissions

2022-09-09 21:00 UTC, hfiguiere commented on net.darkradiant.DarkRadiant.yml
> +#  - --socket=fallback-x11
```suggestion
```

2022-09-09 21:01 UTC, hfiguiere commented
bot, build net.darkradiant.DarkRadiant

2022-09-09 21:02 UTC, hfiguiere requested changes

2022-09-09 21:02 UTC, hfiguiere commented on net.darkradiant.DarkRadiant.yml
> +      - install -Dm644 ${FLATPAK_DEST}/share/darkradiant/bitmaps/darkradiant_icon_64x64.png ${FLATPAK_DEST}/share/icons/hicolor/64x64/apps/${FLATPAK_ID}.png
128x128 at least is required.

2022-09-09 22:04 UTC, hfiguiere commented
build failure
```
builddir/files/share/appdata/net.darkradiant.DarkRadiant.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• style-invalid         : Not enough <screenshot> tags, minimum is 1
Validation of files failed
```

2022-09-13 13:13 UTC, jonri commented
bot, build net.darkradiant.DarkRadiant

2022-09-15 04:46 UTC, barthalion commented
/merge

2022-09-15 04:47 UTC, closed without merging