ml.mdwalters.EightBall
flathub/flathub pull request #3501
Opened 2022-09-13 19:48 UTC by mdwalters

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-09-13 22:34 UTC, hfiguiere commented
this PR is supposed to be against `new-pr`

2022-09-13 22:35 UTC, hfiguiere commented on ml.mdwalters.EightBall.json
> +                    "url" : "file:///home/ubuntu/Projects/eight-ball"
it will definitely not find the source code.

2022-09-13 22:35 UTC, hfiguiere commented on ml.mdwalters.EightBall.json
> +    }
```suggestion
    ]
```

2022-09-13 22:35 UTC, hfiguiere commented on ml.mdwalters.EightBall.appdata.xml
> +</component>
this is insufficient

2022-09-13 22:35 UTC, hfiguiere commented on ml.mdwalters.EightBall.appdata.xml
> +	<id>ml.mdwalters.EightBall.desktop</id>
```suggestion
	<id>ml.mdwalters.EightBall</id>
```

2022-09-14 02:21 UTC, hfiguiere commented on ml.mdwalters.EightBall.appdata.xml
> +</component>
this is not resolved.

2022-09-14 02:22 UTC, hfiguiere requested changes

2022-09-14 02:22 UTC, hfiguiere commented on ml.mdwalters.EightBall.json
> +                    "url" : "file:///home/ubuntu/Projects/eight-ball"
this is not resolved.

2022-09-15 00:12 UTC, hfiguiere commented on ml.mdwalters.EightBall.json
> +                    "url" : "https://github.com/mdwalters/eight-ball"
you need a revision or tag here.

2022-09-15 00:13 UTC, hfiguiere commented on ml.mdwalters.EightBall.appdata.xml
> +	</description>
as I previously said, this appstream file not sufficient...

missing `releases`, `screenshots`, `url`, `content_rating`

2022-09-15 00:15 UTC, hfiguiere commented on ml.mdwalters.EightBall.json
> +                }
upstream repository already containt desktop file, appstream and icon. They are not necessary in the repository.

2022-09-15 00:17 UTC, hfiguiere commented
bot, build ml.mdwalters.EightBall

2022-09-15 04:26 UTC, mdwalters commented on ml.mdwalters.EightBall.json
> +                    "url" : "https://github.com/mdwalters/eight-ball"
how would i add that?

2022-09-15 21:39 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-16 05:41 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-16 20:47 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-16 21:06 UTC, mdwalters commented
why won't it work?

2022-09-16 21:07 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-16 21:16 UTC, hfiguiere commented
```
builddir/files/share/appdata/ml.mdwalters.EightBall.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• style-invalid         : Not enough <screenshot> tags, minimum is 1
• tag-missing           : <release> required
• tag-missing           : <url> is not present
Validation of files failed
```

2022-09-16 21:17 UTC, hfiguiere commented on ml.mdwalters.EightBall.appdata.xml
> +	</description>
still not done

2022-09-16 21:17 UTC, hfiguiere commented on ml.mdwalters.EightBall.desktop
> +[Desktop Entry]
this is upstream too, remove this from here.

2022-09-16 21:17 UTC, hfiguiere commented on ml.mdwalters.EightBall.appdata.xml
> +	</description>
but it should actually be removed from here it's upstream.

2022-09-16 21:18 UTC, hfiguiere commented on ml.mdwalters.EightBall.json
> +                        "type" : "gnome",
I doubt his is valid since the tarball isn't hosted on gnome.

2022-09-16 21:25 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-16 21:29 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-16 21:30 UTC, hfiguiere commented
it will not magically fix by itself. I already commented one what needed to be done. Either a patch or upstream.

2022-09-16 22:51 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-16 23:55 UTC, hfiguiere commented
```
ml.mdwalters.EightBall:            AppData problem: tag-invalid : Expected children for tag
ml.mdwalters.EightBall:            AppData problem: tag-invalid : <url> type invalid [unknown]
```

2022-09-17 03:00 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-17 03:13 UTC, mdwalters commented
uh...

2022-09-24 21:50 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-24 22:12 UTC, hfiguiere commented
```
builddir/files/share/appdata/ml.mdwalters.EightBall.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• attribute-missing     : <release> has no timestamp
Validation of files failed
```

2022-09-25 14:08 UTC, barthalion commented
bot, build ml.mdwalters.EightBall

2022-09-25 14:24 UTC, hfiguiere commented
stll happening.
```
builddir/files/share/appdata/ml.mdwalters.EightBall.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• attribute-missing     : <release> has no timestamp
Validation of files failed
```

2022-09-26 05:17 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-26 05:39 UTC, mdwalters commented
i think this time it'll work

2022-09-26 05:39 UTC, mdwalters commented
bot, build ml.mdwalters.EightBall

2022-09-26 05:48 UTC, mdwalters commented
YES!

2022-09-27 08:24 UTC, barthalion commented
/merge

2022-09-27 08:25 UTC, closed without merging