Add org.kde.kmahjongg
flathub/flathub pull request #3511
Opened 2022-09-19 08:49 UTC by cho2

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of [permissions](https://invent.kde.org/packaging/flatpak-kde-applications/-/blob/master/org.kde.kmahjongg.json#L10). 
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. 
  - I am a member of [KDE Team on Flathub](https://github.com/orgs/flathub/teams/kde/members).
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
  - KDE project owns the domain
- [x] Any additional patches or files have been submitted to the upstream projects concerned. 
  - n/a

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-09-19 08:49 UTC, cho2 commented
bot, build org.kde.kmahjongg

2022-09-19 09:02 UTC, JakobDev commented on org.kde.kmahjongg.json
> +        "--socket=fallback-x11",
```suggestion
        "--socket=wayland",
        "--socket=fallback-x11",
```

`--socket=fallback-x11` is enough

2022-09-19 09:05 UTC, cho2 commented
cc @flathub/kde

2022-09-19 09:29 UTC, travier commented
Manifest LGTM with the same comment as above. Not tested yet.

2022-09-19 09:34 UTC, hfiguiere requested changes

2022-09-19 09:37 UTC, JakobDev commented on org.kde.kmahjongg.json
> +    "runtime-version": "5.15-21.08",
The KDE team wants to use 5.15-21.08 at the moment. [Source](https://github.com/flathub/org.kde.okular/pull/197#issuecomment-1240694420)

2022-09-19 09:46 UTC, travier commented on org.kde.kmahjongg.json
> +    "runtime-version": "5.15-21.08",
Yes, please do not use the runtime before we've announced it

2022-09-19 09:46 UTC, travier commented on org.kde.kmahjongg.json
> +    "runtime-version": "5.15-21.08",
I'm trying to test it a bit more before we announce it and convert all apps to it

2022-09-19 20:44 UTC, tsdgeos commented
App seems to work fine

2022-09-20 13:54 UTC, barthalion commented
/merge

2022-09-20 13:56 UTC, closed without merging