Add dev.jonmagon.kdiskmark
flathub/flathub pull request #3513
Opened 2022-09-19 16:12 UTC by JonMagon

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions.
- **`--filesystem=host`: Since this is a benchmarking application, it needs access to write to almost every mount point, including external storage devices.**
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- **Technically, the domain is not registered anywhere. The same namespace for DBus is used, reserved in SUSE.**
- [x] Any additional patches or files have been submitted to the upstream projects concerned.
- **The `legacy` branch is used for the sandboxed packages build. Since the `master` uses Polkit, it cannot be used here.**

Requested by issues: https://github.com/JonMagon/KDiskMark/issues/34, https://github.com/JonMagon/KDiskMark/issues/98

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-09-19 16:16 UTC, hfiguiere commented
> * Technically, the domain is not registered anywhere. The same namespace for DBus is used, reserved in SUSE.

Then the app-id doesn't meet the requirements.

2022-09-19 16:18 UTC, JonMagon commented
> Then the app-id doesn't meet the requirements.

Maybe I misunderstood something, what *domain* are we talking about?

2022-09-19 16:19 UTC, hfiguiere requested changes

2022-09-19 16:19 UTC, hfiguiere commented on dev.jonmagon.kdiskmark.yaml
> +  - --socket=wayland
```suggestion
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
```

2022-09-19 16:19 UTC, hfiguiere commented on dev.jonmagon.kdiskmark.yaml
> +        buildsystem: simple
this should be `autotools`

2022-09-19 16:19 UTC, hfiguiere commented on dev.jonmagon.kdiskmark.yaml
> +                type: git
```suggestion
                x-checker-data:
                    type: git
```

it's yaml, indentation is significant.

2022-09-19 16:19 UTC, hfiguiere commented on dev.jonmagon.kdiskmark.yaml
> +app-id: dev.jonmagon.kdiskmark
as said earlier if the domain isn't registered then this doesn't meet the requirements.

2022-09-19 16:20 UTC, hfiguiere commented
bot, build dev.jonmagon.kdiskmark

2022-09-19 16:22 UTC, hfiguiere commented
not appstream file is found.

2022-09-19 19:20 UTC, JonMagon commented
bot, build io.github.jonmagon.kdiskmark

2022-09-19 19:26 UTC, JonMagon commented
fio has go away

2022-09-19 19:33 UTC, JonMagon commented
bot, build io.github.jonmagon.kdiskmark

2022-09-19 19:36 UTC, JonMagon commented
```
ERROR   src.manifest: Failed to check git libaio/libaio.git with GitChecker: https://pagure.io/libaio.git has no tags matching '^(?:[vV])?((?:\d+\.)+\d+)$': list index out of range
ERROR   src.manifest: Failed to check git fio/fio.git with GitChecker: https://github.com/axboe/fio.git has no tags matching '^(?:[vV])?((?:\d+\.)+\d+)$': list index out of range
```
What could be wrong?

2022-09-19 19:40 UTC, hfiguiere commented
This:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/114441/191101584-c7c03b41-a1ac-4599-a21c-8213143045ee.png">

2022-09-19 19:52 UTC, hfiguiere commented
no.

2022-09-19 20:06 UTC, JonMagon commented
bot, build io.github.jonmagon.kdiskmark

2022-09-19 21:04 UTC, hfiguiere commented on io.github.jonmagon.kdiskmark.yaml
> +  - --device=dri
you probably need to ensure you allow the dbus name, unless it got changed too to match the app-id.

2022-09-19 21:04 UTC, hfiguiere commented on io.github.jonmagon.kdiskmark.yaml
> +      - -DCMAKE_BUILD_TYPE=Release
```suggestion
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

This will allow to have debug symbols.

2022-09-20 14:00 UTC, closed without merging

2022-09-20 17:55 UTC, JonMagon commented
It was merged, but I still can't use the built flatpak. The problem is in fio: `flatpak run --command=sh io.github.jonmagon.kdiskmark -c '/app/bin/fio'` does nothing. Probably need to add `config-opts: [ "--disable-native" ]`. PR is closed, how can I trigger yet another test build?
```bash
 %  ~  gdb ./fio                                                                                                                                                                                                                                    Вт 20 сен 2022 20:33:01
GNU gdb (GDB; openSUSE Tumbleweed) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./fio...
Missing separate debuginfo for /home/jonmagon/fio
Try: zypper install -C "debuginfo(build-id)=c096b7c83e14f63d37f448770f27568ca544f58f"
(No debugging symbols found in ./fio)
(gdb) r
Starting program: /home/jonmagon/fio 
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.36-4.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000555555572530 in ?? ()
Missing separate debuginfos, use: zypper install krb5-debuginfo-1.20-1.2.x86_64 libaio1-debuginfo-0.3.113-1.2.x86_64 libbrotlicommon1-debuginfo-1.0.9-1.10.x86_64 libbrotlidec1-debuginfo-1.0.9-1.10.x86_64 libcom_err2-debuginfo-1.46.5-3.1.x86_64 libcurl4-debuginfo-7.85.0-1.1.x86_64 libidn2-0-debuginfo-2.3.3-1.2.x86_64 libkeyutils1-debuginfo-1.6.3-4.3.x86_64 libldap2-debuginfo-2.6.3-1.2.x86_64 libnghttp2-14-debuginfo-1.49.0-1.2.x86_64 libopenssl1_1-debuginfo-1.1.1q-1.3.x86_64 libpcre2-8-0-debuginfo-10.40-3.3.x86_64 libpsl5-debuginfo-0.21.1-1.13.x86_64 libsasl2-3-debuginfo-2.1.28-1.6.x86_64 libselinux1-debuginfo-3.4-2.3.x86_64 libssh4-debuginfo-0.10.4-1.1.x86_64 libunistring2-debuginfo-1.0-1.4.x86_64 libz1-debuginfo-1.2.12-1.1.x86_64 libzstd1-debuginfo-1.5.2-1.9.x86_64
```