Add com.github.mrquantumoff.mcmodpackmanager
flathub/flathub pull request #3585
Opened 2022-10-14 09:16 UTC by mrquantumoff

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-10-14 11:57 UTC, JakobDev commented
App IDs that starts with `com.github` are no longer allowed. Please use `io.github` instead

2022-10-14 13:29 UTC, mrquantumoff commented
> App IDs that starts with `com.github` are no longer allowed. Please use `io.github` instead

Fixed it

2022-10-14 13:39 UTC, hfiguiere requested changes

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +branch: "master"
```suggestion
```

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +finish-args:
finish args is usuall above modules toward the begining of the manifest.

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +  - --socket=wayland
why do you need both?

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +  - --socket=system-bus
no system bus allowed. You need to figure out which dbus name you need to access.

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - '*.tar.gz'
there is no tar.gz installed.

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - ar -vox minecraft-modpack-manager_2.4.3_amd64.deb
why no building from source?

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +runtime: org.gnome.Platform
do you really the GNOME runtime? Also 43 is out.

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - install -Dm755 -t /app/bin usr/bin/minecraft-modpack-manager
having `/app/usr` will be a source of problem. this should be avoided.

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - install -D usr/share/icons/hicolor/500x500/apps/minecraft-modpack-manager.png /app/share/icons/hicolor/500x500/apps/io.github.mrquantumoff.mcmodpackmanager.png
500x500 isn't a valid icon size

2022-10-14 13:39 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - cat desktopfile.desktop
```suggestion
```

2022-10-14 13:40 UTC, hfiguiere commented
has the .destkop file and appdata been submitted upstream? Such an app without a desktop file in the upstream package it's a bug.

2022-10-14 13:41 UTC, hfiguiere commented
I know the linter will fail

bot, build io.github.mrquantumoff.mcmodpackmanager

2022-10-14 13:42 UTC, JakobDev commented on io.github.mrquantumoff.mcmodpackmanager.metainfo.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Your AppStream is missing Screenshots

2022-10-14 13:45 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +  - --socket=wayland
before suggesting this, the right question is "does it support wayland?"

2022-10-14 13:46 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - install -Dm755 -t /app/bin usr/bin/minecraft-modpack-manager
nevermimd I misread this line.

2022-10-14 13:48 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - install -D usr/share/icons/hicolor/256x256/apps/io.mrquantumoff.mcmodpackmanager.png  /app/share/icons/hicolor/256x256/apps/io.github.mrquantumoff.mcmodpackmanager.png
are you sure it's the right file name ? (the build fail because of that)

2022-10-14 13:48 UTC, hfiguiere commented on desktopfile.desktop
> +[Desktop Entry]
not sure why the empty lines, but it's purely cosmetic

2022-10-14 13:49 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.metainfo.xml
> +<launchable type="desktop-id">io.github.mrquantumoff.mcmodpackmanager.desktop</launchable>
missing `content_rating`.

2022-10-14 13:51 UTC, hfiguiere commented
> has the .destkop file and appdata been submitted upstream? Such an app without a desktop file in the upstream package it's a bug.

Both are in the archive, therefor they should be used and the one in this submission should be removed. Patch as necessary (and submit the changes upstream)

2022-10-14 14:19 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +  - --filesystem=home
why is "home" access needed?

2022-10-14 14:43 UTC, hfiguiere commented
in both situation, the upstream shipped files should be used and patched as needed.

2022-10-14 15:29 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - ar -vox minecraft-modpack-manager_2.4.3_amd64.deb
nor why you are not building from source.

2022-10-14 15:30 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +      - '*.tar.gz'
```suggestion
```

2022-10-14 15:44 UTC, hfiguiere commented on io.github.mrquantumoff.mcmodpackmanager.yml
> +        path: io.github.mrquantumoff.mcmodpackmanager.metainfo.xml
this file is shipped too in the tarball.

2022-10-14 19:50 UTC, mrquantumoff commented
bot, build io.github.mrquantumoff.mcmodpackmanager

2022-10-14 19:57 UTC, mrquantumoff commented
bot, build

2022-10-14 19:57 UTC, mrquantumoff commented
bot, build io.github.mrquantumoff.mcmodpackmanager.

2022-10-14 19:58 UTC, mrquantumoff commented
bot, build io.github.mrquantumoff.mcmodpackmanager

2022-10-15 14:23 UTC, hfiguiere commented
Several **important** questions unanswered (just marked as resolved)

2022-10-15 20:39 UTC, mrquantumoff commented
> Several **important** questions unanswered (just marked as resolved)

I just answered to some of them, please let me know if there is anything else you that want to know

2022-10-15 21:13 UTC, hfiguiere commented
I see no answer here.

2022-10-15 21:40 UTC, mrquantumoff commented
Can you please elaborate on what you are referring to as "here"?

2022-10-15 22:04 UTC, hfiguiere commented
![image](https://user-images.githubusercontent.com/114441/196009265-44ec7009-13ae-49ab-890f-e81abbc0f9db.png)

![image](https://user-images.githubusercontent.com/114441/196009279-c877edbe-1cc5-4a6a-b578-2842c6b512f2.png)

![image](https://user-images.githubusercontent.com/114441/196009288-3cbcecb5-4bfe-4b8e-a4e1-851b87be7c5e.png)

![image](https://user-images.githubusercontent.com/114441/196009296-ed768fb6-0556-440f-b9a4-884c2b04181d.png)

Three of them marked as resolved without any answer.

2022-10-16 06:19 UTC, mrquantumoff commented
Strange, I answered those questions but there is a label saying "Pending" near them

2022-10-16 06:30 UTC, mrquantumoff commented
> ![image](https://user-images.githubusercontent.com/114441/196009265-44ec7009-13ae-49ab-890f-e81abbc0f9db.png)
> 
> ![image](https://user-images.githubusercontent.com/114441/196009279-c877edbe-1cc5-4a6a-b578-2842c6b512f2.png)
> 
> ![image](https://user-images.githubusercontent.com/114441/196009288-3cbcecb5-4bfe-4b8e-a4e1-851b87be7c5e.png)
> 
> ![image](https://user-images.githubusercontent.com/114441/196009296-ed768fb6-0556-440f-b9a4-884c2b04181d.png)
> 
> Three of them marked as resolved without any answer.

![image](https://user-images.githubusercontent.com/36820091/196021460-339eab4f-cf2e-462f-bcfb-92f42bf59ece.png)

I'm not building from source, because I don't want to setup one more CI/CD and also the build process is using many build dependencies such as webkitgtk, node js, rust, cargo etc. It's also easier to package the app from .deb, because deb package also has auto-updater disabled by the framework. 

I need home access to modify many files in ~/.minecraft folder and user might need it to select a .mcmodpackref file to install a modpack from the web and I'm sure not so everyone knows about apps like flatseal and/or remember cli apps to modify permissions.

![image](https://user-images.githubusercontent.com/36820091/196021628-23a20935-2d9f-453f-a4d5-a62bce1a82f9.png)

2022-10-16 23:05 UTC, barthalion commented on io.github.mrquantumoff.mcmodpackmanager.metainfo.xml
> +<p>I had a struggle with managing modpacks, so I made an app that does the job!</p>
This description should really be improved.

2022-10-17 20:01 UTC, mrquantumoff commented
bot, build io.github.mrquantumoff.mcmodpackmanager

2022-10-21 06:50 UTC, barthalion commented
/merge

2022-10-21 06:51 UTC, closed without merging