Add OceanPop
flathub/flathub pull request #3635
Opened 2022-11-10 10:19 UTC by sharkwouter

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

I'd like to add an open source puzzle game called OceanPop to the Flathub. I developed this game over the course of about half a year and I think I managed to make quite a polished release out of it. It should build for all platforms the Flathub supports.

I had to use the `--device=all` permission to get gamepads to work unfortunately.

2022-11-10 13:14 UTC, barthalion commented on io.github.sharkwouter.OceanPop.yaml
> +runtime-version: '21.08'
```suggestion
runtime-version: '22.08'
```

2022-11-10 13:15 UTC, barthalion commented
bot, build io.github.sharkwouter.OceanPop

2022-11-10 13:27 UTC, hfiguiere requested changes
Build fail because
```
error: /srv/buildbot/worker/build-x86_64-6/build/builddir/export/share/icons/hicolor/128x128/apps/io.github.sharkwouter.OceanPop.png is not a valid icon: Expected a square icon but got: 128x127
```

The icon is supposed to be square, and appstream enforce this.

2022-11-10 13:27 UTC, hfiguiere commented on io.github.sharkwouter.OceanPop.yaml
> +    buildsystem: cmake
```suggestion
    buildsystem: cmake-ninja
```

2022-11-10 13:41 UTC, sharkwouter commented
bot, build io.github.sharkwouter.OceanPop

2022-11-10 13:42 UTC, sharkwouter commented
I had no idea the icon was 1 pixel off, that was not intended. I fixed it and created a new tag with the fix.

2022-11-10 13:54 UTC, sharkwouter commented
bot, build io.github.sharkwouter.OceanPop

2022-11-10 14:26 UTC, sharkwouter commented
bot, build io.github.sharkwouter.OceanPop

2022-11-10 14:30 UTC, closed without merging

2022-11-10 14:31 UTC, sharkwouter commented
Closing in favor of #3636

2022-11-10 14:32 UTC, hfiguiere commented
WHY? it makes review harder

2022-11-10 14:43 UTC, sharkwouter commented
I wanted to change the id from io.github.sharkwouter.OceanPop to io.github.sharkwouter.oceanpop, which requires a new branch. Sorry about that. It should finally work now.

2022-11-10 15:02 UTC, hfiguiere commented
not it doesn't require a new branch. branch name is irrelevant.

2022-11-10 15:30 UTC, sharkwouter commented
Oh, I see

2022-11-11 13:11 UTC, sharkwouter commented
Turns out I cannot actually reopen this issue, since I did a force push. I'm sorry :(

2022-11-11 20:08 UTC, barthalion commented
Yeah, you need to open a new PR. This is unfortunately how GitHub works.