Add org.eu.wabarc.wayback
flathub/flathub pull request #3644
Opened 2022-11-14 05:41 UTC by waybackarchiver

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

Related conversations https://github.com/flathub/flathub/pull/3641

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-11-14 13:22 UTC, hfiguiere requested changes

2022-11-14 13:22 UTC, hfiguiere commented on org.eu.wabarc.wayback.appdata.xml
> +  </releases>
still missing mandatory screenshots.

2022-11-14 13:22 UTC, hfiguiere commented on org.eu.wabarc.wayback.yml
> +        tar -xvf wayback-linux-*-${version}.tar.gz
what happened to building from source?

2022-11-14 15:00 UTC, hfiguiere commented on org.eu.wabarc.wayback.yml
> +          - x86_64
this doesn't do what you think it does.

there still will be (an attempt) to build an aarch64 flatpak.

2022-11-14 15:02 UTC, hfiguiere commented on org.eu.wabarc.wayback.yml
> -          - aarch
this is not what i meant by "invalid arch".

The proper arch id for ARM v8 64-bits is `aarch64`.

2022-11-16 09:21 UTC, barthalion commented on org.eu.wabarc.wayback.appdata.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I recommend moving appdata, desktop and icon files to your upstream repo and distribute them in the tarball this gets build from.

2022-11-16 09:22 UTC, barthalion commented
bot, build org.eu.wabarc.wayback

2022-11-16 09:45 UTC, barthalion commented
I noticed it ships a desktop file but it doesn't actually have any UI? You should change the type in your metainfo file to `console-application` and avoid installing the desktop file at all.

2022-11-18 23:32 UTC, hfiguiere commented on org.eu.wabarc.wayback.yml
> +        mkdir -p /app/share/applications
```suggestion
```

This is not necessary. `install -D` will do it for you

2022-11-27 17:23 UTC, barthalion commented
bot, build org.eu.wabarc.wayback

2022-11-27 18:25 UTC, hfiguiere commented on org.eu.wabarc.wayback.yml
> +      - install -Dm755 -t /app/bin wayback
there is an inconsistency in the path here. line 16 `wayback` doesn't exist, but `mv` expect a directory.
line 17 `wayback` is expected to be a file

2022-11-29 07:54 UTC, barthalion commented
bot, build org.eu.wabarc.wayback

2022-11-29 07:56 UTC, barthalion commented
Please also add a file named `flathub.json` with the following content:

```
{
  "skip-icons-check": true
}
```

2022-12-02 07:47 UTC, barthalion commented
bot, build org.eu.wabarc.wayback

2022-12-02 07:50 UTC, barthalion commented
/merge

2022-12-02 07:51 UTC, closed without merging