add io.github.hrkfdn.ncspot
flathub/flathub pull request #3681
Opened 2022-11-26 23:58 UTC by thorpelawrence

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*
  - `.desktop` file patch not upstreamed, only applicable to Flatpak which is renamed from upstream

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-11-27 01:04 UTC, hfiguiere requested changes

2022-11-27 01:04 UTC, hfiguiere commented on desktop-icon.patch
> +diff --git a/misc/ncspot.desktop b/misc/ncspot.desktop
no need for a patch. you can just use `desktop-file-edit`

`rename-icon` also take care of it but you don't use it here.

2022-11-27 01:04 UTC, hfiguiere commented on io.github.hrkfdn.ncspot.appdata.xml
> +  </releases>
missing required `content_rating`

2022-11-27 01:04 UTC, hfiguiere commented on io.github.hrkfdn.ncspot.yml
> +build-options:
build-options and finish-args usually come before the modules.

2022-11-27 01:04 UTC, hfiguiere commented on io.github.hrkfdn.ncspot.yml
> +  - --socket=fallback-x11
`--share=ipc` is also required for X11.

2022-11-27 01:05 UTC, hfiguiere commented
bot, build io.github.hrkfdn.ncspot

2022-11-27 01:05 UTC, hfiguiere commented on io.github.hrkfdn.ncspot.yml
> +      - cargo-sources.json
this file is actually missing.

2022-11-27 11:09 UTC, thorpelawrence commented
bot, build io.github.hrkfdn.ncspot

2022-11-27 11:20 UTC, thorpelawrence commented
bot, build io.github.hrkfdn.ncspot

2022-12-05 23:35 UTC, hfiguiere requested changes

2022-12-05 23:35 UTC, hfiguiere commented on io.github.hrkfdn.ncspot.appdata.xml
> +  <summary>Cross-platform ncurses Spotify client written in Rust</summary>
```suggestion
  <summary>Cross-platform ncurses Spotify client</summary>
```

This doesn't matter to users.

2022-12-05 23:35 UTC, hfiguiere commented on io.github.hrkfdn.ncspot.yml
> +    post-install:
```suggestion
```

2022-12-05 23:35 UTC, hfiguiere commented
bot, build io.github.hrkfdn.ncspot

2022-12-06 00:09 UTC, hfiguiere commented on io.github.hrkfdn.ncspot.appdata.xml
> +  <summary>Cross-platform ncurses Spotify client written in Rust</summary>
it actually has meaning for the end user as it qualifies the UI. Albeit "text based" or "terminal based" is probably more descriptive.

2022-12-12 10:15 UTC, barthalion commented
bot, build io.github.hrkfdn.ncspot

2022-12-12 10:27 UTC, thorpelawrence commented
> It doesn't launch from CLI:
> 
> ```
> ~ 15.2s ❱ flatpak run io.github.hrkfdn.ncspot
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Uncategorized, message: "No such device or address" }', /run/build/ncspot/cargo/vendor/cursive-0.20.0/src/cursive_ext.rs:70:36
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Works fine through the desktop file, though.

Interesting, I can't reproduce from the 11183 build - it launches for me through both methods

2022-12-12 10:54 UTC, barthalion commented
Hm, looks like something is wrong when I launch it inside the toolbox. LGTM, then.

/merge @hrkfdn

2022-12-12 10:56 UTC, closed without merging