Funkplot
flathub/flathub pull request #3684
Opened 2022-11-28 09:29 UTC by fritzone

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-11-28 15:42 UTC, hfiguiere requested changes

2022-11-28 15:43 UTC, hfiguiere commented on org.unafrog.funkplot.yml
> +app-id: org.unafrog.funkplot
There doesn't seem to be a domain `unaforg.org`. So this app-id doesn't meet the requirements.

2022-11-28 20:19 UTC, fritzone commented on org.unafrog.funkplot.yml
> +  - --socket=wayland
changed to `fallback-x11`

2022-11-28 20:20 UTC, fritzone commented on org.unafrog.funkplot.yml
> +      - "-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/app -DFLATPAK_BUILD=ON"
done

2022-11-28 20:20 UTC, fritzone commented on org.unafrog.funkplot.yml
> +    buildsystem: cmake
done

2022-11-28 20:21 UTC, hfiguiere commented
bot, build sh.funkplot.Funkplot

2022-11-28 21:30 UTC, hfiguiere commented
it's missing the required appstream file, and the .desktop and icons have to be renamed.

2022-11-28 21:33 UTC, hfiguiere commented on sh.funkplot.Funkplot.yml
> +  - --device=dri
also missing `cleanup` rules to remove files not needed at build time like the headers and the cmake files.

2022-11-28 21:34 UTC, hfiguiere commented on sh.funkplot.Funkplot.yml
> +  - --socket=fallback-x11
this won't work. I didn't say to remove the wayland socket if it support wayland. Nor to change to fallback-x11 if it doesn't.

2022-11-29 18:39 UTC, fritzone commented
Sorry, this is all new to me, I just used the example provided at https://docs.flatpak.org/en/latest/qt.html for Qt applications, tailored it to suit my needs and hoped that it will work out of the box. When I will have a bit more time I will invest some energy in properly creating a flatpak package.

2023-05-03 17:14 UTC, hfiguiere commented
bot, build sh.funkplot.Funkplot

2023-05-03 17:23 UTC, hfiguiere commented
> it's missing the required appstream file, and the .desktop and icons have to be renamed.

Whithout this the build will never be successful.

2024-12-05 01:08 UTC, closed without merging