KGraphViewer
flathub/flathub pull request #3701
Opened 2022-12-10 21:38 UTC by Mailaender

### Please confirm your submission meets all the criteria

- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** https://invent.kde.org/teams/flathub/issues/-/issues/14
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)* https://invent.kde.org/graphics/kgraphviewer/-/merge_requests/8 https://invent.kde.org/graphics/kgraphviewer/-/commit/c007946a889d6b27d4c0d68e9fb7dde99d95a368.patch

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2022-12-10 21:49 UTC, hfiguiere commented
cc @flathub/kde

2022-12-10 21:51 UTC, hfiguiere requested changes

2022-12-10 21:51 UTC, hfiguiere commented on org.kde.kgraphviewer.json
> +        "--socket=x11"
either X11 or wayland + fallback

2022-12-10 21:51 UTC, hfiguiere commented on org.kde.kgraphviewer.json
> +            "buildsystem": "cmake",
```suggestion
            "buildsystem": "cmake-ninja",
```

2022-12-10 21:51 UTC, hfiguiere commented on org.kde.kgraphviewer.json
> +                    "path": "logo.png"
was this issue submitted upstream?

2022-12-10 21:51 UTC, hfiguiere commented on org.kde.kgraphviewer.json
> +    "runtime-version": "5.15-21.08",
22.08 maybe?

2022-12-10 22:26 UTC, Mailaender commented on org.kde.kgraphviewer.json
> +                    "path": "logo.png"
Yes, see above.

2022-12-10 22:26 UTC, Mailaender commented on org.kde.kgraphviewer.json
> +    "runtime-version": "5.15-21.08",
I was told it is not ready yet.

2022-12-10 22:28 UTC, Mailaender commented
bot, build org.kde.kgraphviewer

2022-12-11 10:00 UTC, Mailaender commented
bot, build org.kde.kgraphviewer

2022-12-12 09:58 UTC, barthalion commented
/merge

2022-12-12 10:00 UTC, closed without merging