Add org.kde.plasmatube
flathub/flathub pull request #3912
Opened 2023-02-17 11:08 UTC by plata

### Please confirm your submission meets all the criteria

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2023-02-17 11:08 UTC, plata commented
CC @flathub/kde

2023-02-17 11:08 UTC, plata commented
bot, build org.kde.plasmatube

2023-02-17 11:10 UTC, plata commented
@lnj is this ok for you?

2023-02-17 11:24 UTC, plata commented
needs:
- https://github.com/flathub/shared-modules/pull/233
- https://github.com/flathub/shared-modules/pull/232

2023-02-17 12:55 UTC, hfiguiere commented
> needs:
> 
>     * [Add python3-yt-dlp shared-modules#233](https://github.com/flathub/shared-modules/pull/233)
> 
>     * [Add libmpv shared-modules#232](https://github.com/flathub/shared-modules/pull/232)

No.

Since they are not in shared-modules they should be in this manifest.

2023-02-17 13:58 UTC, plata commented
bot, build org.kde.plasmatube

2023-02-17 15:19 UTC, JakobDev commented
You might want to run `flatpak-pip-generator` with the `--checker-data` argument, so you will automatic get a PR when a new Version of yt-dlp is released.

2023-02-17 15:21 UTC, JakobDev commented on org.kde.plasmatube.json
> +                        "project-id": 326638,
This points to to [kasts](https://release-monitoring.org/project/326638/). It looks like Plsmatube is currently not monitored by Anitya.

2023-02-17 16:33 UTC, espidev commented on org.kde.plasmatube.json
> +                        "project-id": 326638,
```suggestion
                        "project-id": 328147,
```

2023-02-17 17:52 UTC, plata commented
@JakobDev I don't know if there was a specific reason to use that yt-dlp version. I don't think so but I would leave this to @lnj.

2023-02-17 22:43 UTC, JBBgameich commented
> I don't know if there was a specific reason to use that yt-dlp version. I don't think so but I would leave this to

There isn't, but if you want to stay in sync with the nightly flatpak, you could add something similar to what I am using for audiotube: https://github.com/flathub/org.kde.audiotube/blob/master/update-generated-sources.sh

2023-02-18 10:45 UTC, plata commented
bot, build org.kde.plasmatube

2023-02-18 10:49 UTC, plata commented
bot, build org.kde.plasmatube

2023-02-19 12:04 UTC, plata commented
@espidev @JBBgameich can you answer the open topics in the PR description?

2023-02-19 12:37 UTC, JBBgameich requested changes
There are two unused permissions, after removing these only the minimal set that is required is left.

2023-02-19 12:37 UTC, JBBgameich commented on org.kde.plasmatube.json
> +        "--filesystem=home",
This shouldn't be necessary

2023-02-19 12:37 UTC, JBBgameich commented on org.kde.plasmatube.json
> +        "--talk-name=org.freedesktop.Notifications"
This shouldn't be necessary

2023-02-19 12:42 UTC, JBBgameich commented
> - [x] All assets referenced in the manifest are redistributable by any party. If not, the unredistributable parts are using an extra-data source type.

It's all under open-source licenses


> - [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. 

Not sure who is officially maintaining PlasmTube right now, but personally I'm of course fine with publishing to Flathub

> - [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).

kde.org is owned by KDE, so that's fine.

2023-02-19 13:04 UTC, plata commented
bot, build org.kde.plasmatube

2023-02-19 14:28 UTC, JBBgameich commented
Can you update the python dependencies to the versions used in the current master branch? It seems like the yt-dlp version used in the stable release doesn't work with youtube any more.

2023-02-19 14:33 UTC, plata commented
bot, build org.kde.plasmatube

2023-02-20 08:31 UTC, barthalion commented
/merge @JBBgameich

2023-02-20 08:32 UTC, closed without merging