Add The Unofficial Homestuck Collection
flathub/flathub pull request #4042
Opened 2023-04-03 12:20 UTC by Grafcube

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub.   **Bambosh/unofficial-homestuck-collection#470**
- [ ] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *No patches necessary*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2023-04-03 12:28 UTC, hfiguiere commented on LICENSE
this is unecessary

2023-04-03 12:28 UTC, hfiguiere commented on dev.bambosh.UnofficialHomestuckCollection.desktop
> +Exec=/app/bin/run.sh
```suggestion
Exec=run.sh
```

2023-04-03 12:29 UTC, hfiguiere commented on dev.bambosh.UnofficialHomestuckCollection.yml
> +  - --socket=wayland
does this really support wayland out of the box?

2023-04-03 12:30 UTC, hfiguiere commented on dev.bambosh.UnofficialHomestuckCollection.yml
> +        url: https://github.com/Bambosh/unofficial-homestuck-collection/releases/download/2.0.5/unofficial-homestuck-collection-2.0.5.tar.gz
do I understand this is a x86_64 binary? how will that work on aarch64?

2023-04-03 12:33 UTC, hfiguiere requested changes
have the .desktop and appstream file been submitted for inclusion upstream?

2023-04-03 12:40 UTC, Grafcube commented on LICENSE
Done. I've removed the license file.

2023-04-03 12:44 UTC, Grafcube commented
> have the .desktop and appstream file been submitted for inclusion upstream?

I didn't know those had to be upstreamed. I'll make the PRs.

2023-04-04 01:47 UTC, GiovanH commented
TUHC member here checking in to say this is all fine and dandy. bambosh may be somewhat busy but you can always ping me for admin/compat stuff and I'll try to support asap

2023-04-04 05:18 UTC, Grafcube commented
I've changed the install path for the icons based on what I saw in other manifest files.

2023-04-04 08:48 UTC, Grafcube commented
What is the correct directory to install the icons and desktop file to? I can't seem to find any documentation on this.

2023-04-04 09:48 UTC, closed without merging