New app: io.github.twanvl.MagicSetEditor2
flathub/flathub pull request #4079
Opened 2023-04-18 18:45 UTC by subpop

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [ ] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

2023-04-18 19:08 UTC, hfiguiere commented on io.github.twanvl.MagicSetEditor2.desktop
> +Exec=/app/bin/magicseteditor
```suggestion
Exec=magicseteditor
```

2023-04-18 19:09 UTC, hfiguiere commented on io.github.twanvl.MagicSetEditor2-64.png
you don't need a 64px icon if it doesn't come from the upstream sources.

2023-04-18 19:10 UTC, hfiguiere commented on io.github.twanvl.MagicSetEditor2.metainfo.xml
> +</component>
missing mandatory screenshots.

2023-04-18 19:11 UTC, hfiguiere commented on io.github.twanvl.MagicSetEditor2.yaml
> +  - --filesystem=~/.magicseteditor
this should be 
```suggestion
  - --persist=.magicseteditor
```

2023-04-18 19:11 UTC, hfiguiere commented on io.github.twanvl.MagicSetEditor2.yaml
> +  - --socket=wayland
if it really supports wayland then it should be fallback-x11

2023-04-18 19:12 UTC, hfiguiere commented on io.github.twanvl.MagicSetEditor2.yaml
> +    sources:
(everywhere) sources is usually last.

2023-04-18 19:12 UTC, hfiguiere commented on io.github.twanvl.MagicSetEditor2.yaml
> +      - install -D --mode=755 ./magicseteditor /app/bin/
```suggestion
      - install -Dm755 ./magicseteditor -t /app/bin/
```

2023-04-18 19:14 UTC, hfiguiere commented
bot, build io.github.twanvl.MagicSetEditor2

2023-04-18 19:15 UTC, hfiguiere requested changes
the desktop, appstream and icon files should be submitted upstream.

2023-04-18 19:24 UTC, barthalion commented
There is no upstream activity since 2021 so I assume it's fine not to upstream anything.

2023-04-19 01:35 UTC, subpop commented
Yea, upstream is not dead, but it's extremely inactive. This is a program that has been limping along for the better part of a decade or more already. This upstream is a "keep-alive" fork as it is. I'll submit some of these changes upstream, but I don't expect them to be accepted.

2023-04-19 16:50 UTC, subpop commented
bot, build io.github.twanvl.MagicSetEditor2

2023-04-19 17:36 UTC, subpop commented
bot, build io.github.twanvl.MagicSetEditor2

2023-04-20 00:33 UTC, subpop commented
bot, build io.github.twanvl.MagicSetEditor2

2023-04-20 07:44 UTC, barthalion commented
/merge

2023-04-20 07:45 UTC, closed without merging