Add com.github.alainm23.planify
flathub/flathub pull request #4180
Opened 2023-05-26 22:21 UTC by alainm23

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions.
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. https://github.com/alainm23/planner
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. 

[reqs]: https://github.com/flathub/flathub/wiki/App-Requirements
[maint]: https://github.com/flathub/flathub/wiki/App-Maintenance
[submission]: https://github.com/flathub/flathub/wiki/App-Submission

I only want to use the beta branch for now, until we have a first stable release sometime in the future. We think that's a good way to keep users up to date to gather more user feedback.

2023-05-26 22:23 UTC, alainm23 commented
bot, build com.github.alainm23.planify

2023-05-26 22:32 UTC, alainm23 commented
bot, build com.github.alainm23.planify

2023-05-26 22:35 UTC, alainm23 commented
bot, build com.github.alainm23.planify

2023-05-26 23:28 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +    "app-id" : "com.github.alainm23.planify",
must be `io.github`

2023-05-26 23:28 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +        "--socket=session-bus",
this is not allowed. you need to determine which "talk names" you need.

2023-05-26 23:37 UTC, hfiguiere requested changes

2023-05-26 23:37 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +        "--metadata=X-DConf=migrate-path=/com/github/alainm23/planify/"
```suggestion
```

this is uncessary.

2023-05-26 23:37 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +                    "url" : "https://github.com/alainm23/planner.git"
you need a tag or a commit

2023-05-26 23:37 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +                "-Dprofile=development"
given that flathub is for users, I believe these build options might be incorrect.

2023-05-26 23:37 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +    ],
```suggestion
```

this is not needed

2023-05-26 23:37 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +    "app-id" : "com.github.alainm23.planify",
this is a fatal error

2023-05-26 23:37 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +        "--socket=session-bus",
this is a fatal error

2023-05-26 23:37 UTC, hfiguiere commented on com.github.alainm23.planify.json
> +                    "url" : "https://github.com/alainm23/planner.git"
this is a fatal error

2023-05-27 09:52 UTC, alainm23 commented
bot, build com.github.alainm23.planify

2023-05-27 10:08 UTC, alainm23 commented
bot, build io.github.alainm23.planify

2023-05-27 10:10 UTC, alainm23 commented
bot, build io.github.alainm23.planify

2023-05-27 10:21 UTC, alainm23 commented
bot, build io.github.alainm23.planify

2023-05-27 10:40 UTC, alainm23 commented
bot, build io.github.alainm23.planify

2023-05-27 14:00 UTC, hfiguiere commented on io.github.alainm23.planify.json
> +        "--talk-name=io.github.alainm23.planify"
this name is granted by default
```suggestion
```

2023-05-27 14:01 UTC, hfiguiere commented on io.github.alainm23.planify.json
> +        "--talk-name=io.github.alainm23.planify"
this name is granted by default

```suggestion
        "--talk-name=org.gnome.evolution.dataserver.Sources5"
```

2023-05-27 16:26 UTC, alainm23 commented
bot, build io.github.alainm23.planify

2023-05-29 06:11 UTC, barthalion commented
/merge:beta

2023-05-29 06:12 UTC, closed without merging