Add com.visualstudio.code.tool.host-spawn
flathub/flathub pull request #4267
Opened 2023-06-20 18:39 UTC by mdmundo

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:** [request to submit to Flathub](https://github.com/1player/host-spawn/issues/24)
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

2023-06-20 22:44 UTC, hfiguiere commented on flathub.json
you don't need `only-arches`. But you probably need `    "skip-icons-check": true`

2023-06-20 22:48 UTC, hfiguiere commented
bot, build com.visualstudio.code.tool.host-spawn

2023-06-20 22:56 UTC, hfiguiere requested changes
Missing an appstream file.

2023-06-20 23:10 UTC, mdmundo commented
bot, build com.visualstudio.code.tool.host-spawn

2023-06-20 23:18 UTC, mdmundo commented
bot, build com.visualstudio.code.tool.host-spawn

2023-06-20 23:25 UTC, mdmundo commented
bot, build com.visualstudio.code.tool.host-spawn

2023-06-21 00:05 UTC, hfiguiere commented on com.visualstudio.code.tool.host-spawn.metainfo.xml
> +  <project_license>MIT</project_license>
```suggestion
  <project_license>MIT-0</project_license>
```

according to the repository

2023-06-22 14:44 UTC, 1player commented
As the author of host-spawn, LGTM, go ahead :)

2023-06-25 13:35 UTC, hfiguiere commented
bot, build com.visualstudio.code.tool.host-spawn

2023-06-25 13:51 UTC, hfiguiere commented on com.visualstudio.code.tool.host-spawn.metainfo.xml
> +  <metadata_license>MIT-0</metadata_license>
seems that appstream doesn't like this. We prefer `CC0-1.0` for the metadata.

2023-06-26 10:20 UTC, mdmundo commented
bot, build com.visualstudio.code.tool.host-spawn

2023-06-26 10:27 UTC, mdmundo commented
@hfiguiere it can be checked again

2023-08-10 19:58 UTC, AlbertoFabbri93 commented
Is this getting merged? I have the problem this merge request is trying to fix...

2023-08-10 20:16 UTC, mdmundo commented
It is ready for merging. For now you can try the [build](https://github.com/flathub/flathub/pull/4267#issuecomment-1607162098) command, wait a few minutes and install it after build completion ([like this](https://github.com/flathub/flathub/pull/4267#issuecomment-1607167159)).

2023-08-10 23:52 UTC, AlbertoFabbri93 commented
Can I install this "branch" side by side with my regular install?

2023-08-10 23:59 UTC, mdmundo commented
> Can I install this "branch" side by side with my regular install?

@AlbertoFabbri93 Yeah, but keep in mind it becomes unavailable after some time. If you need to install it later again, then run the command again.

2023-08-11 13:23 UTC, AlbertoFabbri93 commented
bot, build com.visualstudio.code.tool.host-spawn

2023-08-11 14:10 UTC, AlbertoFabbri93 commented
I have installed the extension and added the following to my user `settings.json`:
```
"terminal.integrated.defaultProfile.linux": "host-spawn",
    "terminal.integrated.env.linux": {
        "LD_PRELOAD": null,
    },
    "terminal.integrated.profiles.linux": {
        "host-bash": {
            "path": "/usr/bin/flatpak-spawn",
            "args": [ "--host", "--env=TERM=xterm-256color", "bash" ]
        },
        "local": {
            "path": "bash"
        },
        "host-spawn": {
            "path": "/app/bin/host-spawn",
            "args": ["bash"],
            "icon": "terminal-bash",
            "overrideName": true
        },
    },
```
But in the folder `/app/bin/` there is no executable called `host-spawn`. Should I add something to the command line to start vscode with the extension enabled?

2023-08-11 16:26 UTC, mdmundo commented
iirc, u don't need the `/app/bin/` prefix

2023-08-11 22:23 UTC, AlbertoFabbri93 commented
I saw that path in the updated readme file...

Thank you very much, it works! And the errors are gone :)

2023-08-22 07:44 UTC, alatiera commented
bot, build com.visualstudio.code.tool.host-spawn

2023-08-22 09:52 UTC, alatiera commented
> u probably want to run `which host-spawn` to get the path

fwiw it should be `/app/tools/host-spawn/bin/host-spawn`

Seems to work okay so far. Honestly we should probably make that the default in the vscode faltpak cause both the current bash config and the hacked `script` snippet from https://github.com/flathub/com.visualstudio.code/issues/315 are not working well.

```
        "host-spawn": {
            "path": "/app/tools/host-spawn/bin/host-spawn",
            "args": ["bash"],
            "icon": "terminal-bash",
            "overrideName": true
        },
```

IMO better to go with https://github.com/flathub/com.visualstudio.code/pull/375

2023-08-22 14:04 UTC, closed without merging