Add net.imaginaryinfinity.Squiid
flathub/flathub pull request #4367
Opened 2023-07-26 23:39 UTC by TabulateJarl8

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
    - `--share=network` is required due to inter-process communication between the components of the application
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

2023-07-26 23:40 UTC, TabulateJarl8 commented
This is a reopened version of #4366 because it wouldn't allow me to add the generated sources file

2023-07-27 07:57 UTC, barthalion commented
bot, build net.imaginaryinfinity.Squiid

2023-07-27 13:34 UTC, hfiguiere requested changes
I don't see any icon, desktop, or appstream file installed.

This is the build failure on x86_64.

2023-08-14 04:24 UTC, TabulateJarl8 commented
Let me know if this looks good

2023-08-14 14:27 UTC, hfiguiere commented
why switching to PNG?

2023-08-14 14:28 UTC, hfiguiere commented on net.imaginaryinfinity.Squiid.metainfo.xml
> +  <summary>Squiid is a modular calculator written in Rust.</summary>
```suggestion
  <summary>Squiid is a modular calculator</summary>
```

2023-08-14 14:28 UTC, hfiguiere commented on net.imaginaryinfinity.Squiid.metainfo.xml
> +      Squiid is a modular calculator written in Rust. It is currently very early in development but it is intended to be the successor to ImaginaryInfinity Calculator.
```suggestion
      Squiid is a modular calculator. It is currently very early in development but it is intended to be the successor to ImaginaryInfinity Calculator.
```

2023-08-14 14:29 UTC, hfiguiere commented on net.imaginaryinfinity.Squiid.metainfo.xml
> +</component>
missing required `url`, `screenshots`, `releases`

2023-08-14 14:29 UTC, hfiguiere commented on net.imaginaryinfinity.Squiid.desktop
this file should be upstream

2023-08-14 14:29 UTC, hfiguiere commented on net.imaginaryinfinity.Squiid.metainfo.xml
this file should be upstream.

2023-08-14 14:31 UTC, hfiguiere commented on net.imaginaryinfinity.Squiid.desktop
> +Version=1.0.2
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

>  Version of the Desktop Entry Specification that the desktop entry conforms with. Entries that confirm with this version of the specification should use 1.5. Note that the version field is not required to be present.

2023-08-15 16:20 UTC, hfiguiere commented
bot, build net.imaginaryinfinity.Squiid

2023-08-15 16:31 UTC, hfiguiere commented
Seems like not all the crates are in the cargo-source

Was the Cargo.lock up to date when you generated it?

2023-08-15 16:36 UTC, TabulateJarl8 commented
It should've been up to date, I can double check it in a few hours and push the changes

2023-08-15 21:44 UTC, hfiguiere commented on net.imaginaryinfinity.Squiid.json
> +                "sha256": "d778e19581339bca9911d6738b3db0cfb92f74259a0b7a4b659d6a5d4375030b"
1. retagging like that is bad
2. it's `generated-sources.json` that needs to be updated.

2023-08-15 21:47 UTC, TabulateJarl8 commented
My bad, I completely forgot about that file

2023-08-15 21:49 UTC, hfiguiere commented
bot, build net.imaginaryinfinity.Squiid

2023-08-15 22:07 UTC, TabulateJarl8 commented
Oh I'm really dumb, i checked for that and missed it. Sorry for all the stupid mistakes, I'll fix that in a bit

2023-08-16 17:08 UTC, hfiguiere commented
bot, build net.imaginaryinfinity.Squiid

2023-08-16 17:11 UTC, TabulateJarl8 commented
It seems to have failed again, I have no idea why, it compiles on my machine. You it be against flathub's guidelines to build without using offline mode? I know its supposed to ensure the binary compiles, but it doesn't seem to be working in this instance

2023-08-16 17:13 UTC, TabulateJarl8 commented
Actually, the compiling seems to be an aarch64 issue. The caption text errors I can fix, but I don't know how to solce the compilation issue

2023-08-16 18:52 UTC, TabulateJarl8 commented
Is there any reason that the aarch64 build is getting the error `error: linker `aarch64-linux-gnu-gcc` not found`? Is that a configuration issue on my end?

2023-08-21 02:53 UTC, hfiguiere commented
it should just work. not sure.

2023-09-05 15:08 UTC, TabulateJarl8 commented
Am I supposed to do anything else before this is merged? I don't know if it's just from the old requested changes, but I'm seeing PRs that were merged yesterday so I just wanted to check that I don't need to do anything else

2023-09-07 08:20 UTC, closed without merging