Add fr.inria.corese.CoreseCommand
flathub/flathub pull request #4483
Opened 2023-09-05 08:22 UTC by remiceres

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

2023-09-05 12:07 UTC, hfiguiere commented on fr.inria.corese.CoreseCommand.yml
> +      - type: file
since the icons don'c come from upstream, keep the SVG, remove the bitmaps.

2023-09-05 12:07 UTC, hfiguiere commented on fr.inria.corese.CoreseCommand.yml
> +finish-args:
finish args is found above modules in general.

2023-09-05 12:08 UTC, hfiguiere commented on fr.inria.corese.CoreseCommand.desktop
> +Exec=/app/bin/run.sh
```suggestion
Exec=run.sh
```

2023-09-05 12:08 UTC, hfiguiere commented on fr.inria.corese.CoreseCommand.yml
> +command: /app/bin/run.sh
```suggestion
command: run.sh
```

2023-09-05 12:08 UTC, hfiguiere requested changes
~~desktop file is missing~~

nevermind

2023-09-05 12:11 UTC, hfiguiere commented
bot, build fr.inria.corese.CoreseCommand

2023-09-05 12:13 UTC, hfiguiere commented on fr.inria.corese.CoreseCommand.appdata.xml
> +<?xml version="1.0" encoding="UTF-8"?>
the same comments as on the other packages apply.

2023-09-05 12:14 UTC, hfiguiere commented on fr.inria.corese.CoreseCommand.yml
> +          - url-query: '"https://github.com/Wimmics/corese/releases/download/release-" + $version + "/corese-command-" + $version + ".jar"'
an object is expected for `x-checker-data`  not a list. that's what causing the list validation.

2023-09-05 12:23 UTC, hfiguiere commented
the icons, desktop and appstream file should be managed upstream for future releases.

2023-09-06 01:17 UTC, hfiguiere commented
bot, build fr.inria.corese.CoreseCommand

2023-09-06 06:46 UTC, remiceres commented
Thank you for the feedback. After testing, everything seems to be working correctly. Ready for merge.

2023-09-07 08:18 UTC, closed without merging