Add de.linuxguides.RechnungsAssistent
flathub/flathub pull request #4488
Opened 2023-09-06 11:06 UTC by Jean28518

**Notice: This app is only available in german language.** I didn't find any special instructions for that circumstance.

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am the upstream contributor to the project.
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission

2023-09-06 12:11 UTC, hfiguiere commented on de.linuxguides.RechnungsAssistent.yml
> +finish-args:
finish args is usually above modules.

2023-09-06 12:13 UTC, hfiguiere commented on de.linuxguides.RechnungsAssistent.yml
> +app-id: de.linuxguides.RechnungsAssistent
`linuxguides.de` doesn't see to exist.

2023-09-06 12:15 UTC, hfiguiere commented on de.linuxguides.RechnungsAssistent.desktop
also upstream has a .desktop file so you shouldn't have one here.

2023-09-06 12:15 UTC, hfiguiere requested changes
there is also no icon installed.

2023-09-06 14:48 UTC, Jean28518 commented on de.linuxguides.RechnungsAssistent.yml
> +finish-args:
Thanks!

2023-09-06 14:49 UTC, Jean28518 commented on de.linuxguides.RechnungsAssistent.desktop
Check, thank you

2023-09-06 15:22 UTC, Jean28518 commented
Thank you very much for your hints.
I hope I fixed everything.
Should I create a new PR from new-pr or is this okay?

2023-09-07 03:20 UTC, hfiguiere commented on de.linuxguides.RechnungsAssistent.yml
> +app-id: de.linuxguides.RechnungsAssistent
yeah that's ok. it didn't work when I checked.

2023-09-07 03:22 UTC, hfiguiere commented
bot, build de.linuxguides.RechnungsAssistent

2023-09-07 03:38 UTC, hfiguiere commented on de.linuxguides.RechnungsAssistent.metainfo.xml
this file is never installed.

2023-09-07 03:38 UTC, hfiguiere requested changes
no desktop file is installed either.

2023-09-07 07:59 UTC, Jean28518 commented
Thank you very much for your patience.
Please retry.

2023-09-07 09:21 UTC, Jean28518 commented
bot, build de.linuxguides.RechnungsAssistent

Thanks. Appdata in metainfo.xml is now in english.

2023-09-07 10:16 UTC, Jean28518 commented
bot, build de.linuxguides.RechnungsAssistent

2023-09-07 11:16 UTC, Jean28518 commented
bot, build de.linuxguides.RechnungsAssistent

2023-09-07 12:02 UTC, Jean28518 commented
From my side everything is done now.

2023-09-08 08:37 UTC, closed without merging