add cn.xfangfang.wiliwili
flathub/flathub pull request #4761
Opened 2023-12-06 14:38 UTC by pugaizai

### Please confirm your submission meets all the criteria

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:https://github.com/xfangfang/wiliwili/issues/252**
- [x] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

2023-12-06 14:40 UTC, madoka773 commented
This flatpak will be maintained by the author @xfangfang

2023-12-06 14:40 UTC, madoka773 commented
bot, build

2023-12-06 14:48 UTC, madoka773 commented
bot, build

2023-12-06 14:55 UTC, madoka773 commented
bot, build cn.xfangfang.wiliwili

2023-12-06 15:18 UTC, madoka773 commented
wait, need some jobs for aarch64

2023-12-06 16:19 UTC, madoka773 commented on cn.xfangfang.wiliwili.yaml
> +                url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.3.2.tar.gz
now it use prebuilt ffmpeg-full instead

2023-12-06 17:05 UTC, madoka773 commented
bot, build cn.xfangfang.wiliwili

2023-12-06 17:24 UTC, madoka773 commented
bot, build cn.xfangfang.wiliwili

2023-12-08 11:40 UTC, madoka773 commented
bot, build cn.xfangfang.wiliwili

2023-12-08 11:57 UTC, madoka773 commented
@xfangfang  it seeams that build failed caused by upstream opencc updates

2023-12-08 12:04 UTC, xfangfang commented
@madoka773 It's fixed now.

2023-12-09 03:17 UTC, hfiguiere requested changes
build failed.

2023-12-09 05:44 UTC, xfangfang commented
bot, build cn.xfangfang.wiliwili

2023-12-09 13:36 UTC, madoka773 commented
> build failed.

it is successed now.

2023-12-11 11:20 UTC, barthalion commented
bot, build cn.xfangfang.wiliwili

2023-12-11 12:28 UTC, barthalion commented
/merge

2023-12-11 12:28 UTC, closed without merging

2023-12-11 14:16 UTC, madoka773 commented
@barthalion hello, can you add the app's author @xfangfang to the [flathub repo](https://github.com/flathub/cn.xfangfang.wiliwili)? thanks.

2023-12-12 12:22 UTC, bbhtt commented
Can you please open an issue https://github.com/flathub/flathub/issues?

2023-12-12 17:43 UTC, madoka773 commented
Okay