Add io.github.Bitsafe_cli
flathub/flathub pull request #4792
Opened 2023-12-17 19:39 UTC by francivaldo4334

### Please confirm your submission meets all the criteria

- [yes] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [yes] My pull request follows the instructions at [App Submission][submission].
- [yes] I have [built][build] and tested the submission locally.
- [yes] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [yes] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [yes] I am an upstream contributor to the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [yes] I own the domain used in the application ID or the domain has a policy for delegating subdomains (e.g. GitHub, SourceForge).
- [yes] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

2023-12-17 20:18 UTC, hfiguiere commented on io.github.Bitsafe_cli.yaml
> +id: io.github.Bitsafe_cli
github based app-id have 4 components. `io.github`, the user or organization, and the application name.

this doesn't meet the requirements.

2023-12-17 20:18 UTC, hfiguiere commented on io.github.Bitsafe_cli.yaml
> +        - --share=network
this is not allowed. build MUST happen offline.

2023-12-17 20:18 UTC, hfiguiere commented on bitsafe/__main__.py
Flathube does NOT host the upstream sources. This doesn't belong here.

2023-12-17 20:19 UTC, hfiguiere requested changes
Also none of the icon, desktop file and appstream are provided and installed.

2023-12-17 21:14 UTC, francivaldo4334 commented
I corrected the id, added an image, added the .desktop and corrected the other files

2023-12-18 02:29 UTC, hfiguiere commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +        dest: bitsafe/
this doesn't exist.

2023-12-18 02:30 UTC, hfiguiere commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +  - name: runner
there is no reason to make this a separate module

2023-12-18 02:31 UTC, hfiguiere commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +  - name: app-install
the name is not explicit.
```suggestion
  - name: bitsafe
```

2023-12-18 02:33 UTC, hfiguiere requested changes
it's also missing the where to get the sources.

2023-12-18 02:34 UTC, hfiguiere commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +        path: setup.py
this file doesn't exist

2023-12-18 02:35 UTC, hfiguiere commented on io.github.francivaldo4334.Bitsafe_cli.desktop
> +Icon=/app/package/bitsafe_ic.png
exec is NOT an absolute path

Icon is always just a name. no path, no extension.

and the icon must be in a standard path, with an exportable name.

2023-12-18 14:15 UTC, francivaldo4334 commented
I corrected the errors, I will wait for the evaluation

2023-12-18 14:19 UTC, hfiguiere commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +        dest: bitsafe/
the comment was not to put it back.

Flatpak should get the source from the upstream repository. We do not host upstream projects. Just the the manifest to build the flatpak.

2023-12-18 14:19 UTC, hfiguiere commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +  - name: python3-requirements
this was fine were it was.

2023-12-18 14:24 UTC, francivaldo4334 commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +  - name: python3-requirements
hummn, ok thanks

2023-12-18 19:37 UTC, francivaldo4334 commented
Can you check again please

2023-12-18 22:11 UTC, hfiguiere commented on bitsafe_ic.png
this file is upstream and is also never referenced.

2023-12-18 22:11 UTC, hfiguiere commented on io.github.francivaldo4334.Bitsafe_cli.desktop
this file is upstream and is also never referenced.

2023-12-18 22:11 UTC, hfiguiere requested changes
there is still no appstream file
and the icon is never installed.

2023-12-19 22:38 UTC, francivaldo4334 commented
i fixed the paths

2023-12-22 07:51 UTC, barthalion commented
bot, build io.github.francivaldo4334.Bitsafe_cli

2023-12-22 14:53 UTC, bbhtt commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +      - install -Dm644 io.github.francivaldo4334.Bitsafe_cli.svg /app/share/icons/hicolor/scalable/apps/io.github.francivaldo4334.Bitsafe_cli.svg
https://github.com/francivaldo4334/Bitsafe_cli/blob/main/Dm644%20io.github.francivaldo4334.Bitsafe_cli.svg icon name has a stray Dm644 in front

2023-12-22 14:55 UTC, bbhtt commented on io.github.francivaldo4334.Bitsafe_cli.yaml
> +      - install -Dm644 io.github.francivaldo4334.Bitsafe_cli.svg /app/share/icons/hicolor/scalable/apps/io.github.francivaldo4334.Bitsafe_cli.svg
https://github.com/francivaldo4334/Bitsafe_cli/blob/main/Dm644%20io.github.francivaldo4334.Bitsafe_cli.svg icon name has a stray Dm644 in front

2025-02-26 00:50 UTC, closed without merging