Add rocks.poopjournal.librelinkupdesktop
flathub/flathub pull request #5086
Opened 2024-03-25 23:44 UTC by CrazyMarvin

### Please confirm your submission meets all the criteria

- [X] Please describe your application briefly.
- [X] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [X] My pull request follows the instructions at [App Submission][submission].
- [ ] I have [built][build] and tested the submission locally.
- [X] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [X] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [X] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [X] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

2024-03-25 23:48 UTC, CrazyMarvin commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-03-25 23:48 UTC, hfiguiere commented on rocks.poopjournal.librelinkupdesktop.yml
> +        path: ..
and where do you think `..` points to?

2024-03-25 23:48 UTC, hfiguiere commented on rocks.poopjournal.librelinkupdesktop.yml
> +      - generated-sources.json
and what about this?

2024-03-25 23:49 UTC, hfiguiere requested changes
also I don't see any icons, .desktop or appstream file installed.

2024-03-25 23:52 UTC, CrazyMarvin commented
> also I don't see any icons, .desktop or appstream file installed.

I just copied it from the [sample](https://github.com/flathub/electron-sample-app/blob/master/flatpak/org.flathub.electron-sample-app.yml) and hoped it would build. 😅
I will have a closer look later.

2024-03-29 22:24 UTC, CrazyMarvin commented
Do you recommend to put some files like the Flathub Manifest or MetaInfo File into the upstream repo or is it fine to have everything just here?

2024-03-29 22:26 UTC, hfiguiere commented
> Do you recommend to put some files like the Flathub Manifest or MetaInfo File into the upstream repo or is it fine to have everything just here?

Upstream is always best. The ideal flathub repo contain only the manifest file.

2024-03-29 22:28 UTC, hfiguiere commented
Definitely NEVER the upstream source or distribution

In that case the `generated-sources.json` is missing should be in the repo.

2024-04-03 04:00 UTC, hfiguiere commented on rocks.poopjournal.librelinkupdesktop.yml
> +      - ls -la release-build/librelinkupdesktop-linux-x64
```suggestion
```

2024-04-03 04:00 UTC, hfiguiere commented on rocks.poopjournal.librelinkupdesktop.yml
> +      - npx electron-packager . librelinkupdesktop --overwrite --platform=linux --arch=x64 --out=release-build --prune=true --electron-version=27.3.4 --app-version=0.1.3
so how does that work on aarch64?

2024-04-03 04:01 UTC, hfiguiere commented on rocks.poopjournal.librelinkupdesktop.yml
> +      - npx electron-packager . librelinkupdesktop --overwrite --platform=linux --arch=x64 --out=release-build --prune=true --electron-version=27.3.4 --app-version=0.1.3
also app-version 0.1.3 but tarball is 0.1.4. Am I missing something?

2024-04-03 12:29 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-03 12:30 UTC, fperera123 commented
> also I don't see any icons, .desktop or appstream file installed.

These are now added

2024-04-03 12:55 UTC, hfiguiere commented on rocks.poopjournal.librelinkupdesktop.yml
> +      - npx electron-packager . librelinkupdesktop --overwrite --platform=linux --arch=x64 --out=release-build --prune=true --electron-version=27.3.4 --app-version=0.1.3
0.1.5

2024-04-04 01:31 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-04 14:24 UTC, bbhtt commented on rocks.poopjournal.librelinkupdesktop.yml
> +      - install -Dm444 flathub/rocks.poopjournal.librelinkupdesktop.metainfo.xml /app/share/metainfo/rocks.poopjournal.librelinkupdesktop.metainfo.xml
It's `Apache-2.0` https://spdx.org/licenses/

2024-04-05 00:32 UTC, bbhtt commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-05 14:02 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-05 14:45 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-05 15:29 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-05 20:37 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-05 21:40 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-05 23:46 UTC, CrazyMarvin commented
> Build [112598 successful](https://buildbot.flathub.org/#/builders/6/builds/112598) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/95408/rocks.poopjournal.librelinkupdesktop.flatpakref
> ```

This looks fine. 🥳

2024-04-06 02:03 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-06 02:05 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-06 10:34 UTC, bbhtt commented on rocks.poopjournal.librelinkupdesktop.yml
> +      - ls -la release/build/linux*unpacked
```suggestion
```

2024-04-06 17:00 UTC, fperera123 commented
bot, build rocks.poopjournal.librelinkupdesktop

2024-04-07 19:00 UTC, closed without merging

2024-04-07 19:04 UTC, CrazyMarvin commented
Thanks to everyone! 😍