Add io.github.riftr.intelpy
flathub/flathub pull request #5111
Opened 2024-03-31 06:42 UTC by Riftr

### Please confirm your submission meets all the criteria

- [x ] Please describe your application briefly.
 IntelPy is a cross-platform chat log monitor and alert system for the game Eve Online.

- [x] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [x] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [x] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [x] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [x] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [x] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

2024-03-31 11:41 UTC, bbhtt commented on io.github.riftr.intelpy.yml
> +
You need to cleanup the baseapp from development files https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp?tab=readme-ov-file#example-pyqtwebengine-application cleanup-commands.

2024-03-31 13:07 UTC, hfiguiere commented
The top of the PR template say the PR should be made against the `new-pr` branch. This is not the case.

2024-03-31 13:08 UTC, hfiguiere commented on io.github.riftr.intelpy.yml
> +  - --filesystem=~
this is an invalid filesystem....

2024-03-31 13:09 UTC, hfiguiere requested changes
I don't see any of the required .desktop, icon and appstream file installed.

2024-04-02 11:51 UTC, Riftr commented
> I don't see any of the required .desktop, icon and appstream file installed.

I've added these now. I had them ready in my own repo and I wasn't sure if I needed to specifically move them.

2024-04-02 14:39 UTC, bbhtt commented
bot, build io.github.riftr.intelpy

2024-04-03 01:29 UTC, bbhtt commented
YOu have to change the screenshots to raw.githubusercontent.com links like this https://raw.githubusercontent.com/Riftr/intelpy/master/intelpy/externals/Intelpy-2-main.png

It has to be a direct link, a link to a page won't work.

2024-04-04 04:21 UTC, Riftr commented
> You have to change the screenshots to raw.githubusercontent.com links like this https://raw.githubusercontent.com/Riftr/intelpy/master/intelpy/externals/Intelpy-2-main.png
> 
> It has to be a direct link, a link to a page won't work.

I've made and pushed the change for this now too.

2024-04-04 14:25 UTC, bbhtt commented
You have to update the tag/commit here.

2024-04-05 05:18 UTC, Riftr commented
> You have to update the tag/commit here.

New release has been added here.

2024-04-05 13:13 UTC, bbhtt commented
bot, build io.github.riftr.intelpy

2024-04-07 19:11 UTC, closed without merging

2024-04-08 05:05 UTC, Riftr commented
Accepted, thank you!