Org.sugarlabs.calculate
flathub/flathub pull request #5455
Opened 2024-07-29 18:20 UTC by SudoSu-bham

### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly.
It is a graphing calculator, which can get the answer to a quick problem, but that is not the limit! we can also explore Algebra, Trigonometry, Boolean and more!

- [X] The domain used for the application ID is [controlled by the application developers][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read the and followed all the [Submission and licence requirements][reqs].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about this submission. **Link:**

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

2024-07-30 02:22 UTC, bbhtt commented
cc @tchx84

bot, build org.sugarlabs.Calculate

2024-07-30 11:56 UTC, tchx84 commented
@SudoSu-bham the PR looks OK but, I suspect there's something missing in terms of screen dimension measurements. If I run the application 1280x720 it doesn't fit in the screen and ends up like this. Can you double check this?

![Screenshot from 2024-07-30 07-47-35](https://github.com/user-attachments/assets/5291f9a2-38b2-4e3f-8734-a4f40235af51)

2024-08-09 21:43 UTC, SudoSu-bham commented
@tchx84 Please review the changes.

2024-08-12 11:40 UTC, tchx84 approved these changes

2024-08-12 11:40 UTC, tchx84 commented on calculate-info.patch
> +-license = GPLv2+
Keep the license please, see https://github.com/sugarlabs/calculate-activity/blob/master/COPYING

2024-08-12 11:41 UTC, tchx84 requested changes
See license comment

2024-08-12 11:41 UTC, tchx84 commented
bot, build org.sugarlabs.Calculate

2024-08-13 21:13 UTC, tchx84 commented
bot, build org.sugarlabs.Calculate

2024-08-13 21:31 UTC, tchx84 requested changes

2024-08-13 21:31 UTC, tchx84 commented on calculate-info.patch
> ++summary = It is a graphing calculator
We need a better summary here, like "An infix-notation graphing calculator" ?

2024-08-13 21:31 UTC, tchx84 commented on calculate-port.patch
> ++from sugarapp.helpers import PrimaryMonitor
Place this in a separate `*-monitors.patch` like we do with all the other apps.

2024-08-16 00:08 UTC, tchx84 commented
bot, build org.sugarlabs.Calculate

2024-08-16 00:17 UTC, tchx84 approved these changes

2024-08-16 00:18 UTC, tchx84 commented
@SudoSu-bham looks great now, thanks! CC @bbhtt

2024-08-22 09:13 UTC, closed without merging