Add io.github.umair_khurshid.caesar_cipher
flathub/flathub pull request #5864
Opened 2024-11-20 15:05 UTC by Umair-khurshid

### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly. 
- [X] The domain used for the application ID is [controlled by the application developer(s)][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read and followed all the [Submission requirements][reqs] and the [Submission guide][reqs2].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor to the project. If not, I contacted upstream developers about this submission. **Link:** N/A (I am the developer).

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[reqs2]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

2024-11-20 15:09 UTC, hfiguiere commented
> Please describe the application briefly. 

Still missing

2024-11-20 15:10 UTC, hfiguiere commented on .flatpak-builder/ccache/disabled/ccache.conf
this doesn't belong here.

2024-11-20 15:10 UTC, hfiguiere requested changes
none of the comment from the previous PR were addressed.

2024-11-20 15:11 UTC, hfiguiere commented on caesarcipher.png
this should be upstream

2024-11-20 15:11 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.metainfo.xml
this should be upstream

2024-11-20 15:11 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.metainfo.xml
> +</component>
missing mandatory screenshot, release

2024-11-20 15:12 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.metainfo.xml
> +  <icon type="stock">caesarcipher</icon>
don't use stock icons

```suggestion
```

2024-11-20 15:13 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.yml
> +        url: https://github.com/Umair-khurshid/caesar-cipher.git
you need a specific revision. not putting a branch is like putting one.

2024-11-20 15:15 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.metainfo.xml
> +  <developer id="com.umair">
it doesn't look like `umair.com` is you.

2024-11-20 15:15 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.yml
> +  - Utilities
```suggestion
```

but I still don't see which part of the doc suggested these.

2024-11-20 15:16 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.yml
> +  - --share=network
it's hard to tell but does this really require network?

2024-11-20 15:17 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.yml
> +  - --filesystem=home
does this require filesystem access?

2024-11-20 15:17 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.yml
> +      - gcc -o caesar caesar.c
no build system?

2024-11-20 15:18 UTC, hfiguiere commented on io.github.umair_khurshid.caesar_cipher.yml
> +      - install caesar /app/bin/
```suggestion
      - gcc -o caesar caesar.c
      - install -Dm755 caesar -t /app/bin/
```

2024-11-21 02:21 UTC, bbhtt commented
Please remove the commits from the master branch of this repo and rebase this to new-pr branch properly.

2024-12-12 21:18 UTC, closed without merging